### ISSUE TITLE
shouldn't have 0x111111... in the blob file if user specified some apnonce?

### ISSUE THREAD

**Issue by blanxd** [airsquared/blobsaver#100]
**Describe the what you'd like**
I understand that it doesn't affect any functionality, but I was 1st confused/scared as to why the blob file sayd 0x1111.. for the generator key when I had specified another apnonce manually, seems you always give that value for the --generator arg to tsschecker. Perhaps might give the user also the option to (optionally) input their generator with the apnonce so it gets saved nicely in the file? Even for safekeeping, so it's all saved in one place, generator value in the file and the apnonce in the filename...

**Optional screenshot**
Add any screenshots about the feature request here.

**Comment by blanxd** [comment]
Hi, thanks, an "advanced" opt might be the right thing to do, indeed.
Me personally, I don't care in the end :) Was just thinking, if I got startled for a second, so might any other user. Especially for the A12 and Chimera users, who do NOT have it set to 111 by default, so in the end, the generator actually isn't really 111 if you specify some different apnonce, ie. a little technical inaccuracy in the blob file.
So there could be some explanation in the GUI explaining that if you paste your apnonce there, the generator string doesn't affect anything and is simply for the sake of saving it, and defaults to 0x1111..
(unless it actually has an effect on tsssaver, I don't know about that really, does the --apnonce in fact override --generator ?)

**Comment by airsquared** [comment]
If an apnonce is manually specified, the generator has no effect. I'll add it to the wiki/help menu.

**Comment by 420Dope** [comment]
I have the same effect and startled for a second i look into the blob and see the 0x1111... generator. So i go to here and would make a new issue and found this issue here.
It would nice if the user use a "Manually specify apnonce", the generator was not shown in the blob file like on TSS Saver by 1 Conan.

**Comment by airsquared** [comment]
This has been fixed and will be released in v2.5.0.
