### ISSUE TITLE
Cannot save blobs for IOS13 official version

### ISSUE THREAD

**Issue by NavePnow** [airsquared/blobsaver#106]
**Describe the bug**
Cannot save blobs for IOS13 official version

**Screenshots**
![image](https://user-images.githubusercontent.com/39482599/65292816-77e5d980-db8b-11e9-8fb9-b73a4f28d671.png)

**Desktop (please complete the following information):**
 - macOS Mojave 10.14.6
 - App version 2.3.2

**Log(s)**
Version: 51a1c1745e58a2f26cb792615efa90d169618e4e - 336
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "C1C821E13002E" to dec:3409044896415790 hex:c1c821e13002e
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmware URL for iOS 13.0 build 17A577
[TSSC] opening Buildmanifest for iPhone10,3_13.0_17A577
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2019FallFCS/fullrestores/061-08721/B905C96C-C875-11E9-8C18-F4CC329DFA63/iPhone10,3,iPhone10,6_13.0_17A577_Restore.ipsw

PKKK?
��[Error] [LFZP] failed to open URL
[Error] [TSSC] ERROR: could not get BuildManifest for firmware URL http://updates-http.cdn-apple.com/2019FallFCS/fullrestores/061-08721/B905C96C-C875-11E9-8C18-F4CC329DFA63/iPhone10,3,iPhone10,6_13.0_17A577_Restore.ipsw

[Error] [TSSC] checking TSS status failed!

If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
Thanks for the bug report, I've found out the issue and I'm working on a fix.

**Comment by airsquared** [comment]
This issue has been fixed in v2.4.0.
