### ISSUE TITLE
iPad Mini 5 cannot save blobs

### ISSUE THREAD

**Issue by gummykage** [airsquared/blobsaver#110]
**Describe the bug**
Filled out ECID selected iPad mini 5 (Cellular) 11,2, selected All Signed Version, and used with and without manually sepecify Apnonce resulted in an error to fill out this bug report when trying to save blobs.

**Desktop (please complete the following information):**
 - OS: Windows 7 64bit up to date
 - App version 2.4.0

**Log(s)**
`
tsschecker = C:\Program Files (x86)\blobsaver\tsschecker.exe
Running: [C:\Program Files (x86)\blobsaver\tsschecker.exe, --generator, 0x1111111111111111, --nocache, -d, iPad11,2, -s, -e, 117DDE1A91002E, --save-path, D:\Users\x\Desktop\Jailbreak\_Saved from Conan\New_Blobs, --apnonce, 9c0951501e9bd68d76b9886f7f20b4ee9990aae364f651fae00dbe9f8a977ba0, -m, C:\Users\x\AppData\Local\Temp\BuildManifest8624229461899825694.plist]
Version: 0d099b1f4db86d48e7a0bee309a12294a1a3b002 - 352
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "117DDE1A91002E" to dec:4923467486003246 hex:117dde1a91002e
[TSSC] manually specified ApNonce to use, parsed "9c0951501e9bd68d76b9886f7f20b4ee9990aae364f651fae00dbe9f8a977ba0" to hex:9c0951501e9bd68d76b9886f7f20b4ee9990aae364f651fae00dbe9f8a977ba0
[TSSC] opening C:\Users\Bx\AppData\Local\Temp\BuildManifest8624229461899825694.plist
[Error] [TSSR] can't find boardconfig for device=iPad11,2 please use --boardconfig
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[Error] [TSSR] can't find boardconfig for device=iPad11,2 please use --boardconfig
[Error] [TSSR] Error: could not get id0 for installType=Update
[Error] [TSSR] faild to build TSS request

[Error] [TSSC] checking TSS status failed!
`

**Comment by airsquared** [comment]
Try this: [blobsaver-windows.exe.zip](https://github.com/airsquared/blobsaver/files/3640390/blobsaver-windows.exe.zip)

**Comment by gummykage** [comment]
@airsquared This fixed it! Was able to save blobs for iPad mini 5 12.4.1. Seems like apple has not updated ipad mini 5 with 13 yet. lol Not sure what's going on with that.

Thank you so much!
