### ISSUE TITLE
iPad Air not compatible (?)

### ISSUE THREAD

**Issue by NewbieDew** [airsquared/blobsaver#111]
Using the tool to read from device gives me an error (picture 1)
![Capture 1](https://user-images.githubusercontent.com/20828176/65516741-dc819b00-dee1-11e9-81d9-e3c8d074fd4e.PNG)

When everything is filled out manually it just gives me this: 
![Capture 2](https://user-images.githubusercontent.com/20828176/65516891-194d9200-dee2-11e9-8207-23c6b3933b46.PNG)

It's on window, I do not know if it's a bug on MacOS.

Also my Xs Max works perfectly

**Comment by airsquared** [comment]
You didn't fill out the issue template; please create a new issue with the issue template filled out. Closing.
