### ISSUE TITLE
Blobsaver 2.4.0

### ISSUE THREAD

**Issue by demlanhlung** [airsquared/blobsaver#112]
http://updates-http.cdn-apple.com/2019FallFCS/fullrestores/061-07273/DCA7D0F0-D986-11E9-ADEC-8420DCDBD6A3/iPhone10,3,iPhone10,6_13.1_17A844_Restore.ipsw

**Comment by airsquared** [comment]
If you have a bug report please create a new issue with the bug report filled out. Closing as spam.
