### ISSUE TITLE
Support for iOS 12.4.2

### ISSUE THREAD

**Issue by TipzTeam** [airsquared/blobsaver#114]
Please add the support for iOS 12.4.2, as Apple have just released this version for all devices that support iOS 12. Here is an example for a supported device: iPad Air 2: <a href="https://updates.cdn-apple.com/2019SummerFCS/fullrestores/061-20502/FD3F2C24-DC8C-11E9-9BB8-1D8C66A83945/iPad_64bit_TouchID_12.4.2_16G114_Restore.ipsw">iOS 12.4.2 for iPad Air 2</a>

**Comment by TipzTeam** [comment]
Also, you should add support for iOS 13.1 and 13.2

**Comment by airsquared** [comment]
The iPad Air 2 doesn't support 12.4.2:
![iPhone 6s and later, iPad Air 2 and later, iPad mini 4 and later, and iPod touch 7th generation](https://user-images.githubusercontent.com/36649395/66261768-2bec8480-e788-11e9-85e2-6cb17291a325.png)

It usually takes a few minutes to an hour for ipsw.me to work for new iOS versions, it should be working now for iOS 13.

**Comment by TipzTeam** [comment]
Yes it does, ipsw.me said it

**Comment by airsquared** [comment]
It literally says on Apple's official website that the iPad Air 2 doesn't support iOS 12.4.2.

**Comment by airsquared** [comment]
Also, ipsw.me doesn't say that the iPad Air 2 supports 12.4.2:

https://ipsw.me/iPad5,3
