### ISSUE TITLE
JRELoadError

### ISSUE THREAD

**Issue by theb1g0ne** [airsquared/blobsaver#115]
Remove the following line and the text above it before submitting this issue:

**Describe the bug**
When opening the app, a JRELoadError occurs

**Desktop (please complete the following information):**
 - OS:  macOS Mojave
 - App version: 2.4.0

**Screenshots**
![Screen Shot 2019-10-04 at 11 04 18 AM](https://user-images.githubusercontent.com/7306182/66218394-18adbc00-e697-11e9-94ad-462d8c2f28d4.png)

**Comment by airsquared** [comment]
https://github.com/airsquared/blobsaver/wiki/'JRELoadError'-when-trying-to-launch-the-application
