### ISSUE TITLE
requesting access to keystrokes in other apps (keylogging)

### ISSUE THREAD

**Issue by halpz** [airsquared/blobsaver#119]
**Describe the bug**
The app requires access to keystrokes even from other apps?
makes me think there is a keylogger installed? or is there another use for this?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - App version 2.4.0

**Comment by airsquared** [comment]
blobsaver should not be requesting to access keystrokes. Are you sure you got blobsaver from [here](https://github.com/airsquared/blobsaver/releases)? Where did you get Java from?

**Comment by airsquared** [comment]
If you still have any problems, please create a new issue.
