### ISSUE TITLE
a stupid question i still want to know

### ISSUE THREAD

**Issue by nssiwi** [airsquared/blobsaver#120]
**Describe the bug**
i installed java using zip files, and i am sure the java environment variables is correct, but it still remind me of installing java while open blodsaver

here is my **environment variables** for java:
**JAVA_HOME**: D:\Program Files\Java\jdk1.8.0_131
**Path**: %JAVA_HOME%\bin;%JAVA_HOME%\jre\bin;
**CLASSPATH**:.;%JAVA_HOME%\lib;D:\Program Files\Java\jdk1.8.0_131\lib\dt.jar;D:\Program Files\Java\jdk1.8.0_131\lib\tools.jar;

**Screenshots**
here is the screenshots:
https://s2.ax1x.com/2019/10/31/KIrOzD.png
https://s2.ax1x.com/2019/10/31/KIrLRO.png

**Desktop (please complete the following information):**
 - OS: win10 17763.805
 - App version 2.4.0

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
Try installing Java from [here](https://java.com/inc/BrowserRedirect1.jsp).

**Comment by airsquared** [comment]
Please create a new issue if you still have an issue with this.
