### ISSUE TITLE
Identifier null for iPhone 11 Pro

### ISSUE THREAD

**Issue by yspreen** [airsquared/blobsaver#122]
**Describe the bug**
Cannot find identifier "null"

**Screenshots**
![image](https://user-images.githubusercontent.com/12631527/68088719-c4316400-fe2f-11e9-9a36-312a17803d62.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - App version: v2.4.0

**Comment by SemoTech** [comment]
Same here, as it seems no one can handle generating blobs for the iPhone 11 Pro (iPhone12,3) or iPhone 11 Pro Max (iPhone12,5) models.  The 1conan.com website has not been updated either and maxes out at iPhone XR.

Is there really a fix or do we have to keep waiting?

**Comment by SemoTech** [comment]
Looks like tihmstar's tsschecker was updated to build 300 on 11/4/2019, just before Apple stopped signing 13.1.2 and 13.1.3. Also, the 1conan site is now updated to support iPhone 12,5, however bobsaver still does not recognize A13 devices and needs an update.

**Comment by y-spreen** [comment]
@SemoTech I dont think 1conan is updated

**Comment by SemoTech** [comment]
@y-spreen Only the blob verify feature for now, not the save blobs yet.

**Comment by airsquared** [comment]
I am trying to add support for the newer devices at the moment, but I'm having trouble compiling the latest versions of tsschecker, which actually adds support for those new devices.

**Comment by airsquared** [comment]
Please see #130 for updates on this.
