### ISSUE TITLE
Blobsaver is running but I cannot open the window

### ISSUE THREAD

**Issue by Dolyfin** [airsquared/blobsaver#125]
**Describe the bug**
Blobsaver is already running, Exiting. I have no way of turning off the background mode and nothing shows up in task manager that i am able to close. This happened after I put it in background mode.

**Desktop (please complete the following information):**
 - OS: win 10 1903
 - App version 2.4

**Comment by airsquared** [comment]
Does the issue persist after restarting your computer?

**Comment by airsquared** [comment]
Closing this issue as a duplicate of #84.
