### ISSUE TITLE
Error saving

### ISSUE THREAD

**Issue by MariusSolaat** [airsquared/blobsaver#13]
![1](https://user-images.githubusercontent.com/20828176/46668039-a8777200-cbcb-11e8-8a76-d5ab22954bab.PNG)
![2](https://user-images.githubusercontent.com/20828176/46668040-a8777200-cbcb-11e8-97d5-a0c47d74640f.PNG)

On newest windows 10 update

**Comment by airsquared** [comment]
Thanks for submitting a bug report. It'll be fixed in the next version. I'll close this issue(duplicate of #12).

**Comment by airsquared** [comment]
Just so you know, this has been fixed in v2.2.1.
