### ISSUE TITLE
No Internet Connection error but can go to ipsw.me.

### ISSUE THREAD

**Issue by ikeacat** [airsquared/blobsaver#137]
**Describe the bug**
I filled out the form like I always do, but it gave me an internet connection error. I could connect to ipsw.me.

**Screenshots**
[The Screenshot](https://i.postimg.cc/sDc86NhQ/issuereport.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - App version 2.4.1

**Comment by airsquared** [comment]
What iOS device do you have?

**Comment by ikeacat** [comment]
> 
> 
> What iOS device do you have?

I have an iPhone XR.

**Comment by airsquared** [comment]
Are you able to successfully download the ipsw from [this url](http://updates-http.cdn-apple.com/2020WinterFCS/fullrestores/061-20302/454ACB32-D3F6-4984-92CB-27C8FA368165/iPhone11,8,iPhone12,1_13.4_17E255_Restore.ipsw)? If you are please try again with blobsaver, ipsw.me may have been down when you were attempting to save blobs earlier.

**Comment by ikeacat** [comment]
I was able to download the IPSW file but it still gives me the error.

**Comment by airsquared** [comment]
Can you open the debug log before attempting to save blobs and paste the output here?

**Comment by ikeacat** [comment]
It doesn't output to the Debug log. [there is a video if ur confused.](https://youtu.be/rf5vT2jMQcM)

**Comment by airsquared** [comment]
Thanks, I think I have found the error and am working on a fix.

**Comment by airsquared** [comment]
Please try [this](https://github.com/airsquared/blobsaver/files/4478825/blobsaver-windows.exe.zip) and tell me if it works.

**Comment by ikeacat** [comment]
I still get the same error.

**Comment by airsquared** [comment]
Do you have a firewall or antivirus on your computer or network?

**Comment by airsquared** [comment]
I've found the bug; the problem is that inputting the identifier manually causes this error but using the drop-down menu still works, please use that instead until I am able to fix it.
