### ISSUE TITLE
blobsaver

### ISSUE THREAD

**Issue by KillCoffe** [airsquared/blobsaver#138]
YOUR ISSUE WILL BE CLOSED AND/OR DELETED IF YOU DO NOT FILL OUT THIS TEMPLATE

Remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
clicked on read from connected device

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Mojave]
 - App version [e.g. 1.1.1]

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
Issue template is not filled out, please create a new issue with the template filled out. Closing.
