### ISSUE TITLE
The developer cannot be verified

### ISSUE THREAD

**Issue by iammanpreetsingh** [airsquared/blobsaver#139]
YOUR ISSUE WILL BE CLOSED AND/OR DELETED IF YOU DO NOT FILL OUT THIS TEMPLATE

Remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Somehow I was not able to open the app because It was saying "The developer cannot be verified (See Screenshot 1). I have already allowed apps from anywhere in macOS Gatekeeper but still was not able to open it. I also didn't find the "Open Anyway option under Security>General. 
But I fixed it by going into Finder the "control+click the application and then choose open and it worked. (See screenshot 2)**

A clear and concise description of what the bug is and the expected behavior.
I really don't know if it's a bug or something a new thing in Catalina. But it was supposed to open without doing anything. 
**Screenshots**
Screenshot 1: https://imgur.com/chk2nrt
Screenshot 2: https://imgur.com/RyB7ruY

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - App version v2.5.0

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
You have to right-click (or control-click) on the app and click "Open". Apple changed something in macOS Catalina that requires developers to sign & notarize apps to remove this warning, and this requires a $100 developer account (which I don't have).
