### ISSUE TITLE
Not able to click any Blobsaver items in the menu bar when it's open

### ISSUE THREAD

**Issue by iammanpreetsingh** [airsquared/blobsaver#140]
YOUR ISSUE WILL BE CLOSED AND/OR DELETED IF YOU DO NOT FILL OUT THIS TEMPLATE

Remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
Hmm, this is weird. When I opened the Blobsaver and choose a menu item, it was not clicking/selecting. But then I went out of the app and got back in and it's working fine. Just see the screen recording, you will understand. 

**Screenshots**
Screen Recording: https://imgur.com/8L5QAo7

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - App version v2.5.0

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
I am unable to reproduce this issue on my own machine. Try restarting your computer. 

Do you have any apps that modify window/system behavior? (like TinkerTool)

**Comment by iammanpreetsingh** [comment]
i have these apps installed: https://imgur.com/PbbPqjq https://imgur.com/10mgXwZ https://imgur.com/wRfDuHD
let me know.

**Comment by airsquared** [comment]
Looking at your list, it *might* be Dozer or Magnet. I've never used either of these apps so I'm not sure, but it could be a possibility.
