### ISSUE TITLE
Apnonce "Read from Device" new option in v2.5.0?

### ISSUE THREAD

**Issue by timidhermit** [airsquared/blobsaver#141]
I notice that v2.5.0 has a new option which now requires mandatory declaration of apnonce, with an option to "read from device". I have some questions about this feature use for iOS 13.x:

1. Can I use the "read from device" option to extract apnonce for a device that is NOT jailbroken? If so, does it support all 64-bit devices? If not, what devices are not supported?
2. Am I correct that device-specific apnonce (not faked apnonce) is only necessary for A12 and higher devices? If so, is it possible to save the SHSH2 blobs using the standard apnonce used in previous blobsaver versions?
3. For non-jailbroken devices, is there another Windows desktop applications or clients to extract apnonce? Or is there a website or app which I can install on the non-jailbroken devices to see the apnonce so that I can manually copy it down?

**Comment by airsquared** [comment]
1. Yes: you do not have to set a generator prior to getting the apnonce (but then the ; all devices are supported
2. blobsaver only requires an apnonce for devices with A12 or higher, you can uncheck it if you do not have an A12 or higher device.
3. blobsaver does this, you dont need any other applications

**Comment by timidhermit** [comment]
Thanks for the answers.

Does v2.5.0 requires iTunes (or components of it) for it to work in Windows, especially with the "Read from device" feature to read off the apnonce?
Will the apnonce ever change over time for a specific device? In other words, once I extracted it, can I use the SAME apnonce for the SAME device in ALL future blob saves so I do NOT need to reconnect the device to read the apnonce each time?

**Comment by airsquared** [comment]
For reading any information from a connected device, blobsaver requires Apple's iOS drivers (which iTunes automatically installs).

The apnonce can change if you attempt to update/restore your device. It may also change if you enter recovery mode multiple times (I am unsure about it changing in recovery mode, but you can test it by attempting to read the apnonce multiple times).

**Comment by timidhermit** [comment]
Can you clarify what you mean by "the apnonce can change if you attempt to update/restore your device"? Are you saying that, once I upgraded to a newer iOS version or downgrade to an older iOS on the device, I have to reconnect the device to let blobsaver read the "new" apnonce in order to save all current and future blobs? If such is the case, then what happens to the validity of all previously saved blobs that were based on the "old" apnonce when the device was on a previous firmware. I am very confused now on this matter...

Is there a situation when this is not necessary so that the apnonce will not change?

**Comment by airsquared** [comment]
If your apnonce changes, the blobs you have saved using that nonce will become useless unless you have a jailbreak that allows you to set the nonce. The nonce can change if you update/restore your device, or (unsure about this part, you can test it by attempting to get the nonce with blobsaver multiple times) if you enter recovery mode multiple times.

The best way to make sure you don't have to worry about this is to set a generator on your device using a jailbreak beforehand.

**Comment by gitchamp** [comment]
Then I’m confused by what I’m reading. If you’re on an A13 device and update to a version of iOS that can’t be jailbroken and you want to use your blobs and apnonce to downgrade, you can’t because the apnonce changed when you upgraded and you can’t set it to the old one without jailbreaking again so you saved your blobs in order to downgrade for nothing?

**Comment by airsquared** [comment]
It's useful if you want to upgrade to an iOS version that isn't signed but is jailbreakable. For example, blobs would be useful if you were jailbroken on iOS 12 and you wanted to upgrade to iOS 13.5 which isn't signed anymore so you can jailbreak on that version instead.
