### ISSUE TITLE
can not save beta blobs

### ISSUE THREAD

**Issue by nssiwi** [airsquared/blobsaver#143]
YOUR ISSUE WILL BE CLOSED AND/OR DELETED IF YOU DO NOT FILL OUT THIS TEMPLATE

Remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
i saw this error in debug log:
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

**Desktop (please complete the following information):**
 - App version [e.g. 1.1.1]

**Log(s)**
```
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
```

what does this error mean?

**Comment by airsquared** [comment]
That means your device doesn't support that version, use a version that your device supports.

**Comment by airsquared** [comment]
If you have any more questions, please create a new issue
