### ISSUE TITLE
"Check Internet connection" error is STILL a false-call EDIT: or maybe not, idk

### ISSUE THREAD

**Issue by HilbertIdeals5** [airsquared/blobsaver#145]
**Description**
When I ran the program, I expected a blob to be created (kind of obvious). Prior to this I tried using the drop-down boxes under "Identifier," using "iPhone" and "iPhone 5 (GSM)"...and nothing happened. I had to force-close the entire program in the Task Manager. When I tried running it with text input for the identifier, I got this error and figured that must be why my previous attempt was stalling. I checked on GitHub for someone with a relevant issue and found exactly what I was looking for. I tried disabling my firewall, my antivirus, and both of them at the same time, but the problem still wasn't getting fixed.

**Screenshot**
![thisiswhatididandwhathappened](https://user-images.githubusercontent.com/63978875/79699331-f9eecb80-825c-11ea-8584-82a7e2987a6f.PNG)

**Desktop**
 - OS: Windows 10 Home
 - App version 2.5.0

**Log**
```
https://api.ipsw.me/v4/device/
```
This is the only thing that was on the clipboard after the operation failed. I assumed the log was a webpage, but when I tried to access it in my browser, it showed a 404 error.

Hope this issue finally gets resolved for good! Thanks.

**Comment by HilbertIdeals5** [comment]
I've just done a quick test to see why the error message popped up. Apparently, it only happens when I enter the product identifier manually. When I enter it from the drop-down boxes, it works fine. I've also discovered that you have to use the actual iOS version number, not the build ID, in the version box (where it says 10B350 in the picture). It produced a blob successfully when I entered 10.3.3 there. However, when I enter 6.1.4, it brings up this error:

![thisiswhatididandwhathappened](https://user-images.githubusercontent.com/63978875/79798079-6d104480-8326-11ea-91ae-21c5c52fa6eb.PNG)

Is this a bug? If it isn't, and a blob actually can't be produced using an unsigned version of iOS, then please tell me. Hope I get an answer soon! Thanks again.

**Comment by HilbertIdeals5** [comment]
Oh wait! Just realized, the log says this:
```
Version: 0ab4c4452a5a6a4f48ab7039560456051348b657 - 1
libfragmentzip version: 0.1-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "3B63B1ADDF4" to dec:4081210547700 hex:3b63b1addf4
[TSSC] opening C:\Users\VM Collection\AppData\Local\Temp\BuildManifest3276814684106275065.plist
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

```
Just from what this log says, I'm assuming it actually is an error. However, I'm brand-new at this iPhone-flashing stuff, so I'll wait to see a response.

**Comment by HilbertIdeals5** [comment]
![thisiswhatididandwhathappened](https://user-images.githubusercontent.com/63978875/79798965-bf059a00-8327-11ea-9d38-32d789d20b36.PNG)

Just saw this from my attempt with the online TSS Saver, so I'm starting to feel like it actually _is_ and error. I'll still wait for a reply, though. Maybe other fellow noobs could find something out from this too...would that be rude to post?...

Sorry for all those extra comments, by the way!

**Comment by HilbertIdeals5** [comment]
So sorry! But I just checked http://www.iphonehacks.com/2018/02/how-to-restore-unsigned-ios-firmwares.html and I'm _really_ starting to feel like I'm stupid and this whole thread is already answered..."You can save the SHSH blobs for an iOS version only if Apple is still signing the firmware."

Still keeping it open, though! Because I'm not smart and I don't know the rules of the threads.

**Comment by airsquared** [comment]
- There is a problem with blobsaver currently that doesn't allow you to manually specify the identifier, you have to use the drop-down box. (will be fixed in the next release)
- In the version text field, you have to specify it as something like "10.3.3" or "13.4". (you can't put the Build ID)
- Yes, you can only save blobs for signed versions. [According to ipsw.me](https://ipsw.me/iPhone5,1), the only signed versions for the iPhone 5 are 10.3.3 and 10.3.4.

Instead of manually specifying the version each time, why don't you just use the "All Signed Versions" checkbox?

**Comment by HilbertIdeals5** [comment]
Wow! Thank you so much for replying. In response to your question, I would have used the "All Signed Versions" checkbox, but right now the version I want to use, 6.1.4, isn't signed anymore. If it really isn't possible to create blobs for iOS after they are unsigned, then I guess this thread can safely be closed. 

Thanks again, airsquared!

**Comment by airsquared** [comment]
No problem, if you have any more questions please create a new issue
