### ISSUE TITLE
App Does Not Detect Java Installation

### ISSUE THREAD

**Issue by KentaigaIBE** [airsquared/blobsaver#146]
**Description of Bug**
When launching the app, a window appears immediately stating I need to install a JRE. However, I already have an appropriate version of Java installed. I have uninstalled all other versions of Java and am currently using the most recent Java 8 release. I installed Java using the typical offline 64-bit installer.

**Screenshot**
![blobsaver-error](https://user-images.githubusercontent.com/38102853/79812436-eb7cde80-8346-11ea-95c0-5337740fab32.png)

**Desktop**
 - OS: Windows 10 Home Single Language, Version 1909
 - App version: 2.5.0
-  Java version: 1.8.0_251-b08

**Comment by airsquared** [comment]
Did you read the wiki page it links to?

**Comment by airsquared** [comment]
Are you able to run a 64-bit instance of the VM using `java -d64 -version`, and did you install it to a different location than the default?

**Comment by KentaigaIBE** [comment]
I was able to make it work, although I had to manually install the x64 version of the JDK in order to make it work. I'm thinking the normal Java installer just assumed I wanted the x86 JRE for whatever reason even though the download page for the offline installer states it's 64-bit. Odd.

**Comment by airsquared** [comment]
If you have any more questions, please create a new issue
