### ISSUE TITLE
Support for 2020 iPad Pro & iPhone SE

### ISSUE THREAD

**Issue by yur1xpp** [airsquared/blobsaver#149]
**Describe the what you'd like**
Hey could you add the support 2020 iPad Pro & iPhone SE?

**Comment by airsquared** [comment]
Was this issue closed by mistake? I'm adding this in the next version.

**Comment by treyturner** [comment]
> Was this issue closed by mistake? I'm adding this in the next version.

Stoked to hear this, as I'm desperate to save my blobs given the 13.4.1 escape that was released. Thanks for your work!

**Comment by yur1xpp** [comment]
I realized you need the device to be jailbroken to be able to save blobs for A12-13, isn't that the case anymore?

**Comment by airsquared** [comment]
You don't have to be jailbroken, but it is highly recommended because if your apnonce changes and you didn't set a generator beforehand the blobs will be useless.

**Comment by airsquared** [comment]
Please try this:

- [blobsaver-macos.dmg](https://github.com/airsquared/blobsaver/files/4604453/blobsaver-macos.dmg.zip)
- [blobsaver-windows.exe](https://github.com/airsquared/blobsaver/files/4604454/blobsaver-windows.exe.zip)

**Comment by yur1xpp** [comment]
It works well for windows version. I'm guessing there's no built-in feature to verify saved shsh?

**Comment by treyturner** [comment]
I'm now able to get my apnonce, but when I try to save the blobs, the progress bar spins endlessly.

**Comment by airsquared** [comment]
@yur1xpp does it show any errors when saving in a preset?

@treyturner can you provide a log from the debug log?

**Comment by yur1xpp** [comment]
Unfortunately there’s nothing, it’s as though as nothing happens. When all the necessary boxes are filled in, when I click save it ask for the new name, filled it in and the name still stays as ‘Preset 5’ and similar. After clicked the ‘Preset 5’, the boxes doesn’t load the info. Let’s say I have a ‘preset 4’ with some ECID, loaded and the boxes filled with correct info, then when I clicked preset 5, the ECID of preset 4 stays there. Perhaps because after upgrade bug?

**Comment by airsquared** [comment]
Do presets still work for other devices?

**Comment by yur1xpp** [comment]
Yeah, those presets that were set using the previous version (2.5.0) still works.

**Comment by treyturner** [comment]
> @treyturner can you provide a log from the debug log?

Actually, I just tried again (a third time) with the debug log open, and this time it worked 🤷 It's possible I've rebooted since my first two attempts. Sorry I can't provide more detail about the failures.

**Comment by airsquared** [comment]
@yur1xpp try resetting the presets using the "Uninstall..." menu item in the options menu

@treyturner so is everything working now?

**Comment by yur1xpp** [comment]
@airsquared yeah clean uninstalled all, still doesn't work. I can't save my device presets at all now.

**Comment by treyturner** [comment]
> @treyturner so is everything working now?

It did, but I'm trying again now after refreshing my apnonce since I just got warning 13.5 is about to drop, and now I'm having the same problem. It hangs for a while at extracting manifest, then I get 'Invalid memory access'. This is the best I can do since the app locks up in this state

![image](https://user-images.githubusercontent.com/1878152/82246587-9793f400-990a-11ea-944a-3470e6c0a96e.png)

**Comment by yur1xpp** [comment]
@airsquared is there any update on the issue I'm facing? Since 13.5 jb is imminent, blobsaver would comes in handy.

**Comment by airsquared** [comment]
Sorry, but I've been really busy recently so I haven't had much time to work on it

**Comment by steipete** [comment]
Can confirm, the beta version works with iPad Pro 4 (iPad8,9). Thank you!

**Comment by airsquared** [comment]
Since it seems to be working for most users, I've released v2.5.1 with this.

@yur1xpp and @treyturner please create a new issue if you still have those problems
