### ISSUE TITLE
"blobsaver.app" can't be opened because the identity of the developer cannot be confirmed"

### ISSUE THREAD

**Issue by jebediah2** [airsquared/blobsaver#158]
Mojave 10.14.6

Had Blobsaver 2.4.0 installed no problem.
Today updated to 2.5.0 but error in title. Dialog does not offer to Open and System Preferences do not offer to "Open Anyway". Basically impossible to open the app as is.

I have to drag and drop the binary file from inside the app/MacOS folder into a Terminal window to launch it.

**Comment by airsquared** [comment]
Right click on the app and press "Open"

**Comment by jebediah2** [comment]
Thanks, and sorry, I had never seen this before and googling it didn't lead to any result.
