### ISSUE TITLE
manual apnonce cant save blobs

### ISSUE THREAD

**Issue by nanerasingh** [airsquared/blobsaver#16]
ios 12, iphone max china cant save manual apnonce, windows10

[TSSC] manually specified apnonce to use, parsed "15400076bc4c35a7c8caefdcae5bda69c140a11bce870548f0862aac28c194cc" to hex:15400076bc4c35a7c8caefdcae5bda69c140a11bce870548f0862aac28c194cc

[TSSC] opening firmware.json

[JSON] counting elements

[JSON] parsing elements

[TSSC] selecting latest iOS: 12.0.1

[TSSC] got firmwareurl for iOS 12.0.1 build 16A405

[TSSC] opening Buildmanifest for iPhone11,6_12.0.1_16A405

[Error] [TSSR] parsed APNoncelen != requiredAPNoncelen (32 != 20)

[Error] [TSSR] failed to populate tss request

[Error] [TSSR] faild to build tssrequest

[Error] [TSSC] checking tss status failed!

**Comment by nanerasingh** [comment]
ios 12, iphone max china

**Comment by airsquared** [comment]
You didn't fill in the information that was in the issue template. Could you please fill that in before reporting bug reports?

**Comment by airsquared** [comment]
@nanerasingh What OS are you on? Are you using the `.jar`?Where did you get the apnonce from?

**Comment by airsquared** [comment]
I'm closing this because OP hasn't responded.
