### ISSUE TITLE
Error when using "Read from connected device" button

### ISSUE THREAD

**Issue by LiquidDeath911** [airsquared/blobsaver#161]
**Describe the bug**
When using the "Read from connected device" button, the following popup appears:

**Screenshots**
![blobsaver error](https://user-images.githubusercontent.com/35089748/82717774-04d5bb00-9c64-11ea-8179-ae54784d243f.JPG)

**Desktop:**
 - iOS 12.2
 - iPhone XS MAX

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
I'm not sure if this might fix it, but try running blobsaver as administrator

**Comment by airsquared** [comment]
This issue occurs if you explicitly click on "do not trust this computer" when prompted. To fix this, you have to reconnect your device and open iTunes then trust your computer.
