### ISSUE TITLE
Issue while saving ipad pro 13.5 blobs. but it worked the next time

### ISSUE THREAD

**Issue by Crafty-The-Fox** [airsquared/blobsaver#164]
**Describe the bug**
blobs were supposed to save correctly, even though the program said they did it came up with an error.

**Screenshots**

**Desktop:**
 - OS Version: Win 10
 - iOS Device: iPad pro 10.5 inch WIfi 2017 A10X

**Checklist (place an x between the brackets to mark as completed):**
 - [x ] I have made sure I am on the latest version of blobsaver
 - [ x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [ x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
problem with libfragmentzip download: code=458
```

**Comment by airsquared** [comment]
Are you able to visit [ipsw.me](https://ipsw.me) in your browser and download the the ipsws for iOS 13.5 and 13.5.1?

**Comment by Crafty-The-Fox** [comment]
i am

**Comment by airsquared** [comment]
What do you mean by "but it worked the next time" in your title? Are you able to reproduce this error consistently?

**Comment by Crafty-The-Fox** [comment]
Yes.

**Comment by airsquared** [comment]
Please try running it again with the debug log open and send me the contents of that log

**Comment by Crafty-The-Fox** [comment]
im so sorry for being  so late, but i will try to do that. i completely forgot.
