### ISSUE TITLE
blobsaver asks "input monitoring permission" which eventually it doesn't use

### ISSUE THREAD

**Issue by ink-splatters** [airsquared/blobsaver#165]
Hello,

thanks a lot for the application, it helped a lot and is much cleaner opposite to messy way using https://tsssaver.1conan.com and libimobiledevice  which needs to be rebuilt from sources (with all the deps), as brew version of libplist's API is not up to date.

Though I was able to save blobs like a charm for both iPhone 11 Pro Max and iPadAir 3, I was really confused by "Input Monitoring" permission (Mac OS). Basically it means access to keyboard which is kind of scary... Why do you need it? What's the intention of this permission? Also important note: despite not giving the permission I was able to successfully get the blobs. So it seems to be not mandatory for anything. There's a link with a screenshot.

https://ibb.co/vDdJQCb

Best regards,
Peter

**Comment by airsquared** [comment]
blobsaver does not need/use this permission; it is actually a bug in Java itself. You can safely deny the permission.

If you update your Java to the latest version of Java 8 it should be fixed.

**Comment by ink-splatters** [comment]
Thanks a lot!
