### ISSUE TITLE
Sent to recovery mode

### ISSUE THREAD

**Issue by hhxhhxhhx** [airsquared/blobsaver#166]
**Describe the bug**
Selecting "Read Apnonce from device" sends device to recovery mode. 

**Screenshots**

**Desktop:**
 - OS Version: Ubuntu 20.04
 - iOS Device: iPhone 11

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
blobsaver is supposed to put your device in recovery mode to read the apnonce, then reboot your device out of recovery mode.

**Comment by hhxhhxhhx** [comment]
was not able to reboot out of recovery mode, tried it about 5 times. was able to use itunes to “update” to 13.5 and get out of it.

**Comment by airsquared** [comment]
This is most likely a hardware problem. What cable are you using to connect your iOS device to your computer, do you have any adapters/USB hubs or other accessories that you are using, and what is the exact port on your computer that you are using?

**Comment by hhxhhxhhx** [comment]
used the cord that apple gave me with the phone. Connected my phone directly into my computer without any accessories.

**Comment by airsquared** [comment]
What is the exact port on your computer you are using? (is it a USB-C? a USB 3.0? a USB 2.0?)

**Comment by hhxhhxhhx** [comment]
usb 3.0

**Comment by airsquared** [comment]
Some users reported problems with USB 3.0 ports, so try using a USB 2.0 port instead.
