### ISSUE TITLE
Request: No mandatory apnounce for A12+ devices in blobsaver

### ISSUE THREAD

**Issue by timidhermit** [airsquared/blobsaver#167]
From previous posts you made, I understand that a device-specific apnonce for A12 or newer devices is needed for the current SHSH2 blobs to be valid. However, you also said that the apnonce is changed whenever the device firmware is updated or restored (possibly), so that the apnonce still needs to be updated each time, which is a pain to do if there are a large number of devices.

With this said, if the device is already jailbroken, you said that the apnonce can be set to use a "default" value before restoring to a firmware. This trick was done for older gen devices. Thus, in this case, an option for blobsaver to follow the same to use a "default" apnonce for A12 or newer devices is still useful.

Right now, there is no option to do so, as the program makes it mandatory to enter an apnonce value for newer gen devices. Can you add a check option to enable manual apnonce so that if this is not checked then the program can still allow saving of apnonce of A12 or newer devices by defaulting to a standard apnonce (not sure the exact value that was frequently used in the past, but I think it may be 0x1111111111111111) that is used in older devices)?

**Comment by airsquared** [comment]
On A12 devices and newer, there is no such thing as a "default" apnonce. Previously on <A12 devices a generator will always generate the same apnonce, which allowed for a default generator/apnonce which will always be the same.

On A12+ devices the apnonce generated by a device is unique to the device and it's impossible to have a default apnonce.

**Comment by TipzTeam** [comment]
@airsquared close or no?

**Comment by airsquared** [comment]
Yes, closing because there's no valid use case for the request.
