### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by HcNguyen111** [airsquared/blobsaver#169]
Where does blobsaver store it's config/preferences? (OS: macOS 10.14.6 (Mojave))

It now crashes on launch for me after briefly "flashing" the ui and at one point used to work fine.(Sorry, I gave up on it a while back and am now reinvestigating as v2.5.1 was released). I ask as I'd like to try "clearing" my previously saved settings to see if that does anything.

This is not (yet) a bug report, though it may lead to one.

**Comment by airsquared** [comment]
Please see #170. (I made a silly mistake in v2.5.1)

For future reference, blobsaver's preferences are stored in `~/Library/Preferences/` in the files `airsquared.blobsaver.prefs.plist` and the preset-specific information is in `airsquared.blobsaver.preset[number].plist`

**Comment by HcNguyen111** [comment]
I've been able to locate the plists, and tried changing some of the background settings to see if it would resolve my launching issues. Sadly it hasn't. I even tried deleted them (moving them out) completely, which also didn't help.

blobsaver just briefly flashes open, then "closes" itself. NOTE: the process is seen to still be running by `ps -ax | grep -i blobsaver` in Terminal (macOS' command line utility).

Is there any _super-early_ logging which can help me (us) debug this?

(Should this now be reported as an Issue, or not yet?)

Thanks for v2.5.2.

**Comment by airsquared** [comment]
If you run the blobsaver executable directly from the terminal it should print more output:

```
$ /Applications/blobsaver.app/Contents/MacOS/JavaAppLauncher
path = /Applications/blobsaver.app/Contents/Frameworks
in tray
there are some presets to save
attempting to save for preset 1
...
```

**Comment by airsquared** [comment]
I did some digging and it seems that if you start blobsaver in the background with no presets enabled to save, it'll crash the UI.

A temporary fix:
Using a plist editor, open `~/Library/Preferences/airsquared.blobsaver.prefs.plist` and change the value "Start background immediately" from true to false then restart your computer. You have to restart your computer after editing the preferences because of how macOS caches preferences and the caches might not get updated.

**Comment by HcNguyen111** [comment]
> A temporary fix:
> Using a plist editor, open `~/Library/Preferences/airsquared.blobsaver.prefs.plist` and change the value "Start background immediately" from true to false then restart your computer. You have to restart your computer after editing the preferences because of how macOS caches preferences so the caches might not get updated.

Success, a reboot did it. That's the exact .plist manual change I tried as well as it looked like it was "hiding/minimising" itself, I should have thought of doing the classic "have you turned it off and on again" as well. (Not that it should affect me again, but I look forward to see how the fix is implemented in an upcoming release (code-wise).)

**Comment by airsquared** [comment]
I'll probably add a check for when all presets are disabled to also disable the background mode.
