### ISSUE TITLE
Save Preset does not work

### ISSUE THREAD

**Issue by nPong** [airsquared/blobsaver#170]
**Describe the bug**
After successfully saving my SSH Blobs for my iPhone 11 Pro Max, I attempted to Save the Preset, I renamed it  "11 Pro Max" (tried with and without spaces) and when I hit OK it was still named "Load Preset 1".  I thought maybe it saved the information but wouldn't change the name, so I closed blobsaver and reopened it.  When I reopened, I clicked Load Preset 1 and nothing happened.

**Screenshots**
none

**Desktop:**
 - OS Version: 10.15.5
 - iOS Device: 13.5

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
none

**Comment by PorridgePi** [comment]
Same problem. Saving Preset does nothing at all.

Desktop OS Version: Windows 10 2004
iOS Device: iOS 13.5
Latest version of blobsaver v2.5.1

**Comment by airsquared** [comment]
I just found the issue, I forgot two `!` in the code. :(

v2.5.2 will fix this.
