### ISSUE TITLE
No place to input board config and tsschecker stopped working error

### ISSUE THREAD

**Issue by xxHoBoZxx** [airsquared/blobsaver#175]

**Comment by airsquared** [comment]
You can upload a screenshot using the bar at the bottom of of the edit box in the issue:
![screenshot](https://user-images.githubusercontent.com/36649395/83826359-91cf3a00-a690-11ea-8e98-ed4b0cded2a8.png)
Please also provide a log, it should be copied to your clipboard.

**Comment by xxHoBoZxx** [comment]
Had to use a different web browser to upload the screenshots. I will try and get the logs.

**Comment by xxHoBoZxx** [comment]
Nevermind. I deleted my report. I will wait on an update and try again then. Sorry for the trouble.
