### ISSUE TITLE
Stuck at Saving Blobs dialog box

### ISSUE THREAD

**Issue by Invisible40** [airsquared/blobsaver#183]
**Describe the bug**
I try saving a blob for the 14.0 beta 1 (with a saved for my iPhone 8 GSM), and it's stuck at the Saving blobs dialog box. When I try to exit out, nothing happens.  I have to end the Java task with Task Manager.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [ ] I have made sure I am on the latest version of blobsaver (Check for Updates button does nothing)
 - [X] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```
Debug Log is empty.

**Comment by airsquared** [comment]
iOS 14 developer beta 1 is restricted to the public; you need a paid developer account to download or save blobs for it.

**Comment by Invisible40** [comment]
Oh that makes a lot of sense, thank you. I'll mark it as closed, since I was using a free developer account.
