### ISSUE TITLE
Not working with Apple TV 4K

### ISSUE THREAD

**Issue by nyuszika7h** [airsquared/blobsaver#185]
**Describe the bug**
When I try to save blobs for the Apple TV 4K, it doesn't work whether I specify all signed versions or a specific version. (I'm aware that they're currently essentially useless, but tsschecker is able to save OTA blobs for the ATV4K.)

**Screenshots**

With "all signed versions":
![image](https://user-images.githubusercontent.com/482367/87045202-e584f400-c1f7-11ea-8d0a-aaadfa07248c.png)
![image](https://user-images.githubusercontent.com/482367/87045085-bec6bd80-c1f7-11ea-95e4-6b957cab0a25.png)

With 13.4.6 specified:

![image](https://user-images.githubusercontent.com/482367/87049913-d143f580-c1fd-11ea-85b0-fe0084c8f82f.png)
![image](https://user-images.githubusercontent.com/482367/87049627-84f8b580-c1fd-11ea-9eb4-98502c5a84e1.png)

In the latter case, the progress bar keeps moving forever and I have to kill blobsaver from the task manager.

**Desktop:**
 - OS Version: Windows 10 2004

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
Won't let me switch to that window to copy, but see screenshots above.

**Comment by airsquared** [comment]
Unfortunately it seems that Apple has pulled all IPSW downloads for the Apple TV 4K so there is no way to save blobs for it.

**Comment by nyuszika7h** [comment]
They may have never existed, but tsschecker can still save blobs from the
OTAs. There's no way to use them right now so maybe a warning about that
could be added, but they're not impossible to save.

**Comment by airsquared** [comment]
Due to the way that blobsaver is written, there's currently no support for saving OTA blobs. If OTA blobs become usable I may consider adding support.

If necessary, you can always manually use tsschecker to save OTA blobs.
