### ISSUE TITLE
recover blobsaver configuration

### ISSUE THREAD

**Issue by BartmanEH** [airsquared/blobsaver#193]
I'm using a new Mac and have Time Machine backups from old Mac. What file can I restore from Time Machine to recover the old configuration for blobsaver? I had presets for my devices nicely setup.

**Comment by airsquared** [comment]
blobsaver's preferences are stored in ~/Library/Preferences/ in the files `airsquared.blobsaver.prefs.plist` and the preset-specific information is in `airsquared.blobsaver.preset[number].plist`

**Comment by BartmanEH** [comment]
Thank you

**Comment by BartmanEH** [comment]
it mostly worked... none of the preset labels "imported" after copying over all the Preference files. also, pretty sure I had a Apnonce set in iPad Pro preset but it doesn't show up after copy Pref files. Oh well, I got close enough.

**Comment by airsquared** [comment]
After replacing the preference files, you also have to restart your Mac because of preference caching
