### ISSUE TITLE
apnonce A12+

### ISSUE THREAD

**Issue by BartmanEH** [airsquared/blobsaver#195]
I have previously saved blobs. I have reinstalled blobsaver on new mac and it's now asking for apnonce for my device. I must have used/extracted an apnonce for the old mac's blobsaver saved blobs, no? Can I extract the apnonce from old saved blobs and re-use in new blobsaver for new blobs?

**Comment by airsquared** [comment]
The apnonce should be part of the file name in the saved blobs
