### ISSUE TITLE
Failed to fetch blob for iPad7,5

### ISSUE THREAD

**Issue by yur1xpp** [airsquared/blobsaver#2]
It says check the board configuration. Thanks :)

**Comment by airsquared** [comment]
Did you get a log? It should have automatically copied it to your clipboard.

**Comment by yur1xpp** [comment]
Hey, here's the log:

Version: 9ce5e00fdeaba8d7e763a028d32b11937839d2f9 - 268
[TSSC] manually specified ecid to use, parsed "XXXXX" to dec:XXXX
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest iOS: 11.4
[TSSC] got firmwareurl for iOS 11.4 build 15F79
[TSSC] opening Buildmanifest for iPad7,6_11.4_15F79
[Error] [TSSR] cant find boardconfig for device=iPad7,6 please manuall use --boardconfig
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[Error] [TSSR] cant find boardconfig for device=iPad7,6 please manuall use --boardconfig
[Error] [TSSR] Error: could not get id0 for installType=Update
[Error] [TSSR] faild to build tssrequest

[Error] [TSSC] checking tss status failed!

**Comment by airsquared** [comment]
What did you choose in the dropdown menu? When you save blobs for the same device using [tsssaver.1conan.com](https://tsssaver.1conan.com/), does it ask for a board configuration?

**Comment by spockers** [comment]
@yur1xpp You titled your issue "iPad7,5" but your log is about an iPad7,6.

Which is the typo? ;)

**Comment by yur1xpp** [comment]
@airsquared I chose "iPad 6(Wifi)(iPad 7,5)". Nope, it didn't ask for anything, saved successfully using the website. I suspect you keyed incorrectly the model name. Let me check.

@spockers There's no typo here, the selection was "iPad 7,5" from the drop-down, however the log came out with "iPad 7,6".

**Comment by yur1xpp** [comment]
Yep, it it.

https://github.com/airsquared/blobsaver/blob/ecb7d17d5def66ae210c5ec14dd6f9e715795999/src/main/java/blobsaver/Controller.java#L1039

It should be run("iPad7,5");

@airsquared

**Comment by airsquared** [comment]
Thanks for reporting the issue. This will be fixed in v1.1.1.

**Comment by yur1xpp** [comment]
Hey @airsquared latest version (1.1.1) still failed to fetch the blobs. I'm not sure what's wrong this time. Here's the log:

> Version: 9ce5e00fdeaba8d7e763a028d32b11937839d2f9 - 268
[TSSC] manually specified ecid to use, parsed "XXXX" to dec:XXXX hex:XXXX
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest iOS: 11.4
[TSSC] got firmwareurl for iOS 11.4 build 15F79
[TSSC] opening Buildmanifest for iPad7,5_11.4_15F79
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2018/ios/091-77674-20180529-3B09633C-5ABE-11E8-A2ED-F257A3E35D9E/iPad_64bit_TouchID_ASTC_11.4_15F79_Restore.ipsw

[A[J100 [===================================================================================================>]
[A[J005 [====>                                                                                               ]
[A[J014 [=============>                                                                                      ]
[A[J022 [=====================>                                                                              ]
[A[J034 [=================================>                                                                  ]
[A[J038 [=====================================>                                                              ]
[A[J042 [=========================================>                                                          ]
[A[J046 [=============================================>                                                      ]
[A[J054 [=====================================================>                                              ]
[A[J062 [=============================================================>                                      ]
[A[J070 [=====================================================================>                              ]
[A[J078 [=============================================================================>                      ]
[A[J095 [==============================================================================================>     ]
[A[J100 [===================================================================================================>]
[Error] [TSSR] cant find boardconfig for device=iPad7,5 please manuall use --boardconfig
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[Error] [TSSR] cant find boardconfig for device=iPad7,5 please manuall use --boardconfig
[Error] [TSSR] Error: could not get id0 for installType=Update
[Error] [TSSR] faild to build tssrequest

[Error] [TSSC] checking tss status failed!

**Comment by spockers** [comment]
@yur1xpp Does that iPad have more than one SoC supplier? Try getting the board ID from the AppStore app BMSSM (System>Device>Model).

**Comment by yur1xpp** [comment]
@spockers it's J71bAP :)

**Comment by airsquared** [comment]
Try downloading [tsschecker](https://github.com/encounter/tsschecker/releases/latest) and running this command manually from the terminal and tell me if it works:

`path_to_tsschecker -d iPad7,5 -s -e PUT_ECID_HERE --boardconfig J71bAP -l`

**Comment by yur1xpp** [comment]
It saved successfully!
[Here's the snippet](https://imgur.com/a/qHhpzMm)
@airsquared

**Comment by airsquared** [comment]
It seems that tsschecker requires a boardconfig for that device. Weird. I'll have it fixed in the next version.
