### ISSUE TITLE
[Linux] Blobsaver just opens as a window 'sliver'

### ISSUE THREAD

**Issue by aspenluxxxy** [airsquared/blobsaver#200]
**Describe the bug**
Blobsaver just opens as a sliver of a window

**Screenshots**
![image](https://user-images.githubusercontent.com/65794972/93502760-2cbcee80-f8e5-11ea-9581-5c23bec7d53f.png)
![image](https://user-images.githubusercontent.com/65794972/93502852-4c541700-f8e5-11ea-9c37-e66f039eea5f.png)

**Desktop:**
 - OS Version: Arch Linux, using OpenJDK 8
 - Desktop Enviroment: KDE Plasma 5.19.5
 - iOS Device: iPhone 11, iOS 13.5

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
~/Downloads via ☕ v1.8.0 took 7s
❯ ./blobsaver

(java:36220): Gtk-WARNING **: 12:56:01.380: Unable to locate theme engine in module_path: "adwaita",
```

```
❯ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

**Comment by airsquared** [comment]
Try the following command:

    pacman -Q gtk-engines

**Comment by aspenluxxxy** [comment]
It wasn't there.

Installing it didn't fix it.

**Comment by airsquared** [comment]
Does restarting after installation have any effect?

Also, what GTK version do you have installed?

**Comment by aspenluxxxy** [comment]
rebooting after has no effect

GTK-3 is installed.

**Comment by airsquared** [comment]
Does the warning still show up?

**Comment by aspenluxxxy** [comment]
yes

**Comment by airsquared** [comment]
Try:

    pacman -S gnome-themes-extra

**Comment by aspenluxxxy** [comment]
Same issue.

`adwaita-icon-theme` is already installed, and I was using `blobsaver-bin` (the problem happens with or without it)

**Comment by airsquared** [comment]
If you run this in terminal, it should show a small window with a button that prints "Hello!" to the terminal when you click it. (this is to test whether it's a problem with Java/GTK or my code)

    echo 'import javafx.scene.control.Button;public class Hello extends javafx.application.Application{public static void main(String[] args){launch();}public void start(javafx.stage.Stage stage){stage.setTitle("Hello World!");Button b = new Button();b.setText("Hello!");b.setOnAction(e->System.out.println("Hello!"));stage.setScene(new javafx.scene.Scene(b, 300, 50));stage.show();}}' >Hello.java && javac Hello.java && java Hello && rm Hello.java Hello.class

![Screen Shot 2020-09-18 at 10 02 14 PM](https://user-images.githubusercontent.com/36649395/93659499-a1ce1800-f9fa-11ea-998c-4654aba25d46.png)

**Comment by aspenluxxxy** [comment]
![image](https://user-images.githubusercontent.com/65794972/93659797-39d9fa80-fa17-11ea-97a2-6c2c72ae572b.png)

**Comment by airsquared** [comment]
Thanks for helping me try all that, looks like it's my (bad) code.

Just to make sure, if you run blobsaver using `java -jar blobsaver.jar`, the issue still occurs?

**Comment by aspenluxxxy** [comment]
yeah. I tried running `./blobsaver`, `java -jar blobsaver.jar`, `java -jar blobsaver.jar -Djdk.gtk.version=3 -Djdk.gtk.verbose=true`, and `java -jar blobsaver.jar -Djdk.gtk.version=2 -Djdk.gtk.verbose=true`

Also, different issue: the blobsaver.exe on Windows won't detect AdoptOpenJDK, only Oracle Java

**Comment by airsquared** [comment]
Try [this](https://github.com/airsquared/blobsaver/files/5249182/blobsaver-linux.tar.gz) build.

For Windows, that's on purpose as AdoptOpenJDK doesn't include JavaFX or OpenJFX. I haven't tested blobsaver with other OpenJDK distributions that do include JavaFX/OpenJFX, but you can try using [Zulu OpenJDK](https://www.azul.com/downloads/zulu-community/?version=java-8-lts&architecture=x86-64-bit&package=jdk-fx), [Liberica JDK](https://www.bell-sw.com/pages/downloads/#/java-8-lts), or [Amazon Coretto](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html) if you don't want to use Oracle's. Requiring Java installed for blobsaver seems to be causing way more problems than I anticipated, so I'm working on compiling blobsaver to native code that doesn't require a JRE (#154).

**Comment by aspenluxxxy** [comment]
Didn't work, although the _error_ about not checking for updates worked.
![image](https://user-images.githubusercontent.com/65794972/93660579-7eb55f80-fa1e-11ea-9735-0ecfa1cab7df.png)

```
~/Downloads via ☕ v1.8.0
❯ ./blobsaver
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/airsquared/blobsaver/releases/latest
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at com.airsquared.blobsaver.Shared.makeRequest(Shared.java:124)
	at com.airsquared.blobsaver.Shared.access$000(Shared.java:52)
	at com.airsquared.blobsaver.Shared$1$1.call(Shared.java:70)
	at com.airsquared.blobsaver.Shared$1$1.call(Shared.java:65)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javafx.concurrent.Service.lambda$null$6(Service.java:725)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by airsquared** [comment]
Is it possible I can contact you somewhere else, like Discord? I don't think GH issues is the best place to attempt to debug something like this.

**Comment by aspenluxxxy** [comment]
sure, aspen#0042

**Comment by airsquared** [comment]
solved

**Comment by Yggdraszil** [comment]
Having the same problem, do you mind sharing what was the solution for this?
