### ISSUE TITLE
Consider adding a warning about apnonce for A12+

### ISSUE THREAD

**Issue by nyuszika7h** [airsquared/blobsaver#203]
A12/A13 users who are unjailbroken may use the "Read from device" feature for apnonce and think they've successfully saved blobs. However, if the blobs were saved this way while unjailbroken and not using an apnonce that was acquired using a known generator while jailbroken, they will be useless. I have seen many people on r/jailbreak Reddit/Discord think the blobs they saved this way were good.

**Comment by Johnnygam3r** [comment]
So, I have an iPhone 11, will I ever be able to save 13.7 blobs?

**Comment by nyuszika7h** [comment]
It will probably be unsigned by the time it gets a jailbreak, so the only way you can save blobs is probably if you stay on 13.7 and then later dump the onboard blobs using SHSHDump.

**Comment by Johnnygam3r** [comment]
Do you think it's worth updating from 13.5?

**Comment by nyuszika7h** [comment]
If you're on 13.5 you can already jailbreak and save blobs for 13.7, no need to update.

**Comment by Johnnygam3r** [comment]
Whenever I try to save them, it says "Saving blobs failed. Check the board configuration or try again later.

**Comment by JustAnOkapi** [comment]
I get the same error

**Comment by airsquared** [comment]
@Johnnygam3r, @JustAnOkapi please see #199 for the "Saving blobs failed. Check the board configuration or ..." error, I am working on fixing this.

**Comment by airsquared** [comment]
In my own testing (and based on other users), I've found that in most cases the apnonce will stay the same on A12+ devices across reboots without needing to set a generator. If the apnonce does end up changing by chance, the blobs will become useless but I've found that this doesn't happen very often.

I can add some more information in the prompt to clarify that it is up to luck whether the apnonce stays constant until the next restore unless a generator is set.

**Comment by nyuszika7h** [comment]
You may be right, but in practice I doubt it would be likely stay the same for a long time. IIRC even checking for an OTA update causes the apnonce to change, but I'm not sure.

**Comment by ccfman2004** [comment]
They do change.  My iPhone 11 Pro Max's apnonce has changed even though I'm still on 13.3.  How do I use a generator? I set it using unc0ver to 0000001234567890 but blobsaver refuses to accept it.

**Comment by nyuszika7h** [comment]
I recommend just leaving it on the default (0x1111111111111111 - 16 '1's). After that, you should be able to use blobsaver's "read from device" option which will read out the apnonce from your device (which is determined by, but *not* the same thing as the generator).

Before verifying if the apnonce stays the same, make sure to rejailbreak in unc0ver (or your preferred jailbreak) and set the same generator.

Users on an unjailbreakable version who don't have a previous apnonce/generator should use [noncestatistics](https://github.com/tihmstar/noncestatistics) to freeze their nonce and save single-use blobs. Make sure not tho check for updates or update/restore your device (except when it's time to use the blobs, of course) as that will reset the nonce.

**Comment by ccfman2004** [comment]
I left it alone but blobsaver had issues reading it and the iPhone rebooted.

**Comment by fabioganga** [comment]
I have a question related to this.

My device is a A12Z, iPad 8,12 12.9 4th generation.

My shsh2 blobs saved with blobsaver seem to contain no generator at all, despite the fact that I have first read the apnonce from the device.

Have I saved a bunch of useless shsh2 now?

**Comment by airsquared** [comment]
If you set an apnonce, the generator will not be included in the blob file. The generator will be the one that was set when you read the apnonce from your device (usually through a jailbreak). If you didn't set a generator the blobs will be single use and you will just have to hope that the generator/apnonce didn't change when you attempt to restore.
