### ISSUE TITLE
Generator is missing

### ISSUE THREAD

**Issue by billgehts** [airsquared/blobsaver#204]
My A13 device save blobs without generator.

**Comment by airsquared** [comment]
This is intentional because if an apnonce is specified, the generator is not used in the blobs. If you set a generator on your device prior to retrieving the apnonce, you should take note of it somewhere so you can use it when you restore.

**Comment by billgehts** [comment]
for a13 devices it is the combination of apnonce and generator to restore with futurerestore.

**Comment by airsquared** [comment]
Yes, so you have to take note of the generator you set prior to reading the apnonce
