### ISSUE TITLE
tsschecker error in windows 7 64bit

### ISSUE THREAD

**Issue by xxHoBoZxx** [airsquared/blobsaver#205]
**Describe the bug**
When saving blobs I get 2 error messages concerning tsschecker (see screenshots). I have to close the popups, but it saves my blobs and I checked with the blobs with the online checker and they are valid. But Blobsaver will not continue unless I close the popups.

**Screenshots**
![tsschecker error](https://user-images.githubusercontent.com/32913594/93721072-187e2900-fb53-11ea-9900-5c0c8e05e1c4.png)

**Desktop:**
  - OS Version: Windows 7 Pro 64bit
 - iOS Device: iPhone 8 - iOS 13.5

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
Log Name:      Application
Source:        Application Error
Date:          9/20/2020 2:41:09 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      HoBoZ-HP-New
Description:
Faulting application name: tsschecker.exe, version: 0.0.0.0, time stamp: 0x5f645813
Faulting module name: ntdll.dll, version: 6.1.7601.24384, time stamp: 0x5c6e245d
Exception code: 0xc0000005
Fault offset: 0x000000000002a365
Faulting process id: 0xda4
Faulting application start time: 0x01d68f85fc584d48
Faulting application path: C:\Program Files\blobsaver\lib\tsschecker.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 3ada1218-fb79-11ea-8d74-480fcf494b02
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-09-20T19:41:09.000000000Z" />
    <EventRecordID>6318</EventRecordID>
    <Channel>Application</Channel>
    <Computer>HoBoZ-HP-New</Computer>
    <Security />
  </System>
  <EventData>
    <Data>tsschecker.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5f645813</Data>
    <Data>ntdll.dll</Data>
    <Data>6.1.7601.24384</Data>
    <Data>5c6e245d</Data>
    <Data>c0000005</Data>
    <Data>000000000002a365</Data>
    <Data>da4</Data>
    <Data>01d68f85fc584d48</Data>
    <Data>C:\Program Files\blobsaver\lib\tsschecker.exe</Data>
    <Data>C:\Windows\SYSTEM32\ntdll.dll</Data>
    <Data>3ada1218-fb79-11ea-8d74-480fcf494b02</Data>
  </EventData>
</Event>
```

**Comment by airsquared** [comment]
This could be a problem with your system itself, try [this solution](https://answers.microsoft.com/en-us/windows/forum/all/app-crash-with-ntdlldll/9aa59f80-99a1-4f3c-b2f0-7eb72df05b2a).

**Comment by xxHoBoZxx** [comment]
Tried that fix, but no luck. As I said it saves the blobs and they are valid, so I'm not to concerned about this. I just wanted to let you know. I will close this issue
