### ISSUE TITLE
shsh.host support

### ISSUE THREAD

**Issue by IzaacJ** [airsquared/blobsaver#206]
**Describe the what you'd like**
Would be perfect for people that has amassed a bunch of blobs on shsh.host to be able to continue using shsh.host even with your tool, so if the blobs can be automatically uploaded there it would be great.

Related to #224.

**Comment by SmartBoy84** [comment]
It wouldn't be too difficult to add support for SHSH.host. The only complication I can see is obtaining the reCAPTCHA token which the api requires to process the request.

Other than that the API is fairly simple, for example this is the request for saving shsh blobs (it returns the web address where they've been saved):
`https://api.arx8x.net/shsh3/device=[id]&boardconfig=[bconfig]&ecid=[ecid]&selected_firmware=[a signed firmware - default is all]&captcha=[token]&generator=[gen]`

Listing saved blobs by scraping: 
`https://shsh.host/[ecid]`

**Comment by SmartBoy84** [comment]
On top this, you could have a migration option which automatically downloads blobs from shsh.host and uses that to automatically set the apnonce and preferred generator.
If this is the case, I think adding a setup screen could prove useful.

**Comment by SmartBoy84** [comment]
Or you could always do blob verification locally as well...
Just download the appropriate "BuildManifest.plist" from [appldnld.apple.com](http://appldnld.apple.com/), using thimstar's [partialZipBrowser](https://github.com/tihmstar/partialZipBrowser/) to extract the plist without having to download the whole ipsw and then use [img4tool](https://github.com/tihmstar/img4tool) to verify the blob's validity.

**Comment by airsquared** [comment]
Added in v3.1.0

**Comment by mailinglists35** [comment]
broken

"Error encountered while trying to save blobs to SHSH Host:
Remote host terminated the handshake"

**Comment by airsquared** [comment]
@mailinglists35 see discussion: https://github.com/airsquared/blobsaver/discussions/562
