### ISSUE TITLE
Error getting device details

### ISSUE THREAD

**Issue by ccfman2004** [airsquared/blobsaver#207]
**Describe the bug**
BlobSaver 2.5.4 can't get device info on MacOS 10.15.7.

<img width="706" alt="Screen Shot 2020-09-30 at 6 33 05 PM" src="https://user-images.githubusercontent.com/79392/94747012-ff902780-034b-11eb-84d8-65c15bc3f9d1.png">

**Desktop:**
 - OS Version:10.15.7
 - iOS Device: iPad Air 2 12.4.1

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
Is finder able to recognize and sync with your device?

**Comment by ccfman2004** [comment]
Yes

**Comment by ccfman2004** [comment]
Not sure what changed but I had to wipe and reinstall 10.15 as a troubleshooting measure for an unrelated issue. Now I have no issues so go figure.
