### ISSUE TITLE
Native Notifications

### ISSUE THREAD

**Issue by airsquared** [airsquared/blobsaver#21]
The notifications being shown while in background aren't very good for this use case. It would be better to have native notifications using the OS's notification center. 

[JMacNotifcation](https://github.com/airsquared/JMacNotification) can be used for Mac(after the library is finished).

AWT's tray icon/notification system can be used for Windows.

**Comment by PencilNotPen** [comment]
Is this still in development? I'd like to second the request for macOS native notifications if possible, would be amazing. Thanks!

**Comment by airsquared** [comment]
I am currently working on a whole new system for saving blobs in the background, which should fix a lot of bugs and improve performance and will also include optional native notifications.
