### ISSUE TITLE
Error creating Blobs for ATV v4 with requested log dump from clipboard 

### ISSUE THREAD

**Issue by taw123** [airsquared/blobsaver#210]
**Describe the bug**
Error generated when attempting to download blobs for Apple TV gen 4 (NOT 4k).

**Desktop:**
 - OS Version: Mac OS X 10.15.7

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
problem with libfragmentzip download: code=-4
```

**Comment by airsquared** [comment]
Does it still save blobs even though it's showing that error message?
