### ISSUE TITLE
problem with libfragmentzip download: code=458

### ISSUE THREAD

**Issue by idkmanwtt** [airsquared/blobsaver#211]
**Describe the bug**
Connected my iPhone SE 2020 to the PC, opened blobsaver, pasted the ECID, clicked on Read from device for the apnonce, entered recovery mode and exited with no problems, and then clicked Go, without disconnecting the device. It took around 2 minutes for the blobs to save, and they saved successfully, but after I exited out of the success window, another window popped up telling me that something went wrong, and to open a Bug Report here. I can't get the window to reappear again

**Screenshots**

**Desktop:**
 - OS Version: Windows 10
 - iOS Device: iPhone 12,8

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
problem with libfragmentzip download: code=458
```

**Comment by airsquared** [comment]
Thanks for the bug report, but since you aren't able to get the error message again, then it may have just been a one time issue.
