### ISSUE TITLE
iPhone 12 series not available as models

### ISSUE THREAD

**Issue by raman325** [airsquared/blobsaver#214]
**Describe the bug**
I downloaded the latest version of blobsaver (v2.5.4) and the iPhone 12 series is missing from the list. I was able to select iPhone 11 Pro and eventually request that the blobs be saved, but not clear on if they are accurate because my device model (iPhone 12 Pro) is unlisted.

**Screenshots**

**Desktop:**
 - OS Version: 10.15.6
 - iOS Device: 14.1

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by gregmichael** [comment]
I can confirm no iPhone 12 models in mac binary. This needs to be added, hopefully soon.

**Comment by StrangeOne101** [comment]
This also appears to affect the windows binary. iPhone 12 models do not appear.

**Comment by ThinkSalat** [comment]
Same here. Just downloaded and it's not listing any of the new generation of iphone.

**Comment by airsquared** [comment]
The devices are just not in the device list, but the saved blobs will be correct and perfectly usable if you enter the identifier manually.

I'll add the iPhone 12 models to the device list in the next update.

**Comment by dopplebockk** [comment]
Upgrade from an XS (blobsaver worked perfect, thank you) to a 12 Mini. I was able to successfully "read from device" to fill in my ECID, internal name/board config and manually specified the apnonce. As per [Apple](https://support.apple.com/en-us/HT201296), my "Identifier" is A2176, correct? The app is refusing to allow me to save this as a preset, keeping that field highlighted in red.

**Comment by airsquared** [comment]
"A2176" is a model number, the identifier for the 12 Mini is "iPhone13,1".

**Comment by airsquared** [comment]
The iPhone 12 models have now been added in v2.5.5.
