### ISSUE TITLE
Infinite "saving blobs" help

### ISSUE THREAD

**Issue by letsdosomesave** [airsquared/blobsaver#216]
YOUR ISSUE WILL BE CLOSED AND/OR DELETED IF YOU DO NOT FILL OUT THIS TEMPLATE

Please remove the following line and the text above it before submitting this issue:
Infinite "saving blobs" loading please help
-------------------------------------------------------------

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [ x] I have made sure I am on the latest version of blobsaver
 - [x ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x
![Screenshot 2020-11-12 090223](https://user-images.githubusercontent.com/74372264/98972716-a62d2380-24c7-11eb-889b-b3c1f944c2a8.jpg)
] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
@letsdosomesave please fill out the template (the OS version, your iOS device, the bug description)
