### ISSUE TITLE
Windows Security block the installer to download

### ISSUE THREAD

**Issue by Ricky842484** [airsquared/blobsaver#22]
**Describe the bug**
I download the version 2.2.1 update. But when it is downloaded, I recived a notification about the program is blocked by Windows Security. I know that we can turn off that feature, but I want to ask use on trying to fix it.

**Screenshots**
Nope! (You know that if you jave Windows 10 installed)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 19H1 Build 18290 (Updating to Build 18305)
 - App version: 2.2.1
 - [No!] Using .jar?

**Crash log**
Nope (It won't have a crash log!)

**Comment by Ricky842484** [comment]
jave = have in Line 7

(I type fast but sometimes I will type some wrong letter.)

**Comment by Ricky842484** [comment]
use = you in Line 3

(Again)

**Comment by airsquared** [comment]
Thanks for the issue. It shows this warning because the app is not signed (and if I remember correctly, you need a paid Microsoft developer account to do this). I currently do not have a developer account so I can't sign it.
