### ISSUE TITLE
Blobsaver - Following not working: Saving blobs for mutliple preset devices automatically, Background frequency check not working

### ISSUE THREAD

**Issue by EdgeXS** [airsquared/blobsaver#220]
**Describe the bug**
Blobsaver not saving multiple preset blobs and frequency setting not working.

**Screenshots**
<no screen shots>

**Desktop:**
 - OS Version: macos 10.15.5, macOS 10.14.6
 - iOS Device: 12.4, 13.5, 9.0.2 (iphone6, iPhone X, ipad2)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
Debug log is blank
If applicable, paste any log(s) here, on the lines between the backticks.

Hey great work on the blobsaver app.  I was trying to figure out a way to automatically periodically save my blobs as IOS gets updated for each devices.  Long time user and learned that blobsaver has the automatically save blobs option. However, it doesn't seem to work as expected.

Things that work and DOESN'T work.  Maybe it's a user error or a bug unsure

Saving single blob - WORKS
My steps:
1. insert device > read from device (do additional steps for trust relationship) > click go
2. blob saving process goes > result is > blob saved
3. click save
4. save in one of the presets
5. add a name > done

Enabling background process for single preset - Works (for testing)
1. click background settings
2. change frequency > 1 minute (for testing)
3. restart app.
4. It states "check your system tray/status bar for the icon, •presetname 1•
5. blob for that preset is created upon startup.

Multiple blobs saves - **DOES NOT WORK**
When multiple presets are setup. Open the app.
1. click background settings
2. presets are listed as "Cancel Name1", "Cancel Name2"
3. quit blobsaver and then open it
4.  Notification states that "Check your system tray/status bar for the icon. •name of preset1•,•name of preset2•
5. Checked the directory where it is saved. It saved the first preset but not the second preset.

**expectation**: That as the status banner states that both presets have been saved.  All blobs are saved in the directory.

**Actual**: only the first preset blobs is saved.

background support & Frequency of Blob saved. - **DOES NOT WORK**
1. Setting the frequency to be every 1 minute (for testing purposes)

**expectation**: 
1.  if blob **exist** for iOS and device - don't overwrite existing blob.
2.  if the blob **doesn't exist**, a blob is created for all the presets based on the desired frequency,
3.  when background setting is enabled - do one of the above.

**Actual**:
1. Can't test because frequency of blob doesn't work.
2. & 3 If I delete the existing blob and wait for at least 2 minutes a new blob isn't saved.

Blob saver icon is in the menulet status bar. Do hope it's a user error not an application bug.  

any help would be appreciated

**Comment by airsquared** [comment]
Thanks for the bug report, it does seem like a problem in blobsaver itself.

I'm currently rewriting the entire saving blobs in the background feature, to fix this and other issues (it will also be a lot faster and use much less resources).

**Comment by EdgeXS** [comment]
Glad to help and looking forward to the update. If you need to help test this feature do not hesitate to reach out. If this bug could be closed when it’s resolved would much appreciate the heads up so I can download the official fixed version.

**Comment by EdgeXS** [comment]
LIVE AGAIN STALE BoT

**Comment by JamesBedwell** [comment]
@airsquared hi, any progress on this background saving update? I'm encountering the same issue. Background saving has never worked for me, and I've had blobsaver installed for a *very* long time and across multiple macOS updates. Reinstalling blobsaver also doesn't fix it.
Currently on macOS 10.15.7 Catalina

Looking forward to your reply, thanks!

**Comment by airsquared** [comment]
I've just completed the fix in #238, I'll have a beta release of it ready soon.

**Comment by JamesBedwell** [comment]
> I've just completed the fix in #238, I'll have a beta release of it ready soon.

Awesome! Thanks 🙂 
Will it be made available via the releases in this repo or should I watch somewhere else?
