### ISSUE TITLE
Cannot remove apnonce inherited from preset with apnonce

### ISSUE THREAD

**Issue by bs286692** [airsquared/blobsaver#221]
**Describe the bug**
I cannot remove the apnonce which was previously set for a preset. In my case, I set up a preset with an apnonce for an iPhone XS Max. Now, I am trying to assign that preset to another device which does not have an apnonce, i.e. an iPhone 7 Plus. But the apnonce cannot be removed, even after unchecking the apnonce and saving the preset again.

**Desktop:**
 - OS Version: Windows 10 64-bit

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
Please try the beta in #242.
