### ISSUE TITLE
Blobsaver should save blobs to a temporary file first, then rename

### ISSUE THREAD

**Issue by bs286692** [airsquared/blobsaver#222]
**Describe the bug**
Currently, blobsaver saves blobs directly to the ultimate destination file. This is not safe in case the saving process fails because of the potential to overwrite a previously valid blob with one which is not valid. blobsaver should first save to a safely-named temporary file, then rename.

**Desktop:**
 - OS Version: Windows 10 64-bit

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
I don't think that tsschecker (which is what blobsaver uses) overwrites blob files unless it actually saved successfully.
