### ISSUE TITLE
Create an option to facilitate remote saving at tsssaver.1conan.com

### ISSUE THREAD

**Issue by bs286692** [airsquared/blobsaver#224]
**Describe the what you'd like**
Create an option to use appropriate APIs to facilitate remote saving at tsssaver.1conan.com.

Related to #206.

**Comment by nyuszika7h** [comment]
This is pretty much a duplicate of #206.

**Comment by airsquared** [comment]
Oh yeah it is a duplicate, seems I missed that. I'll edit this issue to make it just for tsssaver.1conan.com since the other one is for shsh.host.

**Comment by airsquared** [comment]
Added in v3.1.0
