### ISSUE TITLE
Add support for the new iPad models

### ISSUE THREAD

**Issue by jordyvandorp** [airsquared/blobsaver#227]
Currently the tool doesn't support the new iPad models. the models missing are the iPad 8th generation (wifi and cellular) and the iPad Air 4th gen (wifi and cellular)

Both use the A14 chipset

**Comment by airsquared** [comment]
These devices will be added in the next version. Are you able to manually specify the identifier of those devices?

**Comment by airsquared** [comment]
Please try the beta in #242.

**Comment by airsquared** [comment]
Added in v3.0.
