### ISSUE TITLE
irecovery error: code= -3

### ISSUE THREAD

**Issue by Bungalow11433** [airsquared/blobsaver#233]
**Describe the bug**
When pressing read from device for Apnonce my iPhone 11 pro goes into recovery mode and then I get the error code=-3.
Tried on two different Macbooks but I get the same error code. 
 
I have no issues reading the ECID from the device only the Apnonce. My device is jailbroken with Unc0ver on 13.3. I have set my generator to 0x1111111111111111.

**Screenshots**
<img width="381" alt="Skärmavbild 2021-02-17 kl  11 01 49" src="https://user-images.githubusercontent.com/79198394/108195455-13300500-7118-11eb-8343-00092c370e55.png">

**Desktop:**
 - OS Version: MacOS Big Sur 11.2.1
 - iOS Device: Iphone 11 Pro iOS 13.3

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by zaptrem** [comment]
Also running into this.

**Comment by airsquared** [comment]
Try with the v3.0 beta at #242 and see if the error still occurs.

**Comment by DiddyVB** [comment]
I am having this same error running 3.0.1 on an iPhone XR running iOS 13.5 jailbroken with Unc0ver using Windows.

**Comment by airsquared** [comment]
Try different USB cables, different USB ports on your computer, and removing any intermediate devices between your USB cable and computer like USB hubs.
