### ISSUE TITLE
Repeatedly asked to "Trust" on device

### ISSUE THREAD

**Issue by PencilNotPen** [airsquared/blobsaver#234]
**Describe the bug**
Devices which are already trusted in Finder/iTunes/Apple Configurator on my Mac, are asked to be trusted again when added to blobsaver. Is this expected behaviour, and is this trusting somehow different from the basic one-time "Trust" between an iOS device and a given computer? Can blobsaver not use/inherit the existing trust settings between my devices and the computer running blobsaver?

Additionally, I am asked to "Trust" my devices again, each and every time I use the "Read ECID from device" or "Read Apnonce from device" buttons, even when the device has been previously trusted by my computer, AND previously trusted by blobsaver, even when the device is already stored as a preset. Is this also necessary?

Many thanks for blobsaver!

**Desktop:**
 - macOS 11.3 Beta 2:
 - iOS Device: Any, e.g. iPX 13.5, iPXR 14.3, iP7 14.3.

**Comment by airsquared** [comment]
I'll have to look into if libimobiledevice supports saving device pairings. Currently, blobsaver re-pairs the device each time as I wasn't aware of any way to save the device pairings when writing it originally.

**Comment by airsquared** [comment]
With the latest v3.0 beta, it should no longer ask you to repair the device each time.

**Comment by PencilNotPen** [comment]
Thanks, great work!

**Comment by airsquared** [comment]
Added in v3.0.
