### ISSUE TITLE
"JRELoadError" on macOS, despite Java 8 being installed

### ISSUE THREAD

**Issue by aspenluxxxy** [airsquared/blobsaver#235]
YOUR ISSUE WILL BE CLOSED AND/OR DELETED IF YOU DO NOT FILL OUT THIS TEMPLATE

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**

Trying to open blobsaver.app on macOS results in a "JRELoadError", even though manually launching via `java -jar` works.

I am using Amazon Corretto 8.282.08.1 as my Java distribution.

**Screenshots**

Trying to open the app:
![image](https://user-images.githubusercontent.com/65794972/108601219-8a100c80-7369-11eb-97ee-3058245efa90.png)
Directly launching from terminal:
![image](https://user-images.githubusercontent.com/65794972/108601268-c80d3080-7369-11eb-9d41-8efd708a4297.png)

**Desktop:**
 - OS Version: macOS 11.2

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
Where is the JDK installed?

**Comment by aspenluxxxy** [comment]
`/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home`

`java` binary is `/usr/bin/java`.

**Comment by airsquared** [comment]
Please try the beta in #242, it comes bundled with a JRE so you won't need to install one.

**Comment by aspenluxxxy** [comment]
just tried the latest Actions build, it works!
