### ISSUE TITLE
lockdownd error: code=-23

### ISSUE THREAD

**Issue by ihxzey** [airsquared/blobsaver#237]
**Describe the bug**
I simply plugged my iPhone 11 into my Mac, and when I tried reading the Apnonce from my device, I received the error 'lockdownd error: code=-23'

**Screenshots**
<img width="402" alt="Screen Shot 2021-02-25 at 4 55 35 PM" src="https://user-images.githubusercontent.com/39014019/109224743-59c1d700-778a-11eb-809c-6f631015814a.png">
**Desktop:**
 - OS Version: 11.2.1 (20D74)
 - iOS Device: 14.5 beta 2

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
If you're still having this issue, try [here](https://github.com/airsquared/blobsaver/issues/258#issuecomment-844639499). (apologies, it seems I may have missed this issue you created)
