### ISSUE TITLE
Big Sur Icon and .dmg for compression and aesthetics.

### ISSUE THREAD

**Issue by ExeRhythm** [airsquared/blobsaver#251]
**Describe the what you'd like**
A Big Sur styled icon

**Optional screenshot**
Here's my attempt at creating it. It looks bad, I know, it is my second I have ever created.

![AppIcon_1024x1024x32](https://user-images.githubusercontent.com/52459150/112881409-4cbf3d00-90d4-11eb-8efc-48ac8177c23a.png)

And maybe .dmg might be an awesome feature, something like this:
<img width="712" alt="Screen Shot 2021-03-29 at 21 20 15" src="https://user-images.githubusercontent.com/52459150/112881595-8f811500-90d4-11eb-8edc-914129c41874.png">
I don't even know why am I doing all of this, because it looks ugly ngl

**Comment by CoocooFroggy** [comment]
Like I commented in the 3.0 discussion you can do jpackage --icon to set the actual DMG's icon (not app icon if you're making the app image first).

**Comment by EusGoed** [comment]
It would be nice to also change the menu bar icon to align more with the default icon style.

**Comment by airsquared** [comment]
@ExeRhythm I will look into using the icon for v3.0, thank you!

&nbsp;

> It would be nice to also change the menu bar icon to align more with the default icon style.

@EusGoed There is actually going to be a new way for saving blobs automatically for blobsaver in v3.0, which won't even need to run in the background or have a status bar menu.

**Comment by airsquared** [comment]
Would you be able to provide a `.icns` file for the app icon and a `.png` file for the DMG background?

**Comment by ExeRhythm** [comment]
Hi. I sadly deleted them because the issue was not active for a while.

**Comment by airsquared** [comment]
Oh no, sorry I had just been very busy the past couple months so didn't have much time. I was planning on adding these icons right before I released the final version of v3.0, but since you deleted them it's fine then. Thanks for creating them earlier though, you can close this GitHub issue now if you want.
