### ISSUE TITLE
Switch to DanTheMann15's fork of tsschecker

### ISSUE THREAD

**Issue by aspenluxxxy** [airsquared/blobsaver#255]
## Describe the what you'd like
It'd be nice if ths bundled version of tsschecker was switched to https://github.com/DanTheMann15/tsschecker/tree/master - it has several important bugfixes (for example, fixing support for `iPad7,12`, which will error when trying to save blobs with standard tsschecker, **I actually need to switch out the bundled tsschecker with this one in order to successfully save blobs for my Cellular iPad 7**)

for more info on this fork, see the (still unmerged) PR that was made to upstream tsschecker _6 months ago_: https://github.com/tihmstar/tsschecker/pull/165

futurerestore has also switched to this branch of tsschecker (see https://github.com/marijuanARM/futurerestore/pull/2)

**Comment by strikekat** [comment]
Just wanted to say - as someone with zero iOS experience - thanks so much. I was losing my mind trying to figure out why no tool was saving blobs for my iPad 7 and couldn't find anything online about it (and missed 2 firmware signings, sigh).

**Comment by airsquared** [comment]
Thanks, I wasn't aware that tihmstar's tsschecker was missing all of that. I'll replace it in v3.0.

**Comment by aspenluxxxy** [comment]
Note: this fork also has support for the Spring 2021 devices (new iPad Pro and such)

**Comment by airsquared** [comment]
Please try the latest actions build [here](https://github.com/airsquared/blobsaver/actions/runs/867713421), it should fix your issue.

**Comment by airsquared** [comment]
Added in v3.0.
