### ISSUE TITLE
Unable to exit recovery

### ISSUE THREAD

**Issue by booleangit** [airsquared/blobsaver#256]
**Describe the bug**
Tool version: blobsaver 2.6
OS host: Windows 10
OS client: iOS 14.1
Jailbreak: unc0ver 6.1.2

After successfully reading the ApNonce, the device won't exit recovery mode.

In order to exit recovery mode, I had to use 3rd party software called "iMyFone D-Back". After letting it resolve the issue (while leaving it connected), I was able to continue the process and save the blobs.

**Screenshots**

**Desktop:**
 - OS Version: Windows 10
 - iOS Device: iPhone 12 mini

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by sweetw0r** [comment]
Same with iPhone 12 Pro Max / iOS 14.4.2 Apnonce wasn't retrieved. 👀

**Comment by booleangit** [comment]
> Same with iPhone 12 Pro Max / iOS 14.4.2 Apnonce wasn't retrieved. 👀

If you leave your phone connected and blobsaver running, you will be able to manually exit DFU and continue the process.

PS. You have to be jailbroken for it to work.

**Comment by airsquared** [comment]
Does it give an error when it is unable to exit recovery, or does it just silently fail?

**Comment by booleangit** [comment]
It just keeps waiting for the phone to return (which it doesn't because of the DFU loop) indefinitely without an error. When you manually exit DFU (with another tool) the process continues and you're actually able to save the blobs.

**Comment by airsquared** [comment]
I think I've found the problem, please try the latest beta at #242.

**Comment by D3SOX** [comment]
Thank you for mentioning "iMyFone D-Back". I used it in a Windows KVM passing through my iPad, and it was the only software that was able to exit my iPad Air 3 out of recovery mode (Tried libirecovery on my Linux host and Wondershare Dr.Fone and a few other tools in the Windows VM without success)

**Comment by touchmii** [comment]
> iMyFone D-Back

same error

java.lang.UnsatisfiedLinkError: Unable to load library 'irecovery':
dlopen(/Applications/blobsaver.app/Contents/Frameworks/libirecovery.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib
dlopen(/Applications/blobsaver.app/Contents/Frameworks/libirecovery.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib
dlopen(/Users/touchmii/Library/Frameworks/irecovery.framework/irecovery, 9): image not found
dlopen(/Library/Frameworks/irecovery.framework/irecovery, 9): image not found
dlopen(/System/Library/Frameworks/irecovery.framework/irecovery, 9): image not found
Native library (darwin-x86-64/libirecovery.dylib) not found in resource path ()
	at com.sun.jna@5.12.1/com.sun.jna.NativeLibrary.loadLibrary(Unknown Source)
	at com.sun.jna@5.12.1/com.sun.jna.NativeLibrary.getInstance(Unknown Source)
	at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.natives.NativeUtils.register(Unknown Source)
	at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.natives.Libirecovery.<clinit>(Unknown Source)
	at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.LibimobiledeviceUtil.waitForRecovery(Unknown Source)
	at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Applications/blobsaver.app/Contents/Frameworks/libirecovery.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib
		at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
		... 12 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Applications/blobsaver.app/Contents/Frameworks/libirecovery.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib
		at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
		... 12 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/touchmii/Library/Frameworks/irecovery.framework/irecovery, 9): image not found
		at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
		... 12 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/irecovery.framework/irecovery, 9): image not found
		at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
		... 12 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/irecovery.framework/irecovery, 9): image not found
		at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
		... 12 more
	Suppressed: java.io.IOException: Native library (darwin-x86-64/libirecovery.dylib) not found in resource path ()
		at com.sun.jna@5.12.1/com.sun.jna.Native.extractFromResourcePath(Unknown Source)
		... 12 more
	Suppressed: java.lang.UnsatisfiedLinkError: Unable to load library 'irecovery-1.0':
dlopen(libirecovery-1.0.dylib, 9): image not found
dlopen(libirecovery-1.0.dylib, 9): image not found
dlopen(/Users/touchmii/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found
dlopen(/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found
dlopen(/System/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found
Native library (darwin-x86-64/libirecovery-1.0.dylib) not found in resource path ()
		... 12 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libirecovery-1.0.dylib, 9): image not found
			at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
			... 12 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libirecovery-1.0.dylib, 9): image not found
			at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
			... 12 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/touchmii/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found
			at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
			... 12 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found
			at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
			... 12 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found
			at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method)
			... 12 more
		Suppressed: java.io.IOException: Native library (darwin-x86-64/libirecovery-1.0.dylib) not found in resource path ()
			at com.sun.jna@5.12.1/com.sun.jna.Native.extractFromResourcePath(Unknown Source)
			... 12 more

i use imazing exit recover mode.

**Comment by airsquared** [comment]
> > iMyFone D-Back
> 
> same error
> 
> java.lang.UnsatisfiedLinkError: Unable to load library 'irecovery': dlopen(/Applications/blobsaver.app/Contents/Frameworks/libirecovery.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0) Expected in: /usr/lib/libSystem.B.dylib in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib dlopen(/Applications/blobsaver.app/Contents/Frameworks/libirecovery.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0) Expected in: /usr/lib/libSystem.B.dylib in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib dlopen(/Users/touchmii/Library/Frameworks/irecovery.framework/irecovery, 9): image not found dlopen(/Library/Frameworks/irecovery.framework/irecovery, 9): image not found dlopen(/System/Library/Frameworks/irecovery.framework/irecovery, 9): image not found Native library (darwin-x86-64/libirecovery.dylib) not found in resource path () at com.sun.jna@5.12.1/com.sun.jna.NativeLibrary.loadLibrary(Unknown Source) at com.sun.jna@5.12.1/com.sun.jna.NativeLibrary.getInstance(Unknown Source) at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.natives.NativeUtils.register(Unknown Source) at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.natives.Libirecovery.(Unknown Source) at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.LibimobiledeviceUtil.waitForRecovery(Unknown Source) at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source) at airsquared.blobsaver@3.3.0/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source) at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source) Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Applications/blobsaver.app/Contents/Frameworks/libirecovery.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0) Expected in: /usr/lib/libSystem.B.dylib in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Applications/blobsaver.app/Contents/Frameworks/libirecovery.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0) Expected in: /usr/lib/libSystem.B.dylib in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/touchmii/Library/Frameworks/irecovery.framework/irecovery, 9): image not found at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/irecovery.framework/irecovery, 9): image not found at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/irecovery.framework/irecovery, 9): image not found at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.io.IOException: Native library (darwin-x86-64/libirecovery.dylib) not found in resource path () at com.sun.jna@5.12.1/com.sun.jna.Native.extractFromResourcePath(Unknown Source) ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: Unable to load library 'irecovery-1.0': dlopen(libirecovery-1.0.dylib, 9): image not found dlopen(libirecovery-1.0.dylib, 9): image not found dlopen(/Users/touchmii/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found dlopen(/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found dlopen(/System/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found Native library (darwin-x86-64/libirecovery-1.0.dylib) not found in resource path () ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libirecovery-1.0.dylib, 9): image not found at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libirecovery-1.0.dylib, 9): image not found at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/touchmii/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/irecovery-1.0.framework/irecovery-1.0, 9): image not found at com.sun.jna@5.12.1/com.sun.jna.Native.open(Native Method) ... 12 more Suppressed: java.io.IOException: Native library (darwin-x86-64/libirecovery-1.0.dylib) not found in resource path () at com.sun.jna@5.12.1/com.sun.jna.Native.extractFromResourcePath(Unknown Source) ... 12 more
> 
> i use imazing exit recover mode.

See #428, this is a known issue on macOS versions older than Big Sur.
