### ISSUE TITLE
lockdownd error: code=-23

### ISSUE THREAD

**Issue by systwi-again** [airsquared/blobsaver#258]
**Describe the bug**
I connect my iPhone XR (iPhone11,8 running iOS 14.5) into my iMac (iMac19,2 running macOS 10.15.7), run blobsaver and, when clicking the "Read from device" button next to the Apnonce bar, the screenshot below appears.

I saw the same error posted earlier in March with no subsequent activity.

**Screenshots**
<a href="https://ibb.co/Gp0VwQn"><img src="https://i.ibb.co/nmbD2M6/Screen-Shot-2021-05-04-at-6-48-39-PM.png" alt="Screen-Shot-2021-05-04-at-6-48-39-PM" border="0"></a>

**Desktop:**
 - OS Version: macOS Catalina 10.15.7 (19H524)
 - iOS Device: iPhone XR (iPhone11,8)
 - Java Version: Java 8 Update 291 (build 1.8.0_291-b10)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
Entering recovery mode
com.airsquared.blobsaver.Libimobiledevice$LibimobiledeviceException: lockdownd error: code=-23
	at com.airsquared.blobsaver.Libimobiledevice.throwIfNeeded(Libimobiledevice.java:271)
	at com.airsquared.blobsaver.Libimobiledevice.enterRecovery(Libimobiledevice.java:108)
	at com.airsquared.blobsaver.Controller.lambda$readApnonce$18(Controller.java:854)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by TheMissingPort** [comment]
Im having the same issue
OS Version: Big Sur
iOS Device: iPhone 11

**Comment by GrantGus06** [comment]
same issue ;(

**Comment by airsquared** [comment]
Try with the v3.0 beta at #242 and see if the error still occurs.

**Comment by XxBrokenComputerxX** [comment]
Same here on Windows 8.1 Pro, iPhone SE2

> Im having the same issue
> OS Version: Big Sur
> iOS Device: iPhone 11

**Comment by airsquared** [comment]
@XxBrokenComputerxX is this also on v2.5.5 or the v3.0 beta?

**Comment by UnbreakCode** [comment]
Had the same issue with an iphone 11 on windows. Using v3.0 beta sets my iphone into recovery mode and blobsaver got the apnonce.

**Comment by airsquared** [comment]
Just to confirm, you no longer get this issue on the v3.0 beta?

**Comment by XxBrokenComputerxX** [comment]
> Just to confirm, you no longer get this issue on the v3.0 beta?

Yes 3.0 works. Sorry for late reply I haven't been online Yesterday

**Comment by airsquared** [comment]
> Yes 3.0 works. Sorry for late reply I haven't been online Yesterday

Oh no problem, the second time I asked was actually to UnbreakCode since they just commented they had the same issue.

**Comment by UnbreakCode** [comment]
> Just to confirm, you no longer get this issue on the v3.0 beta?

Yes as I said it's working fine in version 3.0

**Comment by airsquared** [comment]
Added in v3.0.

**Comment by systwi-again** [comment]
Sorry for the terribly late reply. Thanks for fixing this!
