### ISSUE TITLE
Saving blobs to folders for easier human navigation

### ISSUE THREAD

**Issue by PencilNotPen** [airsquared/blobsaver#265]
Could an option be introduced to automatically generate folders named after each device, and within each, folders named after each *OS version, which the blobs are saved into? This would make it much easier to locate specific .shsh2 files at a later date, rather than all the blobs being mixed into one folder.

It may already be possible to manually set a different Save Location for each device in the app, but this is labour-intensive when you have many devices, and still doesn't support sub-folders for each *OS version. It would be ideal if you could set one save location such as ~/Documents/Blobs for all devices, and then have blobsaver generate sub-folders within that when saving blobs, such as Device 1, Device 2, etc, and within those folders 14.4, 14.5 etc, each with the .shsh2 file inside.

Many thanks, blobsaver is a great tool!

**Comment by airsquared** [comment]
This could be implemented by allowing variables in the path:

- `{{Device Identifier}}`
- `{{Device Name}}`
- `{{ECID}}`
- `{{Major Version}}`
- `{{Full Version}}`

So in the path field you could enter something like `/Users/airsquared/Blobs/{{Device Identifier}}/{{Major Version}}`

**Comment by airsquared** [comment]
This hasn't been implemented yet; it's just an idea for a future feature.

**Comment by airsquared** [comment]
This has been added in v3.4.0.
