### ISSUE TITLE
No Support iPadPro2021 。。。

### ISSUE THREAD

**Issue by Jun47** [airsquared/blobsaver#266]
No support iPadPro2021 。。。

**Comment by aspenluxxxy** [comment]
this'll be solved whenever https://github.com/airsquared/blobsaver/issues/255 is added

**Comment by Jun47** [comment]
![image](https://user-images.githubusercontent.com/33715140/119146653-6bf79c80-ba7d-11eb-85c5-8beb1bdcaeb3.png)

**Comment by airsquared** [comment]
The new iPads have been added in the latest v3.0 beta.

**Comment by airsquared** [comment]
Added in v3.0.
