### ISSUE TITLE
“blobsaver” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by turlodales** [airsquared/blobsaver#267]
![Screen Shot 2021-05-22 at 05 54 32](https://user-images.githubusercontent.com/25443859/119214914-4476f300-bac2-11eb-80a1-640378dbce48.png)
YOUR ISSUE WILL BE CLOSED AND/OR DELETED IF YOU DO NOT FILL OUT THIS TEMPLATE

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

“blobsaver” is damaged and can’t be opened. You should move it to the Trash. this happens on my Macbook pro 2011, 2012, 2013 mac mini 2012, 2014 only with the Beta version the stable version workers well on them all except a problem then I have 10 devices I will do a bug report on that tho

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [ x ] I have made sure I am on the latest version of blobsaver
 - [ x ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [ x ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
I just fixed this in the latest beta, please try it now.

**Comment by turlodales** [comment]
fixed on my MacBook Pro 2013,
