### ISSUE TITLE
Bundle JRE & Upgrade to Java 11

### ISSUE THREAD

**Issue by airsquared** [airsquared/blobsaver#27]
Bundling a JRE with the application would reduce possible errors and make installation way easier for the user. The JRE should be shrinked using jlink which will be available once blobsaver is updated for Java 11.

**Comment by SwiftWinds** [comment]
Probably the best thing to do is use jlink and the Java 11's [Java Packaging Tool](https://openjdk.java.net/jeps/343). This depends on #35

**Comment by Stoppels** [comment]
Optimally, I'd prefer the option to choose between a version with and one without bundled JRE.

**Comment by SwiftWinds** [comment]
> The upgrade to Java 11 should also remove the activation of the dedicated GPU on the MacBook Pro if `NSSupportsAutomaticGraphicsSwitching` is set to true in the info.plist. Background mode isn't very useful if it also requires heavy graphics.

Thanks for letting us know! I didn't know that JavaFX kept using hardware acceleration even when all the stages are hidden. I'll add that to the next release's info.plist.

As for the one without bundled JRE, I don't know how useful it will be. JavaFX 11 is no longer included in OpenJDK (so the user would have to manually download it and add it to his/her PATH) and JRE versions (without JDK) are no longer offered by Oracle. Most users aren't java developers so they won't have these things installed. Also, with jlink, we can make a very small custom JRE (~30MB). The time to spend making separate builds might not be worth the few users that'd appreciate it. What do you think, @airsquared?

**Comment by airsquared** [comment]
Replaced with #155.
