### ISSUE TITLE
lockdownd error:code=-21

### ISSUE THREAD

**Issue by davex2012** [airsquared/blobsaver#270]
**Describe the bug**
Can't read ECID from device when trying to read lockdownd error:code=-21 on my MacBook Air m1 with latest big Sur. Blobsaver 2.6

Device:

iPhone XS. Jailbroken with latest taurine.

**Comment by airsquared** [comment]
Try restarting both your iOS device and MacBook and if that doesn't work try reading it with your iOS device open and trusted in Finder first.

**Comment by davex2012** [comment]
thanks. !Solved
