### ISSUE TITLE
ECID HEX to DEC conversion issue

### ISSUE THREAD

**Issue by theIuser** [airsquared/blobsaver#272]
**Describe the bug**
My iPhone 7 GSM has a HEX ECID which only contains numerical symbols no letters. When I let the blobsaver 3.0 beta read the ECID from my iPhone SE 2020 I can see my converted HEX to DEC ECID at the beginning of the shsh2 file. When I do this with my iPhone 7 the ECID at the beginning of my SHSH2 file does not get converted. Does blobsaver think my ECID is already DEC and doesn’t convert it and this making my saved blobs invalid?

**Desktop:**
 - OS Version: Windows 10 1809
 - iOS Device: iPhone 7 GSM

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
Try putting `0x` in front of your ECID and see if that allows it to recognize that your ECID is in hex.

**Comment by theIuser** [comment]
> 
> 
> Try putting `0x` in front of your ECID and see if that allows it to recognize that your ECID is in hex.

Yes, adding a 0x to my ECID does convert it to DEC but shouldn't the program recognize this by itself? A beginner maybe wouldn't have noticed this behavior and saved useless blobs?

**Comment by airsquared** [comment]
In the latest v3.0 beta, blobsaver should automatically prepend `0x` if it reads an ECID that's numerical in hex.

**Comment by airsquared** [comment]
Added in v3.0.
