### ISSUE TITLE
Error after reboot and unlock (iPhone 12, 14.2, Jailbroken)

### ISSUE THREAD

**Issue by arfarr35** [airsquared/blobsaver#273]
**Describe the bug**
On an iPhone 12, 14.2, Jailbroken using blobsaver to find the APNonce on both Jailbroken and Unjailbroken modes resulted in an error. It would do all the steps and read "Successful" then would give me a few seconds to unlock the phone before an Error popped up and the APNonce does not appear.

**Screenshots**

**Desktop:**
 - OS Version: MacOS 11.3.1
 - iOS Device: iPhone 12, 14.2, Jailbroken
 - (Beta Version 3.0 of Blobsaver)

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [ ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
What is the exact error that showed up?

**Comment by arfarr35** [comment]
I attempted it again and it’s worked now! I may have waited too long to unlock my device after the reboot the first time. It now functions perfectly, thank you so much!
