### ISSUE TITLE
Save shsh blobs to TSServer

### ISSUE THREAD

**Issue by Grandboy46** [airsquared/blobsaver#277]
Hey all, I really loved this tool specifically because it can save a12-a14 blobs without jailbreak. But I’m really scared that I will lose those blobs by formatting my computer. Is it possible to add feature to save blobs to TSServer?

**Comment by airsquared** [comment]
This is a duplicate of #224, but you could use something like [this](https://github.com/airsquared/blobsaver/wiki/Automatically-saving-blobs-to-the-cloud) to ensure you don't lose them.
