### ISSUE TITLE
Tray menu items disappear when left-click let go on macOS in background mode

### ISSUE THREAD

**Issue by SwiftWinds** [airsquared/blobsaver#29]
When clicking on the tray icon on macOS, it would show the menu icons, but as soon as the left-click was let go, the menu items would disappear. It would also disappear if the mouse moved while held down. This only occurs when in background mode and app isn't in the foreground.

 - OS: [macOS Mojave]
 - App version [2.2.1]
 - No .jar

**Comment by airsquared** [comment]
I'm unable to reproduce the issue. Try restarting your computer?

**Comment by SwiftWinds** [comment]
It seems that it was an upstream bug and it was [fixed in Java 8u201](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8211304). I'm closing this issue, since we'll be bundling OpenJDK 11 soon, which also contains the fix, and we can be certain that the user will have the latest Java.
