### ISSUE TITLE
Did I just lose my jailbreak?

### ISSUE THREAD

**Issue by atrt7** [airsquared/blobsaver#290]
I have an iPhone SE 2nd Generation that is on iOS 14.3 jailbroken with Unc0ver. I tried using blobsaver to save blobs and I tried saving apnonce. Without reading, I clicked jailbroken. It then complained about missing libirecovery.so and went into restore mode. "No big deal" I thought, and I hard restarted it. But every time I hard restart, and yes I am disconnected from a computer, it boots into restore mode. Did I just lose my jailbreak? I do not have blobs for any iOS version.

**Comment by atrt7** [comment]
I got my jailbreak back!!!!

**Comment by airsquared** [comment]
That's good! If you get stuck in recovery again, you could use either the "Exit Recovery Mode" option from the "Help" menu, the command line using `irecovery -n`, or another software like Reiboot.
