### ISSUE TITLE
lockdownd error: code=-23

### ISSUE THREAD

**Issue by flowzwastaken** [airsquared/blobsaver#292]
I am attempting to read the apnonce from my iPhone SE 2 (2020) and everytime I attempt to do so I get the error "lockdownd error: code=-23"

**Comment by airsquared** [comment]
Did you make sure you are on the latest version of blobsaver, v3.0.1?

**Comment by flowzwastaken** [comment]
> Did you make sure you are on the latest version of blobsaver, v3.0.1?

Yea I don't think I was on the correct version I will try this and let you know if it is fixed.
