### ISSUE TITLE
Location path error

### ISSUE THREAD

**Issue by PassiveModding** [airsquared/blobsaver#3]
When saving to a path with a space in it, the preset uses %20 to represent this however when hitting go it will save to the path with the name and %20 in it ie.

![image](http://discord.passivenation.com/3a.png)

saves to

![image](http://discord.passivenation.com/3b.png)

**Comment by PassiveModding** [comment]
Additional Info: 
running on windows (not sure if that would affect on mac or linux, I know you should use escaped spaces for linux though)

This is just with the path the .jar generates as a preset based on the file location when starting the program, which can be manually fixed by replacing %20 with the space and re-saving the profile

**Comment by airsquared** [comment]
Thanks for the bug report, I've fixed this in v2.1
