### ISSUE TITLE
SHSH blobs get saved multiple times

### ISSUE THREAD

**Issue by SwiftWinds** [airsquared/blobsaver#30]
Sometimes, SHSH blobs get saved more times than once to the same folder and preset. It might be related to the fact that there were 2 versions of 12.1.2 with different build numbers.

![image](https://user-images.githubusercontent.com/12981958/51203332-a6e9d400-18b5-11e9-8b71-572f78c2e3f3.png)

**Comment by airsquared** [comment]
Since this is because of the different build numbers, I will close this.
