### ISSUE TITLE
can't figure out why Cydia won't let me add a source and also futureRestore won't work

### ISSUE THREAD

**Issue by andybrunoproductions** [airsquared/blobsaver#300]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by andybrunoproductions** [comment]
I meant to say blob saver
sorry

**Comment by andybrunoproductions** [comment]
its a problem with the build manifest

**Comment by airsquared** [comment]
If you need support with futurerestore, try asking in the discord or for futurerestore support. The problem may not be with blobsaver.
