### ISSUE TITLE
Jailbreak bypass suddenly failed

### ISSUE THREAD

**Issue by teboz** [airsquared/blobsaver#308]
Might not be a bug but my
Jailbreak bypass detection failed.
The blob saving itself was ok and complete but afterwards my jailbreak can no longer bypass apps with anti jb detection. 
I’m using A-Bypass tweak and it stucked at loading 2/10 everytime I opened the requested app

It used to run ok previously. I even restore to rootfs and rejailbreak but still get detected.

Is there anyway I could undo the saving. Any help would be much appreciated.
Thanks!

Desktop
 - OS Version: 14.2.1
 - iOS Device: iPhone 12
 - JB- Taurine

 - [x] I have made sure I am on the latest version of blobsaver
 - [ x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
This issue can't be caused by saving blobs or reading from device, as it doesn't modify your device in any way. There is likely an issue with the jailbreak or bypass you are using, maybe triggered by entering recovery mode.
