### ISSUE TITLE
Cannot start Background Monitoring

### ISSUE THREAD

**Issue by gummykage** [airsquared/blobsaver#318]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
After saving about 10 devices, I selected Auto-Save Settings which brought up the menu to check them all. After they were all checked and the manual shsh was retrieved, I selected Start Background and it immediately gave an error and suggested I open the debug log and try again to get the error.

The error is: ERROR: The task XML contains a value which is incorrectly formatted or out of range.

**Screenshots**
![image](https://user-images.githubusercontent.com/9695713/127880367-b6c33da5-c04b-4f64-a97e-a919f5a9b5a1.png)

**Desktop:**
 - OS Version: Windows 7 SP1 Fully updated until end of life.
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver (USING 3.01)
 - [X] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver (Actually i did all of this and alot more... My next step if there isn't a simple solution is to boot into windows 10 and try again. All other features work on 7 so far. THANK YOU SO MUCH FRIEND <3 )

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by turannul** [comment]
Same issue MacOS Big Sur (11.5.1)

**Comment by airsquared** [comment]
This issue may be because the blobsaver tasks might not work with Windows 7, I would recommend upgrading to a different or newer OS. Windows 7 is no longer supported, so I wouldn't recommend running it anyway.
