### ISSUE TITLE
blobsaver.xml in file system?

### ISSUE THREAD

**Issue by goopy13** [airsquared/blobsaver#322]
I did a clean install of windows and a full disk backup of my old install. Where is blobsaver.xml located so I can transfer it to my new install. Only thing I found was blobsaver.cfg which was useless and a look at the source code doesn't make it obvious; looks to be an array but I don't know how to export that.

**Comment by airsquared** [comment]
It's not actually stored as an XML file on the system, it's stored in the Windows registry in `HKEY_CURRENT_USER\Software\JavaSoft\Prefs`.
