### ISSUE TITLE
Add progress bar and prevent GUI from freezing when saving blobs

### ISSUE THREAD

**Issue by SwiftWinds** [airsquared/blobsaver#33]

**Comment by bensh** [comment]
v2.3.2 GUI freezes sometimes when I click Go. there is no indication or log of what is going on, or where they error is. Program just sits on (Not responding)

**Comment by paz** [comment]
lol

**Comment by airsquared** [comment]
Fixed in commit 9cbd2b4c8f6d9a7d19edc160a97932645f3e0644, to be released in v2.5.0
