### ISSUE TITLE
Automatically update device list with iPhone Wiki API

### ISSUE THREAD

**Issue by SwiftWinds** [airsquared/blobsaver#34]
For example, parse [this](https://www.theiphonewiki.com/w/api.php?action=parse&page=Models&prop=wikitext&section=13&format=json) wikitable for iPhone device identifiers, board configs, etc. Maybe using [wikitables](https://github.com/emir-munoz/wikitables) to do it (I couldn't find a lot of Java libraries to parse wikis) :/.

**Comment by airsquared** [comment]
Some newer devices may require updated versions of tsschecker so I do not want to have users believe blobsaver supports a newer device without testing it first.
