### ISSUE TITLE
iPhone 13 series's Information is not embedded in the Application

### ISSUE THREAD

**Issue by bhkj9999** [airsquared/blobsaver#354]
**Describe the bug**
iPhone 13 series's Information is not embedded in the Application. App Behave as iPhone is detected but iPhone type is empty.

what I found is information missing in `src.main.java.airsquared.blobsaver.app.Devices.java` file.

**Screenshots**
<img width="497" alt="Screen Shot 2021-09-28 at 6 30 53 PM" src="https://user-images.githubusercontent.com/40259944/135174857-bba80c14-199d-41d7-9887-cdf475bc86ac.png">

**Desktop:**
 - OS Version: MacOS Big Sur(not related to the bug)
 - iOS Device: iPhone 13 Pro

**Checklist (place an x between the brackets to mark as completed):**
 - [ X ] I have made sure I am on the latest version of blobsaver
 - [ X ] I have checked other open issues to see if my problem has already been reported
 - [ X ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
no logs available
```

**Comment by yslupdates** [comment]
Same here for iPad Mini 6th gen
