### ISSUE TITLE
12.1.3 not found

### ISSUE THREAD

**Issue by spockers** [airsquared/blobsaver#36]
iOS 12.1.3 dropped a few hours ago.

If I use "latest" option I get 12.1.2 blobs. If I manually specify 12.1.3, I get "could not find device on iOS 12.1.3."

Has Apple changed something recently?

Using v2.2.1 on Mojave.

**Comment by airsquared** [comment]
Sometimes it takes a few hours to recognize a new version. Try again now, it should work.

**Comment by spockers** [comment]
No dice. It's not an emergency, I'll check it again tomorrow. Thanks.

**Comment by airsquared** [comment]
I'll close this, reopen it if the issue is still there.

**Comment by SwiftWinds** [comment]
Maybe elaborate on what device you're using? Maybe check the logs (Windows -> Open/Close Debug log)?

**Comment by spockers** [comment]
6s and 2 5s's. Log window is empty. Maybe there's a cache somewhere I need to clear.

**Comment by SwiftWinds** [comment]
Glad it could be resolved 👍
