### ISSUE TITLE
Save all signed + beta blobs automatically

### ISSUE THREAD

**Issue by 420Dope** [airsquared/blobsaver#362]
Is it possible to save all signed + beta blobs automatically?
With "All Signed Versions" blobsaver saves only the final versions. When we want to save beta blobs we must put in the URL manually and if a new beta comes out we must put in the new URL again.
Is there a way that blobsaver knows automatically which betas are signet and save them? IIRC shsh.host save betas automatically, so maybe there is a way to know which betas are signed.

Thanks for this great tool!

**Comment by r0my** [comment]
I have the same issue. If there is a method to automatically save beta blobs, that would be awesome!

**Comment by airsquared** [comment]
> @sickcodes 

blobsaver should already set up a systemd job on Linux (code for that is [here](https://github.com/airsquared/blobsaver/blob/e52f340ab646c264196a39457592a232925bad62/src/main/java/airsquared/blobsaver/app/Background.java#L690)).

A dockerfile would be good but I'm guessing I would need to add CLI support to blobsaver for that; currently you can only invoke background saving from the command line but you can't set it up.

**Comment by 420Dope** [comment]
@airsquared some news about the title of this issue?

**Comment by airsquared** [comment]
You can try a beta version of it [here](https://nightly.link/airsquared/blobsaver/workflows/main/master).

**Comment by 420Dope** [comment]
The "beta" from nightly is the same as the final from the release section (have checked the hashes), so there is no "beta" I can test.
https://nightly.link/airsquared/blobsaver/workflows/main/master
https://github.com/airsquared/blobsaver/releases

**Comment by airsquared** [comment]
Weird it didn't update, try downloading it directly from the [latest actions build](https://github.com/airsquared/blobsaver/actions/runs/2164788805) then.

**Comment by airsquared** [comment]
Added in v3.2.0.

**Comment by mailinglists35** [comment]
saving beta doesn't work, never worked for me. do I have to do anything else than check the "also save beta" checkbox?
