### ISSUE TITLE
Add a toggle to set program to launch on startup

### ISSUE THREAD

**Issue by SwiftWinds** [airsquared/blobsaver#37]
Windows definitely. Mac maybe not as much, since it's so easy to go into System Preferences and change one tick. I don't know about Linux (maybe add as a cron job?) or ppl using it as a .jar file.

**Comment by airsquared** [comment]
I think it's only useful to do this for Windows, using Inno Setup, so I'll work on that.

**Comment by airsquared** [comment]
A good place to put the toggle is as a checkmark in the menubar.

**Comment by airsquared** [comment]
Replaced by #157.
