### ISSUE TITLE
Icon weird

### ISSUE THREAD

**Issue by olivertzeng** [airsquared/blobsaver#375]
**Desktop:**
 - OS Version: Linux, Ubuntu
 - iOS Device: N/A

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by o8000t** [comment]
> **Desktop:**
> 
> * OS Version: Linux, Ubuntu
> * iOS Device: N/A
> 
> **Checklist (place an x between the brackets to mark as completed):**
> 
> * [x]  I have made sure I am on the latest version of blobsaver
> * [x]  I have checked other open issues to see if my problem has already been reported
> * [x]  I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver
> 
> **Log(s)**
> 
> ```
> If applicable, paste any log(s) here, on the lines between the backticks.
> ```

**Comment by o8000t** [comment]
V

**Comment by o8000t** [comment]
> **Desktop:**
> 
> * OS Version: Linux, Ubuntu
> * iOS Device: N/A
> 
> **Checklist (place an x between the brackets to mark as completed):**
> 
> * [x]   I have made sure I am on the latest version of blobsaver
> * [x]   I have checked other open issues to see if my problem has already been reported
> * [x]   I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver
> 
> **Log(s)**
> 
> ```
> If applicable, paste any log(s) here, on the lines between the backticks.
> ```

**Comment by olivertzeng** [comment]
It still doesn't work

**Comment by olivertzeng** [comment]
> V

What's checkra1n.py do I have to run it to solve the icon issue?
