### ISSUE TITLE
Background saving stop working.

### ISSUE THREAD

**Issue by 420Dope** [airsquared/blobsaver#382]
The background saving stop working a fews weeks ago. I have setup blobsaver and a few months ago and it wroks and saves my blobs. Now a fews weeks ago, since 15.1 gets released, blobsaver don't save the blobs automatically in the background so I must save my blobs manually with blobsaver. So the function itself to save blobs works but only the background saving works not. When I click `Start background` there comes a error:
```Background saving is not enabled. Try again with debug log open to check for any erros.```
When I open the debug log and click again `Start background` the error comes again and in the debug log comes:
```ERFOLGREICH: Die geplante Aufgabe "\airsquared\blobsaver\BackgrounService" wurde erfolgreich erstellt.```

The task scheduler in windows is correct but there is a note:
```Die Anforderung wurde vom Operator oder Administrator zurückgewiesen. (0x800710E0)```
What does this mean?

Screenshots:
https://imgur.com/a/FEtxM8w

Windows Server 2016 Standard
Blobsaver v3.0.4

**Comment by airsquared** [comment]
Sorry for the lare reply, but you may need administrator permissions or you have a setting/policy/permission disabled for either blobsaver or your user account (based on using Google Translate). This doesn't seem like a blobsaver related issue.

**Comment by 420Dope** [comment]
No Problem (:
Administrator permissions are not the case, my account have administrator permissions.
But I have noticed something but don't know when it is the case. In "Status" stands "Wird ausgeführt" (maybe "running" in english) and the process doesn't ended or stops so it blocks the next schedule. If I "right click" on it and "stop" the process, the status changed to "Bereit" (maybe "ready" in english) and the schedule works fine.
I will look at it and maybe I can find the issue why the process don't stop automatically when its failed or something like that.
