### ISSUE TITLE
[Request] Put some timeout

### ISSUE THREAD

**Issue by rexsllemel** [airsquared/blobsaver#384]
**Describe the what you'd like**

Please put some timeout when clicking "Read from device" while the device detected before it gives error. It is because some devices have passcode, and the app throws error while entering the passcode.

**Optional screenshot**
Add any screenshots about the feature request here.
![image](https://user-images.githubusercontent.com/15032596/147265832-d6c0fc3c-32e1-4ce9-8998-6ed17279e0aa.png)

It was when I use "Read from Device" in "Specify APNonce" my device (iPhone 10,5) is not jailbroken so I select "Unjailbroken", after exiting from recovery, I have to put the passcode first specially in clicking "trust" prompt.

**Comment by airsquared** [comment]
This issue should be fixed in v3.1
