### ISSUE TITLE
Save beta blobs for ATV 4K without specifying IPSW URL?

### ISSUE THREAD

**Issue by PencilNotPen** [airsquared/blobsaver#397]
The checkbox for "save beta blobs" requires specifying the IPSW URL for each and every build, which is labour-intensive and not automated. Is there a way to simply check the box and have the signed beta firmwares scraped from elsewhere, to save blobs for them? I think IPSW.me lists beta builds and URLs, perhaps they could be scraped from there, so that the checkbox becomes automated?

This would be useful for all devices, but particularly in the case of the ATV 4K. This device has no full IPSWs available, and the "All signed versions" checkbox in blobsaver does nothing at all, never saving a blob. For this device, "save beta blobs" is a very important option, but an option to check for signed versions in the background would be very useful. As there are no IPSWs, a URL cannot be manually specified, but it seems that URL of some kinds, to .zips, are shown here:

https://ipsw.me/otas/AppleTV6,2

With an example URL from a build page here:

http://updates-http.cdn-apple.com/2020SummerFCS/patches/061-92082/3B2806AC-7C68-443A-B807-85D9F7AFDCE3/com_apple_MobileAsset_SoftwareUpdate/eab06859de597a073b2195c1282135f8f7c4c50a.zip

So it seems that while an IPSW URL may not be supported, URLs corresponding to builds do exist, and could be scraped for signed versions? tsschecker does support manually saving ATV 4K blobs, it is the checking for and automatic saving of blobs for the ATV 4K which does not currently exist.

Many thanks for all your good work!

**Comment by Serena-io** [comment]
The program uses the ipsw.me API, which, to my knowledge, does not list betas.

**Comment by airsquared** [comment]
Those builds you link to are OTA builds, and saving blobs for them is entirely useless (you cannot futurerestore or do anything with them).

Saving blobs for beta versions without a manually specified URL on other devices is being added (see #362).
