### ISSUE TITLE
Warn A12+ users to not do "Read from device" a second time.

### ISSUE THREAD

**Issue by coworo** [airsquared/blobsaver#413]
If user is on A12+ and on an unjailbreakable version(or unjailbroken), reading the nonce again will change the generator, making prior blobs useless until a jailbreak for the version theyre on releases (if ever). AFAIK so does updating and even checking for updates. 

So i believe a big warning popping up reminding users to set ios to never check updates, and never doing "read from device" again would increase the chances of them doing a successful restore later.

**Comment by airsquared** [comment]
Fixed in v3.1.0
