### ISSUE TITLE
Apnonce mismatch A14 device

### ISSUE THREAD

**Issue by davex2012** [airsquared/blobsaver#419]
<img width="582" alt="Screenshot 2022-03-14 at 02 29 13" src="https://user-images.githubusercontent.com/15570883/158235014-f26a7244-1bdc-4150-9632-80f8340d7828.png">

Hi!
Ive saved blobs for my Iphone 12 pro from ios 14.6 to 15.3 but when trying to update using futurerestore My APnonce is mismatch. What is the problem here? Never jailbroken my device its come with ios 14.6 when i bought from store.

Now all my blob are useless. Suggestion dev?

**Comment by Viktova** [comment]
+1 same error message

**Comment by airsquared** [comment]
This is likely because you read the apnonce again using "unjailbroken" mode which gets a new APNonce every time.

This is no longer an issue starting in v3.1.0, however.
