### ISSUE TITLE
Where are configs located?

### ISSUE THREAD

**Issue by UhhhAaron** [airsquared/blobsaver#432]
Heyo, I recently had to clone and reset the internal drive in my PC. Since I have quite a few devices I save blobs for, I was wondering where blobsaver saves the config files for devices, so I could just copy the config files over instead of having to plug in all of my devices again to get ECID and APNonce. Thanks!

**Comment by Macleykun** [comment]
Is this feature what your looking for?
![image](https://user-images.githubusercontent.com/26381427/169845942-0eb125da-7def-4c51-b1a5-7b1bfba2f7fa.png)

**Comment by airsquared** [comment]
What do you see in `JavaSoft/Prefs` then?

**Comment by jojodat** [comment]
The old registry from Backup has JavaSoft/Prefs with something from jetbrains but not from  airsquared 
But maybe cause i maybe used portable install back then? 🤷‍♂️ 

Current registry has airsquared/blobsaver with the whole tree of Keys - but only the app key has a few REG_SZ values.
Just like (i think) after a fresh installation on a new system.

**Comment by airsquared** [comment]
Are you sure you're looking at the current user in the backup and not the system wide registry? If not, I'm not sure where it could have gone but you can try searching for other places Java might store preferences in the registry. Otherwise, I wouldn't be able to help.

**Comment by jojodat** [comment]
Yes, it is from current user of the only user on the system.

🤔 ok then i have to reenter all the devices and this time export the Data - just to be sure.
