### ISSUE TITLE
BlobSaver 3.1.0+ Unable to open in macOS 10.11

### ISSUE THREAD

**Issue by xaier** [airsquared/blobsaver#434]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
Being a java app not sure why it has issues opening in all OSes.
Version 3.0.4 - can be opened in macOS 10.11
Version 3.1.0+ - can't not be opened in macOS 10.11

**Screenshots**
https://ibb.co/n0nb0CX - you can see the icon represents over the app.

**Desktop:**
 - OS Version: macOS 10.11.6
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by xaier** [comment]
Any update on this?

**Comment by airsquared** [comment]
Does it give an error or a message explaining why it can't be opened? Or can you provide anything else to help me debug the issue?

**Comment by xaier** [comment]
Sure.
When you up a dialog states:
"You can’t use this version of the application “blobsaver.app” with this version of OS X.

You have OS X 10.11.6. The application requires OS X 10.12 or later."

Being a java app not sure why it's OS dependent.

**Comment by xaier** [comment]
no stale bot.

**Comment by airsquared** [comment]
I'm not sure why it seems to require 10.12 but I don't have any machines to test this on or figure out why it doesn't work. Being a 7 year old macOS version, I'm not going to try to fix the issue myself, but would welcome any PR to fix it.
