### ISSUE TITLE
Read ECID from device error

### ISSUE THREAD

**Issue by SoupSam02** [airsquared/blobsaver#44]
**Describe the bug**
ERROR:
idevicepair error.

**Screenshots**
![image](https://user-images.githubusercontent.com/47083268/51802820-e5847480-224d-11e9-946e-9adb486a3a91.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - App version: 2.2.1 (I can't update to 2.2.2, for some reason)
 - [NOT] Using .jar?

I try downloading version 2.2.2, but it keeps downloading 2.2.1.

**Comment by SwiftWinds** [comment]
>I try downloading version 2.2.2, but it keeps downloading 2.2.1.

It is downloading 2.2.2 but @airsquared forgot to change the version number in the code. Only he has direct access to the code, and he's sleeping right now so we'll have to wait until he wakes up to fix this.

**Comment by airsquared** [comment]
@SoupSam02 I've fixed the second bug, and I am using issue #20 to track the read from device error.
