### ISSUE TITLE
I have the error code -20 = lockdownd error when trying to read from my device

### ISSUE THREAD

**Issue by Constantinos11** [airsquared/blobsaver#441]
I have the error code -20 = lockdownd error when trying to read from my device

**Desktop:**
Windows 10 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
Please try the solutions listed [here](https://github.com/airsquared/blobsaver/wiki/Errors-reading-from-device).
