### ISSUE TITLE
lockdownd error: LOCKDOWN_E_MUX_ERROR (-8)

### ISSUE THREAD

**Issue by sajeevan1234** [airsquared/blobsaver#447]
lockdownd error : LOCKDOWN_E_MUX_ERROR (-8)
-------------------------------------------------------------

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [ ] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked other open issues to see if my problem has already been reported
 - [ ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
Please try the solutions listed [here](https://github.com/airsquared/blobsaver/wiki/Errors-reading-from-device).
