### ISSUE TITLE
Blobsaver on windows flooded the temp folder

### ISSUE THREAD

**Issue by 420Dope** [airsquared/blobsaver#458]
Blobsaver on Windows flooded the temp folder "C:\Users\<Username>\AppData\Local\Temp" with tons of BuildManifestXXX862427XXX5113XXX.plist files.
I have blobsaver configured to save blobs for my 5 devices every 10 minutes (don't won't miss maybe a downgrade party). Every saving period, there are comes few new files and in a fews weeks my drive is full.

**Comment by airsquared** [comment]
Fixed in v3.3.0.
