### ISSUE TITLE
Apple TV HD connected via USB-C , not able to save blobs

### ISSUE THREAD

**Issue by anonypublic** [airsquared/blobsaver#469]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [ ] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked other open issues to see if my problem has already been reported
 - [ ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by anonypublic** [comment]
Currently on tvOS 15.4

**Comment by airsquared** [comment]
Please edit your issue with more details to fill out the template and leave a comment to reopen this issue once you have edited it.
