### ISSUE TITLE
Lockdownd error: code=-5

### ISSUE THREAD

**Issue by Doofitator** [airsquared/blobsaver#478]
**Describe the bug**
Upon trying to read the ECID from the device, a popup appears containing the text "Lockdownd error: code=-5"

**Screenshots**
![image](https://user-images.githubusercontent.com/4780013/191463117-74653088-789c-4bc6-b776-67f0c89acb33.png)

**Desktop:**
 - OS Version: Fedora 36
 - iOS Device: iPad Air 1st Gen A1474 (iOS 8.4.0)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
Please try the solutions listed [here](https://github.com/airsquared/blobsaver/wiki/Errors-reading-from-device).
