### ISSUE TITLE
Use as a windows service

### ISSUE THREAD

**Issue by Ectalite** [airsquared/blobsaver#48]
You could start it as a windows service. I tested it to automate the boot, but I can't start it as it say me that the service takes too long to start (error 1053). I think you can bypass that with [that](https://support.threattracksecurity.com/support/solutions/articles/1000071019-error-1053-the-service-did-not-respond-in-a-timely-fashion-when-attempting-to-start-stop-or-pause). I aded the service with the cmd command "sc" [see here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc990289(v=ws.10)).
I think that's the best way to automate it.

![Here an image of the cmd](https://user-images.githubusercontent.com/31344054/51853504-bee73c00-2328-11e9-83e6-9a3988f14495.png)

**Comment by SwiftWinds** [comment]
Is this for starting the program automatically on system startup? If so, we're already planning to use Inno Setup or Install4J to do this. If there is some way that this is superior to either of those options, please let us know.

**Comment by Ectalite** [comment]
Ok, that's actually good and I found an alternative to my previous idea.
You could just put a shortcut to C:\ProgramData\Microsoft\Windows\Start
Menu\Programs\Startup and I think it's what Inno Setup or Install4J does.

Le mer. 30 janv. 2019 à 02:43, SwiftWinds <notifications@github.com> a
écrit :

**Comment by airsquared** [comment]
Since there is already instructions in the README for this and #37 is for making this easier, I will close this as a duplicate.
