### ISSUE TITLE
A16 iOS 16

### ISSUE THREAD

**Issue by GiftedK** [airsquared/blobsaver#484]
Hi, Thanks for the great app. Please update it to support iPhone 14.

**Comment by maksg** [comment]
I have created a PR with support for A16 on macOS. If you are using macOS version then you can download tsschecker from there and replace it in your blobsaver.app.
https://github.com/maksg/blobsaver/blob/update_tsschecker/dist/macos/Contents/MacOS/tsschecker

**Comment by mehapps** [comment]
@maksg 
I'm using macOS, replaced the tsschecker version but there still is no option to select an iPhone 14 Pro Max.
<img width="261" alt="image" src="https://user-images.githubusercontent.com/63882957/197428423-c9e758b1-1fc1-4640-86b1-619b20029e49.png">

**Comment by maksg** [comment]
@mehapps That's because I didn't update the app itself. You still need to manually provide device identifier and internal name/board configuration.

Tsschecker is just a subprogram which checks for blobs and downloads them. The version built into the blobsaver had a bug where it didn't save blobs for A16 and that's why it had to be updated.

You can find your identifier and internal name here: https://www.theiphonewiki.com/wiki/Models

**Comment by metaljay** [comment]
> @mehapps That's because I didn't update the app itself. You still need to manually provide device identifier and internal name/board configuration.
> 
> Tsschecker is just a subprogram which checks for blobs and downloads them. The version built into the blobsaver had a bug where it didn't save blobs for A16 and that's why it had to be updated.
> 
> You can find your identifier and internal name here: https://www.theiphonewiki.com/wiki/Models

Just tried this and still getting an error when saving, ive also disabled gatekeeper after giving the file correct permissions to double check

**Comment by mehapps** [comment]
> @mehapps That's because I didn't update the app itself. You still need to manually provide device identifier and internal name/board configuration.
> 
> Tsschecker is just a subprogram which checks for blobs and downloads them. The version built into the blobsaver had a bug where it didn't save blobs for A16 and that's why it had to be updated.
> 
> You can find your identifier and internal name here: https://www.theiphonewiki.com/wiki/Models

@maksg How do I actually input the device identifier etc into blobsaver?

**Comment by maksg** [comment]
> 

@metaljay Yeah, I'm using M1. In that case I have no idea how to compile it for both architectures. I used tsschecker from DanTheMann15 so if you want then you can try to compile that yourself: https://github.com/DanTheMann15/tsschecker

**Comment by maksg** [comment]
> > @mehapps That's because I didn't update the app itself. You still need to manually provide device identifier and internal name/board configuration.
> > Tsschecker is just a subprogram which checks for blobs and downloads them. The version built into the blobsaver had a bug where it didn't save blobs for A16 and that's why it had to be updated.
> > You can find your identifier and internal name here: https://www.theiphonewiki.com/wiki/Models
> 
> @maksg How do I actually input the device identifier etc into blobsaver?

@mehapps You have to tick the `Manually Specify Identifier` box.

**Comment by airsquared** [comment]
This has been fixed in v3.3.0.
