### ISSUE TITLE
Saving blobs failed. Check the board configuration or try again later.

### ISSUE THREAD

**Issue by JamesLewisLiu** [airsquared/blobsaver#487]
**Describe the bug**
Saving blobs failed. Check the board configuration or try again later.

**Screenshots**
![image](https://user-images.githubusercontent.com/17558260/195243445-245df742-483f-4a34-90c6-78bf4b5a6f5e.png)

**Desktop:**
 - OS Version: iOS16
 - iOS Device: iPhone 14 Pro iPhone15,2 MQ0W3

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
tsschecker version: 0.378-39daf4d4267ec867cccc4ccdcedaa0f9115011b8
libfragmentzip version: 0.Debug-Build: Feb 10 2022 01:34:29-RELEASE
[TSSC] manually specified generator ""
[TSSC] manually specified ECID to use, parsed "" to dec: hex:
[TSSC] manually specified apnonce to use, parsed "" to hex:
[TSSC] opening C:\Users\james\AppData\Local\Temp\BuildManifest16122321123897476605.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[WARNING] [TSSC] could not get BuildIdentity for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[Error] [TSSR] Error: could not get BuildIdentity for installType=Update
[Error] [TSSR] failed to build tss request

[Error] [TSSC] checking tss status failed!

```

**Comment by littlecxm** [comment]
seems it doesn't support latest iPhone series, so you must input `Identifier` & `Internal Name/Board Configuration` manually
e.g: iPhone 14 Pro is `iPhone15,2` `D73AP`
then it should works
reference: [link1](https://github.com/pbakondy/ios-device-list/blob/master/iphone.json) [link2](https://www.theiphonewiki.com/wiki/Category:Devices)

**Comment by airsquared** [comment]
Will be added in next version.

**Comment by airsquared** [comment]
Added in v3.3.0.
