### ISSUE TITLE
How does blobsaver work? (Q&A + Idea)

### ISSUE THREAD

**Issue by WillXProject** [airsquared/blobsaver#495]
### Discussed in https://github.com/airsquared/blobsaver/discussions/494

<div type='discussions-op-text'>

<sup>Originally posted by **WillXProject** October 28, 2022</sup>
I'm writing a batch script for TSSChecker and would like to know how blobsaver grabs all the signed versions (betas and releases) and how to replicate how it works in batch with TSSChecker, or maybe there is some way to add command line utils to blobsaver?</div>

**Comment by malicious** [comment]
Something like `tsschecker --list-ios --boardconfig n69ap` should show you the list of iOS versions. I believe it grabs it from a manifest plist published on Apple's site, or something on api.ipsw.me.

I've been using a Makefile like the following:

```
define generate_target_single
download: download-$(1)-$(2)

.PHONY: download-$(1)-$(2)
download-$(1)-$(2): tsschecker blobs
    ./tsschecker --boardconfig $(1) --ecid $(2) $(TSSCHECKER_FLAGS)

endef

define generate_target
$(foreach boardconfig,$(1),$(foreach ecid,$(2),$(call generate_target_single,$(boardconfig),$(ecid))))
endef

$(eval $(call generate_target,N69AP,ecid1 ecid2))
$(eval $(call generate_target,iPhone 12 or whatever,ecid))

.PHONY: download
download:
    @:
```

**Comment by WillXProject** [comment]
Thanks
