### ISSUE TITLE
Saving blobs failed

### ISSUE THREAD

**Issue by Revod** [airsquared/blobsaver#5]
**Describe the bug**
Saving blobs failed trying to save a beta blob
**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sierra 10.12.6 (16G1212)
 - App version 2.0

**Crash log**
If applicable, paste the crash log here.

This is what I got:
![screen shot 2018-08-14 at 5 29 49 pm](https://user-images.githubusercontent.com/10109689/44119710-03cc21ba-9fe8-11e8-9bea-6b73f5193f13.png)
![screen shot 2018-08-14 at 5 29 57 pm](https://user-images.githubusercontent.com/10109689/44119715-059c5b04-9fe8-11e8-9a15-6b58d48bf564.png)

**Comment by airsquared** [comment]
@Revod It should have automatically copied the crash log to your clipboard, could you please include that?

**Comment by Revod** [comment]
@airsquared Sorry didn't know that I was trying to search the log but no luck, this is the crash log:

```log
Version: 9ce5e00fdeaba8d7e763a028d32b11937839d2f9 - 268
[TSSC] manually specified ecid to use, parsed "E743E00298D26" to dec:4068459313466662 hex:e743e00298d26
[TSSC] opening /var/folders/c7/f5f48qn941j55dvwn1ry7l3m0000gn/T/BuildManifest2217443437173157561.plist
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

Build 16A5354b for device iPhone9,2 IS NOT being signed!
```

**Comment by airsquared** [comment]
Odd. It seems that 12.0b7 version isn't being signed by Apple.(it's not a problem with my program)
