### ISSUE TITLE
Small window always open

### ISSUE THREAD

**Issue by PassiveModding** [airsquared/blobsaver#50]
**Describe the bug**
For some reason when I have blobsaver running in the background (as a tray app) there is always a small window on my screen at all times (note this is on a second monitor)
The window can be dragged around and has a small close button on it.

This is only an issue when background checking is enabled. The window can be closed without the program being affected from what I can tell

**Screenshots**
http://discord.passivenation.com/9ue211386270.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App version: v2.2.2
 - [x] Using .jar?

**Comment by airsquared** [comment]
This is due to the way blobsaver shows notifications but will be fixed when support for native notifications is released.

**Comment by airsquared** [comment]
I will close this issue so progress can be tracked at #21.
