### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sqweeee** [airsquared/blobsaver#501]
I tried reading the APNounce on my iPhone XR and it gives me "lockdown error: LOCKDOWN_E_MUX_ERROR (8) 

It then tells me that the APNounce is not frozen

**Comment by as071589** [comment]
I'm having same issue

**Comment by airsquared** [comment]
Try the solutions listed [here](https://github.com/airsquared/blobsaver/wiki/Errors-reading-from-device).

**Comment by airsquared** [comment]
I will close this issue, but if you are still having problems you can reopen it.
