### ISSUE TITLE
start background fail

### ISSUE THREAD

**Issue by chengzi-niude** [airsquared/blobsaver#506]
**Describe the bug**
 fail to start background

**Screenshots**

![image](https://user-images.githubusercontent.com/115403380/201933360-285b6058-76cc-4024-97f8-41db0ab68247.png)

**Desktop:**
 - OS Version:win11 22000.1042
 - iOS Device: ios14.4.2 

**Checklist (place an x between the brackets to mark as completed):**
 - [ x] I have made sure I am on the latest version of blobsaver
 - [ x] I have checked other open issues to see if my problem has already been reported
 - [ x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
￯﾿ﾽ￉ﾹ￯﾿ﾽ: ￯﾿ﾽ￉ﾹ￯﾿ﾽ￯﾿ﾽ￯﾿ﾽ￯﾿ﾽ￯﾿ﾽ￯﾿ﾽￆﾻ￯﾿ﾽ￯﾿ﾽ￯﾿ﾽ￯﾿ﾽ￯﾿ﾽ "\airsquared\blobsaver\BackgroundService"￯﾿ﾽ￯﾿ﾽ
```

**Comment by airsquared** [comment]
Try changing your system language to English and let me know if it works. If that is what turns out to be the issue I have an idea for an update to fix it on those languages.

**Comment by airsquared** [comment]
Closing as stale. If you are still having this issue please comment or reopen it.
