### ISSUE TITLE
Hope to add SHSH backup support for OTA firmware

### ISSUE THREAD

**Issue by wyek1n** [airsquared/blobsaver#507]
Like "iOS 16.2 beta 3"

Thx.

**Comment by airsquared** [comment]
What's the use of saving OTA blobs? I'm not aware of any way to use them.

**Comment by wyek1n** [comment]
> What's the use of saving OTA blobs? I'm not aware of any way to use them.

For example, this TrollStore supports all versions of 15.6 beta, but does not support 15.6 RC. I think one more preparation is safe.

**Comment by airsquared** [comment]
But how would this help with that if you can't use OTA blobs?

**Comment by wyek1n** [comment]
> But how would this help with that if you can't use OTA blobs?

Can't OTA's blobs be used for downgrade? 
I know this for the first time, thank you for the answer! ～～
