### ISSUE TITLE
Hopes the API interface address can be changed

### ISSUE THREAD

**Issue by toutwoa** [airsquared/blobsaver#508]
https://www.betahub.cn/api/apple/firmwares/iPhone14,3?type=1
type  1=release  2=beta

The update speed of the previous interface address is too slow

**Comment by airsquared** [comment]
Who runs this API and how is it updated?

**Comment by mailinglists35** [comment]
can we have it integrated anyway? or how to save beta blobs manually?

**Comment by airsquared** [comment]
I'd be willing to integrate it if I can get that more information about the API first.

**Comment by toutwoa** [comment]
[official website](https://www.betahub.cn/)
They developed a BetaCat data crawler to detect firmware updates/TSS status/microblogging and other automated tasks.
Specific content can be accessed on their official website.
To avoid unnecessary trouble, it is recommended to communicate with the website developer before using the interface.

For instance
1 [iPhone 13 Pro Max update url](https://www.betahub.cn/project/betacat/iPhone14,3) Visit the website to get the latest signature status.
2 Click the latest version to copy the firmware download address
3 Use blobsaver to obtain blobs

[https://www.betahub.cn/api/apple/firmwares/iPhone14,3?type=1](https://www.betahub.cn/api/apple/firmwares/iPhone14,3?type=1)
type 1=release 2=beta
Get the latest signature firmware information of iPhone13 Pro Max Json
{
		"id": 5718,
		"created_at": "2022-12-14T02:49:36.303+08:00",
		"updated_at": "2023-01-08T14:58:32.32+08:00",
		"deleted_at": null,
		"version": "16.2",
		"build_id": "20C65",
		"size": 6582419970,
		"upload_at": "2022-12-04T00:31:34+08:00",
		"url": "https://updates.cdn-apple.com/2022FallFCS/fullrestores/032-14004/3075A008-B19E-48BF-A50F-22381293C12B/iPhone14,3_16.2_20C65_Restore.ipsw",
		"cow_url": "",
		"filename": "iPhone14,3_16.2_20C65_Restore",
		"type": 1,
		"signing": 1
	}
signing = 1 Firmware valid  
signing = -1 Invalid firmware
url:ipsw download url

**Comment by toutwoa** [comment]
You can switch languages in the upper right corner of the website

**Comment by airsquared** [comment]
Thanks for the information, I was able to add BetaHub as an automatic fallback if getting version information from ipsw.me or m1sta.xyz/betas fails.

Do you really need to have it as an option to default to to BetaHub first, or is just using it as a fallback fine?

**Comment by airsquared** [comment]
Added as fallback in v3.5.0.
