### ISSUE TITLE
Can´t install v2.2.2 on Windows Server 2016

### ISSUE THREAD

**Issue by 420Dope** [airsquared/blobsaver#51]
I can´t install v2.2.2 on Windows Server 2016.
When i click the .exe nothing happens. I can install v2.2.1 normally. After click on the .exe from v2.2.1 the installer opens and i can install it normally.
I have try to disable Windows Defender but it don´t help.

**Comment by airsquared** [comment]
This has been fixed in v2.2.3. Reopen this Github issue if the bug is still there.

**Comment by 420Dope** [comment]
Bug is still there. Installer don‘t opens after clicking on it.

**Comment by airsquared** [comment]
Does it just crash after double-clicking?

**Comment by 420Dope** [comment]
I don´t know if it crash after clicking.
When i click the blobsaver_setup.exe, the circle next to the cursor appears for maybe one second and thats it. Have also reinstall java to get sure i have the last version.
Have tried a "normal double click", "right click as administrator" but always the same result. The circle next to the cursor appears for maybe one second and thats it.
I am logged in with an administrator account so the question "Are sure you want to run this program..." don´t appear.
Version 2.2.1 i can install normal. But 2.2.2 and after not.

**Comment by 420Dope** [comment]
I have not tried the .jar file. That file works perfect. But i can´t set it for "Running on system startup". So it would be nice if you can fix it.
Can i give you more informations or something like that?

**Comment by airsquared** [comment]
Could you open `cmd.exe`, and drag and drop the blobsaver installer to the window, then press enter? It should print some output, and just send me a screenshot of that.

**Comment by 420Dope** [comment]
Strange, i have do this and there was no output. But the install process has started and i can install it.
![unbenannt](https://user-images.githubusercontent.com/42419689/52873877-5681c280-3150-11e9-9de6-d64a30891ca4.JPG)

**Comment by airsquared** [comment]
Since this seems to have been solved, I'll close this.

**Comment by 420Dope** [comment]
For me it is solved. 
Maybe you can add this as a „Tip“ to the install guide. Maybe others have the same problem with Windows Server. Just an idea ;)
