### ISSUE TITLE
Save only new BLOBs

### ISSUE THREAD

**Issue by ocp1000** [airsquared/blobsaver#513]
Currently, the way blob saver works is by saving all BLOBs all the time; It's an overkill. For example, there are now 3 signed versions: 16.1, 16.1.1 and 16.1.2. When you run blobsaver it will go over all of these versions and re-download the BLOBs every single time.
It should only download _new_ versions, i.e. ones that don't exist in the user folder.

**Comment by airsquared** [comment]
This has been added in v3.4.0.
