### ISSUE TITLE
Blobsaver detected as PUP by Avast and AVG

### ISSUE THREAD

**Issue by nik312123** [airsquared/blobsaver#521]
**Describe the bug**
[Blobsaver 3.4.0 for Apple Silicon is considered a PUP by Avast and AVG](https://www.virustotal.com/gui/file/9705418a6f4eb714acae69624a80cd461773ca95a70222c93b25ede14871049a/detection).

From trying to run the installation on my Mac, Avast quarantines `/Volumes/blobsaver/blobsaver.app/Contents/Frameworks/libirecovery.dylib`, so it may be having a problem with that file. Though, virustotal does not detect it as malicious when uploaded to it.

Probably a false positive? Worth maybe looking into and providing false positive report to Avast and AVG.

**Screenshots**
N/A

**Desktop:**
 - OS Version: macOS 12.6
 - iOS Device: N/A

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
N/A

**Comment by airsquared** [comment]
It's a false positive; likely because of libirecovery's USB access. The libirecovery included in blobsaver is just downloaded from the GitHub Actions builds in [libimobiledevice/libirecovery](https://github.com/libimobiledevice/libirecovery/actions).

**Comment by nik312123** [comment]
Right. libirecovery.dylib itself isn't showing detection when uploaded to virustotal or when scanned individually by Avast, so it is quite odd that it is showing detection for being in a dmg file for Avast and AVG. :/

**Comment by airsquared** [comment]
Yeah; I have no idea why. I don't use any antivirus software so I have no clue how they work or how they decided that blobsaver could be malicious. ¯\\\_(ツ)_/¯

I'll close this issue. If you'd like to, you can submit a false positive report to Avast or AVG.
