### ISSUE TITLE
Latest version 3.4.0 unable to save blobs for iPhone 14 Pro

### ISSUE THREAD

**Issue by rtxbae** [airsquared/blobsaver#522]
**Describe the bug**
Just upgraded to version 3.4.0 from 3.3.0. Now iPhone 14 Pro unable to save blobs and it stuck at "Saving blob" dialog box infinitely. However, iPad8,11 saved the blobs just fine in this version. (I have to screenshot the debug log since it's not copy-able as saving blob dialog box is preventing it)

**Screenshots**
See logs below.

**Desktop:**
 - OS Version: Windows 10 21H2
 - iOS Device: iPhone 14 Pro

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
![image](https://user-images.githubusercontent.com/65499097/207502022-1a87f0f2-e926-4748-ad0c-2e28843fadb2.png)

**Comment by blanxd** [comment]
looks like there's a similar issue with the macOS version, running on either arch (the same universal tsschecker binary). Works fine for <= A15 but not so well for A16 (not definitive distinctions, I only have 1 or 2 devices with each chip). Ran it manually, some logging:

    ./blobsaver.app/Contents/MacOS/tsschecker --generator <redacted> --nocache -d iPhone15,2 -s -e <redacted> --save-path /Users/<redacted>/tmp/Blobs-manual/16.2 --boardconfig D73AP -m /Users/<redacted>/tmp/iOS-manifest/BuildManifest_15,2_16.2_20C65.plist --apnonce <redacted>
    tsschecker version: 0.414-0bc6174c3c2f77a0de525b71e7d8ec0987f07aa1
    libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
    [TSSC] manually specified generator "<redacted>"
    [TSSC] manually specified ECID to use, parsed "<redacted>" to dec:<redacted> hex:<redacted>
    [TSSC] manually specified apnonce to use, parsed "<redacted>" to hex:<redacted>
    Request URL set to https://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 1... response successfully received
    also requesting APTicket for installType=Update
    Request URL set to https://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 1... response successfully received
    Request URL set to https://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 1... Request URL set to https://17.171.36.30/TSS/controller?action=2
    Sending TSS request attempt 2... Request URL set to https://17.151.36.30/TSS/controller?action=2
    Sending TSS request attempt 3... Request URL set to http://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 4... Request URL set to http://17.171.36.30/TSS/controller?action=2
    Sending TSS request attempt 5... Request URL set to http://17.151.36.30/TSS/controller?action=2
    Sending TSS request attempt 6... Request URL set to https://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 7... Request URL set to https://17.171.36.30/TSS/controller?action=2
    Sending TSS request attempt 8... Request URL set to https://17.151.36.30/TSS/controller?action=2
    Sending TSS request attempt 9... Request URL set to http://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 10... Request URL set to http://17.171.36.30/TSS/controller?action=2
    Sending TSS request attempt 11... Request URL set to http://17.151.36.30/TSS/controller?action=2
    Sending TSS request attempt 12... Request URL set to https://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 13... Request URL set to https://17.171.36.30/TSS/controller?action=2
    Sending TSS request attempt 14... Request URL set to https://17.151.36.30/TSS/controller?action=2
    Sending TSS request attempt 15... Saved shsh blobs!
    
    iOS 16.2 for device iPhone15,2 IS being signed!

It does do the job eventually, but the above TSS requests took ~13min, whereas it only takes a few seconds for older devices. The tsschecker version ````0.414-0bc6174c3c2f77a0de525b71e7d8ec0987f07aa1```` looks older than the one that was packaged with ver.3.3.0? ````0.415-7632a31c401fbca1a1003edea94d20cfdca53564```` doesn't stall like that.

**Comment by Cryptiiiic** [comment]
Technically the old version only works because its broken to begin with but it seems apple is blocking null nonce for exclusively a16 so the next update will do that. Weird that they are doing this. @blanxd

**Comment by airsquared** [comment]
This has been fixed in v3.4.1.
