### ISSUE TITLE
I have a problem ?

### ISSUE THREAD

**Issue by Toantd00** [airsquared/blobsaver#524]
Hi everyone,I am currently getting the error that beta blobs can't be saved,but if I uncheck the beta version,everything works fine again.I am using latest blobsaver version.
Iphone 11, iOS: 15.6.1

**Comment by airsquared** [comment]
There's a problem with the beta API; nothing I can do about it. It goes down occasionally but ig it seems to be happening more; maybe I can look into switching to a different API.

**Comment by airsquared** [comment]
This has actually been fixed in v3.5.0 by adding a fallback API in case the previous one doesn't work.
