### ISSUE TITLE
Load Preset: Freezes into Not Responding only for my iPhone 6, not for iPhone 7 & 5 devices? 

### ISSUE THREAD

**Issue by xbliss** [airsquared/blobsaver#53]
**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

Load Preset: Freezes into Not Responding only for my iPhone 6, not for iPhone 7 & 5 devices? 
Should it not have the same behavior for all my iPhone devices? 

**Screenshots**

I dont think will do much. I can post it with the ECID or it blurred out - whatever helps? 

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Mojave] - Win 8.1 x 64
 - App version [e.g. 1.1.1]  - 2.2.3
 - [ ] Using .jar? - .exe 

**Crash log**
If applicable, paste the crash log here.

Where do I get this from? Is it generated in certain folder as I do not see any such log file or data on the App

**Comment by xbliss** [comment]
Even when I save it for first time and request it the App freezes. 

Although: The very first time I save it the App did Freeze but I got an SHSH2 in that folder (different one). 

So would you first like to try with this specific ECID and why its causing to Freeze?

**Comment by xbliss** [comment]
So I pulled back to 2.2 and even it kinda freezes for a bit but eventually gets the SHSH2 after a bit. 

I am wondering if the background would work tomorrow (frequency of 1 day), so lets see. 

PS: Would really be good if the UI would not freeze (send a non blocking background thread with progress bar on UI)

**Comment by airsquared** [comment]
The application will freeze for certain devices on the first time you run it, but if you leave it and let it run, it should work. I will add a progress bar and run it in a separate thread in the next version(see #33).

**Comment by xbliss** [comment]
It just got worse on 2.3.0 
https://i.imgur.com/rI2IeBU.png

**Comment by airsquared** [comment]
I have found out the error, and will have this fixed in the next version(I need to update tsschecker).

**Comment by airsquared** [comment]
See issue #60.

**Comment by xbliss** [comment]
This seems to have been resolved on 2.3.1 - Just installed and used it. Will report back after trying it out few more times

**Comment by paz** [comment]
After updating from 2.4 to 2.4.1 it freezes forever, previously didn't freeze at all. Probably have to update tsschecker again?

**Comment by airsquared** [comment]
@paz Please see issue #136.
