### ISSUE TITLE
An unknown error occurred when try to read device blob saver not working

### ISSUE THREAD

**Issue by Antgithub1** [airsquared/blobsaver#551]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

Here is A video I made on youtube to show its not working.
https://youtu.be/vfPiJosPE9o

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by Antgithub1** [comment]
Here is A video on youtube to show proved its not working  ](https://youtu.be/vfPiJosPE9o)

**Comment by airsquared** [comment]
Please fill out the template.
