### ISSUE TITLE
How do I use the CLI feature?

### ISSUE THREAD

**Issue by PassiveLemon** [airsquared/blobsaver#552]
I have installed it on a Fedora system using the rpm with `dnf install` but I am unsure how to actually use the CLI. I can't find any info about it other than the release saying to use `BLOBSAVER_CLI_ONLY` in my environment. I can't even use `blobsaver help` because that isn't an available command to use.

**Comment by airsquared** [comment]
`blobsaver` isn't added to the path by default when installed from RPM.

The executable is located at `/opt/blobsaver/bin/blobsaver`. You can either use the fully qualified path to call it, symlink it into a directory in your path (like `/usr/local/bin`), or add the directory `/opt/blobsaver/bin` to your path.

**Comment by PassiveLemon** [comment]
Ah okay thanks. I was able to get it running. I'm not familiar with Fedora so I am unsure if that is typical behavior of RPMs.
