### ISSUE TITLE
java lock up

### ISSUE THREAD

**Issue by billymac101** [airsquared/blobsaver#56]
**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

Keeps freezing, Windows 7  when clicking save (not Responding)  java hangup
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Mojave]
 - App version [e.g. 1.1.1]
 - [ ] Using .jar?

Windows 7 Ultimate SP1 2600
Amd Phenom XII 3.2 ghz
12 gb ram  Sata Raid 
2.2.3 Blob saver
Java V8 build 201  (build 1.8.0_201-b09)

**Crash log**
If applicable, paste the crash log here.

Description:
  A problem caused this program to stop interacting with Windows.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	javaw.exe
  Application Version:	8.0.201.9
  Application Timestamp:	5c15be66
  Hang Signature:	1bc3
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Hang Signature 1:	1bc32ff51e8550a28bb81f0679c91e17
  Additional Hang Signature 2:	6a0a
  Additional Hang Signature 3:	6a0a8bbfff5a159e057c2a80ae6eb16e
  Additional Hang Signature 4:	1bc3
  Additional Hang Signature 5:	1bc32ff51e8550a28bb81f0679c91e17
  Additional Hang Signature 6:	6a0a
  Additional Hang Signature 7:	6a0a8bbfff5a159e057c2a80ae6eb16e

**Comment by airsquared** [comment]
If you don't force close/quit it, does it eventually finish(after like a minute)?

**Comment by billymac101** [comment]
Hi , no it hangs forever, I let it sit to see if java recovered

**Comment by airsquared** [comment]
Can you please fill out the information in the "Desktop" section of the issue?

**Comment by billymac101** [comment]
Desktop info updated, tried recently 1st blob saved fine, after that hung up, random

**Comment by airsquared** [comment]
You seem to have a beta version of an older java. Can you try updating to the latest non-beta Java 8?(version 1.8.0_202) [Direct download link](https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-i586-iftw.exe)

**Comment by billymac101** [comment]
Deleted all java and resinstalled, now all 9 ECID blob presets are gone, I installed new version 2.3 and still presets missing, blobs are still in Users folder but all saved presets missing

**Comment by billymac101** [comment]
Hello again, after a fresh install of Java I recreated my ECID preset list that vanished and started saving blobs again, first 2 saved ok, third preset slow to save, fourth blob I tried to save it java locked up again.

Description:
  A problem caused this program to stop interacting with Windows.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	javaw.exe
  Application Version:	8.0.201.9
  Application Timestamp:	5c15be66
  Hang Signature:	15d9
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Hang Signature 1:	15d9986c59e0879640738c853fb01be2
  Additional Hang Signature 2:	a861
  Additional Hang Signature 3:	a861d5b0a29fb4f538b02fe942fdda25
  Additional Hang Signature 4:	15d9
  Additional Hang Signature 5:	15d9986c59e0879640738c853fb01be2
  Additional Hang Signature 6:	a861
  Additional Hang Signature 7:	a861d5b0a29fb4f538b02fe942fdda25

**Comment by airsquared** [comment]
I know the problem now, it will be fixed in the next version(see issue #60).

**Comment by billymac101** [comment]
Thanks, Good work, awesome app !  I  did notice certain ECID's lock it up, iPhone 6 seems to lock up java ?

**Comment by airsquared** [comment]
This issue has been fixed in v2.3.1.
