### ISSUE TITLE
Save devices and configurations as a file

### ISSUE THREAD

**Issue by antoniu200** [airsquared/blobsaver#565]
Hi,

**Context:**
Sometimes, I run into issues with Windows that require a full reinstallation. So I don't have to reconfigure every program each time this happens, I just copy over to the new installation the AppData and ProgramData folders, while programs that don't require any kind of integration into Windows are kept on a drive separate from Windows (Blobsaver, games, etc.).

**Describe the what you'd like:**
Blobsaver does not save its configurations in the form of a file inside its directory or inside AppData or ProgramData, since every time I have reinstalled Windows in the last 2 weeks (probably 6 times at this point), all my saved devices and configurations have been erased.
Is it possible this feature could be implemented?

Thank you!

**Comment by airsquared** [comment]
You can export/import saved devices to/from a file from the "File" menu.
