### ISSUE TITLE
Save new blob as separate file

### ISSUE THREAD

**Issue by antoniu200** [airsquared/blobsaver#566]
**Describe the what you'd like**
When saving a second, third, etc. blob of the same iOS version for the same device, don't overwrite old blob, but rather save it as a separate file.

**Comment by airsquared** [comment]
What use case do you have for this? Wouldn't it just be a duplicate of the exact same file?

**Comment by antoniu200** [comment]
I thought I read somewhere that for newer devies SHSH2 Blobs could only be used one time, so for more than one restore I would need more than one Blob.
Seems like I was wrong.

But different Blobs for the same device and software version have slightly different contents, [diffchecker](https://www.diffchecker.com/) can confirm this.
