### ISSUE TITLE
JavaFX?

### ISSUE THREAD

**Issue by BartmanEH** [airsquared/blobsaver#57]
blobsaver says I need JavaFX (JDK is installed). I click OK go to download link, install the latest JDK, same problem--just get JavaFX error on launch.

This is always the case with every Java dependent application. They can never find a JDK install in my standard Win10 setup.

**Comment by airsquared** [comment]
Install Java8(from java.com) alongside your exisiting java installation.

**Comment by BartmanEH** [comment]
thanks for your help. I've tried that a couple of times. it says installation completed but the JavaFX error continues.

**Comment by airsquared** [comment]
Can you please post a screenshot of the error?

**Comment by BartmanEH** [comment]
![image](https://user-images.githubusercontent.com/6135879/53370542-fb07bf80-391b-11e9-8455-712c32eefb10.png)

**Comment by SwiftWinds** [comment]
Could you open command prompt and type `java -version`? Maybe it's not included in your PATH or the one in your PATH points to JDK 11, which does not include JavaFX. In the future, this won't be a problem because we will bundle JRE with blobsaver.

**Comment by BartmanEH** [comment]
"C:\WINDOWS\system32>java - version
Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit."

Ugh, I just hate Java. It's been like this for YEARS. Millions of people have to have Java and millions of people suffer these ridiculous issues that should be all but gone now in 2019.

**Comment by BartmanEH** [comment]
In order to avoid opening another issue just to ask for information but as invited in the Wiki for "What are blobs and why do you need them?" -> If you need more information or something isn't clear, create a new issue on github." I realize that it's not the purpose of this tool to educate noobs like me but the documentation (for which I am exceedingly grateful that there is any at all!) kinda seems to prefer beta iOS versions for reasons I can't understand. In the "Getting the required information" wiki entry, it jumps right into filling in fields but emphasizes "Saving blobs for beta versions".

1. Can I get blobs for full GM releases? How? Do I use the ipsw link from "https://www.theiphonewiki.com/wiki/Firmware" instead? This is completely unclear.
2. does my device need to have the firmware version installed in order to get the blob for that version? Also not clear but perhaps intuitively obvious to anyone who understands blobs.
3. does the device have to be connected? also not obvious except to allow blobsaver to extract the ECID automatically.

Appreciate your support. Once these fundamentals become clear to me, I'm happy to help augment your wiki page with this sort of "getting started" information.

**Comment by BartmanEH** [comment]
I can't be the only one with this JavaFX error.

**Comment by SwiftWinds** [comment]
> 1. Can I get blobs for full GM releases? How? Do I use the ipsw link from "https://www.theiphonewiki.com/wiki/Firmware" instead? This is completely unclear.

Yeah, you can get blobs for full GM releases. The IPSW link and everything applies for beta versions only. No need to get any required information with GM releases except your ECID and device model (which blobsaver can read from an iOS device connected to your computer).  

> 2. does my device need to have the firmware version installed in order to get the blob for that version? Also not clear but perhaps intuitively obvious to anyone who understands blobs.

No.

> 3. does the device have to be connected? also not obvious except to allow blobsaver to extract the ECID automatically.

Only when extracting the ECID, board config, and device model.

> Appreciate your support. Once these fundamentals become clear to me, I'm happy to help augment your wiki page with this sort of "getting started" information.

Thanks! I appreciate it 👍 


And, to get to your point with JavaFX, I haven't had any problems with Java getting detected but JavaFX not getting detected. That is very weird. I compiled a version that doesn't check for `Class.forName("javafx.application.Application")`. Download it [here](https://www13.zippyshare.com/v/yaIFJ5MU/file.html) and run `java -jar <path to downloaded jar file>` in command prompt. It'll probably crash, but don't worry. Just tell me what the output is.

Thanks.

**Comment by BartmanEH** [comment]
That version runs just fine. It will be clunky for me to launch it that way all the time though.

**Comment by airsquared** [comment]
Can you try the Linux download of blobsaver and run that with `java -jar <path to jar file>` and tell me if it works?

> Ugh, I just hate Java. It's been like this for YEARS. Millions of people have to have Java and millions of people suffer these ridiculous issues that should be all but gone now in 2019.

> I can't be the only one with this JavaFX error.

Nobody else seems to have had this error, it's just a problem with your machine/installation.

**Comment by Nikostito** [comment]
Have the same error on ubuntu linux 18.04 even though I have openjfx installed...

**Comment by airsquared** [comment]
@Nikostito Please run `java -version` in the terminal and tell me the output.

**Comment by airsquared** [comment]
Sorry, I accidentally closed this.

**Comment by Nikostito** [comment]
Hey I saved the problem by installing the Oracle java sdk version 8. Apparently openjfx and oracle sdk when they were split on version 10, are not recognizing one another. So I had to delete openjfx 11 and install java sdk 8. No everything gets recognized. May be you can include it in the readme for other users facing the same issue!:)

**Comment by BartmanEH** [comment]
I don't think installing old versions of JDK is the way to go. We have enough security concerns to worry about and downgrading Java just isn't possible for many of us. I tried to have both old and new running at the same time but that doesn't work. The solution is to make it work with the latest version of Java.

**Comment by airsquared** [comment]
@BartmanEH Java 8 is not a security problem(many commerical systems, Google's servers included, run on Java 8). It's similar to how Python2 is still being supported even though Python3 is out. Java allows you to easily install multiple versions of Java side-by-side(for example I have Java8, Java11, and Java12 all installed at the same time), so you don't need to downgrade Java.

**Comment by airsquared** [comment]
@BartmanEH What are all the versions of Java you had installed previously?

**Comment by BartmanEH** [comment]
I uninstalled 5 things but didn't record them all. 64bit JDK 11, an SE thing, JDK 8 201 and 202

**Comment by airsquared** [comment]
Can you try installing only the java versions you actually need, and see if blobsaver still works?

**Comment by BartmanEH** [comment]
Argh, I had to install JDK 11 for Net Beans and now blobsaver no longer works despite java-version reporting:
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode)

**Comment by BartmanEH** [comment]
so.... like.... blobsaver ain't working again

**Comment by airsquared** [comment]
Can you try [this](https://nofile.io/f/SBCaBoShEAT/blobsaver_setup.exe) version of blobsaver? Make sure to completely uninstall the previous version of blobsaver before trying this one.

**Comment by AdrianGri** [comment]
I am having this issue and just found this post now. Has anyone found a solution to this?

**Comment by airsquared** [comment]
@Leafs5 Can you try [this](https://nofile.io/f/SBCaBoShEAT/blobsaver_setup.exe) version of blobsaver? Make sure to completely uninstall the previous version of blobsaver before trying this one.

**Comment by Leafs5** [comment]
@airsquared I am getting a different error when I try to open that file. 
![Here's the error message.](https://user-images.githubusercontent.com/33498069/54561550-481b0680-499b-11e9-8cff-74ef8cb280c8.png)

**Comment by SwiftWinds** [comment]
ehh, try this one? https://www18.zippyshare.com/v/I8zhmlca/file.html

I just removed the check for JavaFX all together so if it doesn't find it it will just crash. Tell me if it crashes or not mkay? 

If it does, then that means that launch4j starts blobsaver differently than `java -jar`, and @airsquared and I will have to workarounds.

**Comment by BartmanEH** [comment]
I uninstalled the previous version and installed this version but nothing happens when I run it. Crashing maybe?

**Comment by SwiftWinds** [comment]
Yep. \*sigh\* 

To fix this, maybe we should try to temporarily switch to install4j until we can get GraalVM to work, @airsquared?

**Comment by airsquared** [comment]
@BartmanEH and @Leafs5 How about [this](https://nofile.io/f/h6kv67xYTte/blobsaver_setup.exe) version? Make sure to completely uninstall the previous version of blobsaver before trying this one.

**Comment by BartmanEH** [comment]
Works!

**Comment by SwiftWinds** [comment]
Eyy!

**Comment by Leafs5** [comment]
Works for me too! @airsquared

**Comment by airsquared** [comment]
This issue has been fixed in blobsaver v2.3.1.
