### ISSUE TITLE
Support for Windows ARM64

### ISSUE THREAD

**Issue by tyhallcsu** [airsquared/blobsaver#573]
Currently, the software doesnt support ARM64 Windows

Request to support ARM on Windows. Especially Windows Virtualization on MAC.

Screenshot:
<img width="508" alt="CleanShot 2023-05-23 at 05 38 55@2x" src="https://github.com/airsquared/blobsaver/assets/16804423/86284a0d-0030-46e1-8af6-8fccf07c5c94">

**Comment by airsquared** [comment]
The latest [nightly build](https://nightly.link/airsquared/blobsaver/workflows/main/master) allows installation on Windows ARM.

However, why would you want to run blobsaver through virtualized Windows when you can run it directly on your Mac?

**Comment by tyhallcsu** [comment]
> 

Thank you, I will try this.

The reason is, I got a Mac and moved my old Windows config/install over to a virtualized version.

**Comment by tyhallcsu** [comment]
Update: it works! Thanks a bunch

**Comment by tyhallcsu** [comment]
Update: solved.
