### ISSUE TITLE
Error Issue when trying to save Beta Blobs

### ISSUE THREAD

**Issue by Carbon271** [airsquared/blobsaver#577]
**Describe the bug**
The Error that occurs happens when saving beta blobs I don't know if it has to do with the new iOS 17 Betas or not but if so it would be nice to save some blobs for iOS 17.

**Screenshots**

![Screenshot 2023-06-09 110029](https://github.com/airsquared/blobsaver/assets/13841284/180e1944-5ae8-4081-ad34-0c97408c7687)

**Desktop:**
 - OS Version: Win 11
 - iOS Device: iPhone 13 Mini

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.Debug-Build: Dec 14 2022 19:22:07-RELEASE
[TSSC] manually specified generator "0x1228a0a6e1b5f695"
[TSSC] manually specified ECID to use, parsed "2313C0E6B801E" to dec:617083963146270 hex:2313c0e6b801e
[TSSC] manually specified apnonce to use, parsed "d6be1ff083c105f805b033f6fba4e398655295b8de16282fd6413d8a6220ec88" to hex:d6be1ff083c105f805b033f6fba4e398655295b8de16282fd6413d8a6220ec88
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!
```

**Comment by airsquared** [comment]
This is because the first iOS 17 beta requires a developer account and blobsaver currently doesn't know how to handle that. As a workaround, you can disable including beta blobs until this first beta becomes unsigned.

This will be fixed in the next version.
