### ISSUE TITLE
The installer does not open on Windows 10

### ISSUE THREAD

**Issue by lucabecca** [airsquared/blobsaver#581]
### Bug description:
The installer (blobsaver-3.5.0.exe) does not open.
I also tried the v3.4.1 but nothing change.
The installer of the old version that I currently have installed (v3.0.4) opens normally without any problem.

### Desktop:
 - OS Version: Windows 10

### Checklist:
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
Is there any error message shown or are there any logs? Are you on 32-bit?

**Comment by jirikrepl** [comment]
version 3.5.1 on intel mac couldnt be opened .
I have the same dialog message if I open by icon, or from console.
No errors in console.
I tried to downgrade back to 3.5.0 and it worked for me fine.

#### terminal screenshot below
---

<img width="780" alt="Screenshot 2023-06-27 at 10 56 19" src="https://github.com/airsquared/blobsaver/assets/2588479/99df7d4b-8a2a-4bf6-ac31-24bf49a53044">

**Comment by lucabecca** [comment]
> Is there any error message shown or are there any logs? Are you on 32-bit?

I'm on 64 bit, the installer doesn't create any log in the current folder, in my case the Download folder.

**Comment by lucabecca** [comment]
Later I’ll try the latest version.

**Comment by airsquared** [comment]
@jirikrepl see https://github.com/airsquared/blobsaver/wiki/Unable-to-open-on-macOS

Not sure why the right click and open option is no longer working though 🤔

**Comment by airsquared** [comment]
This issue will be closed due to inactivity. If the problem is still present, please comment to reopen the issue.
