### ISSUE TITLE
The 3.5.1 ARM version won't run on macOS

### ISSUE THREAD

**Issue by Semmelstulle** [airsquared/blobsaver#589]
**Describe the bug**
Trying to run Blobsaver 3.5.1 ARM makes macOS complain about corrupted binary, 3.5.0 works just fine.

**Screenshots**
<img width="409" alt="image" src="https://github.com/airsquared/blobsaver/assets/74740271/7623ca31-3c19-4812-a4a2-97fecfd6f0ee">

**Desktop:**
 - OS Version: macOS 13.4.1

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment]
https://github.com/airsquared/blobsaver/wiki/Unable-to-open-on-macOS

**Comment by airsquared** [comment]
I have added zip downloads that don't seem to show this error message when they have the quarantine attribute.
