### ISSUE TITLE
Crash with "Blobsaver.app" is damaged (intel)

### ISSUE THREAD

**Issue by Pois0ne** [airsquared/blobsaver#593]
**Describe the bug**
Crash with "Blobsaver.app" is damaged. Problem with intel version of blobsaver on intel mac. File is not corrupted, i downloaded it several times

**Screenshots**
<img width="656" alt="Screenshot 2023-07-06 at 21 57 27" src="https://github.com/airsquared/blobsaver/assets/90562595/72c56a6d-1131-472d-8822-7c57bd047708">

**Desktop:**
 - OS Version: MacOS Ventura 13.3.1 (22E261)
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
https://github.com/airsquared/blobsaver/wiki/Unable-to-open-on-macOS

**Comment by airsquared** [comment]
I have added zip downloads that don't seem to show this error message when they have the quarantine attribute.
