### ISSUE TITLE
Allow user to apply devices to app using custom plist/xml generated with Python

### ISSUE THREAD

**Issue by Merculous** [airsquared/blobsaver#597]
There are cases where I cannot read from the device, which is not a blobsaver issue.

I know you can import an xml, however when I've tried reading the one blobsaver makes using plistlib from Python, it cannot read this file, mostly due to the different naming of tags and such.

Is there any way to either convert a plain xml to one that your app or java can read? Otherwise if not, could there be an addition to next version which does this?

The format is almost identical, but uses different names for tags and plistlib only parses stuff that isn't used in this app.

**Comment by airsquared** [comment]
The XML file that blobsaver produces with export is not a plist. Have you tried using a standard XML reader instead of a plist reader?

**Comment by Merculous** [comment]
I totally forgot that Python has an actual xml library. I'm not familiar on how to use it but I've honestly never encountered an actual pure xml until I've tried this. Every other occasion its always been a plist in xml format, whatever xml means in a plist sense. I'll try to figure how to to use Python's xml library, I'm already confused on how to do this proper using that library. Plain easy and lazy way is just to use plistlib and treat "xml" as plist data I guess.

Everything parsed mine and blobsaver's except Xplist, but that does explicitly say its a plist editor.
