### ISSUE TITLE
Blobs fail to save for iPad 5's

### ISSUE THREAD

**Issue by Willpower719** [airsquared/blobsaver#6]
**Describe the bug**
Blobs fail to save for any iPad 5 devices. I would assume this is because it is an A9 device and would require you to enter a board configuration but the box is grayed out?

**Desktop (please complete the following information):**
Windows 10
App Version 2.1

**Log** 
Running: [C:\Users\*****\AppData\Local\Temp\tsschecker_windows31230200655061554.tmp.exe, -d, iPad6,11, -s, -e, 000005B42B0C29F9, --save-path, E:\Dropbox\Back up\SSH\Test, -i, 11.4.1]
Version: 9ce5e00fdeaba8d7e763a028d32b11937839d2f9 - 268

[TSSC] manually specified ecid to use, parsed "ECID_HERE" to dec:ECID_HERE hex:ECID_HERE

[TSSC] opening firmware.json

[JSON] counting elements

[JSON] parsing elements

[TSSC] got firmwareurl for iOS 11.4.1 build 15G77

[TSSC] opening Buildmanifest for iPad6,11_11.4.1_15G77

[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2018/ios/091-77690-20180709-8140758C-7C1C-11E8-ACF5-B25B544C24EB/iPad_64bit_TouchID_ASTC_11.4.1_15G77_Restore.ipsw

[Error] [LFZP] failed to open url

[Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl http://updates-http.cdn-apple.com/2018/ios/091-77690-20180709-8140758C-7C1C-11E8-ACF5-B25B544C24EB/iPad_64bit_TouchID_ASTC_11.4.1_15G77_Restore.ipsw

[Error] [TSSC] checking tss status failed!

**Comment by airsquared** [comment]
I've fixed this in v2.2
