### ISSUE TITLE
Unable to save blobs for some devices

### ISSUE THREAD

**Issue by razer86** [airsquared/blobsaver#60]
**Describe the bug**
Unable to save blobs for iPad Mini 3

**Desktop (please complete the following information):**
Java file on Windows
tsschecker on OS 10.14

**Crash log**
I know this is really a tsschecker issue, but s0uthwest doesnt have issues enable on the repo

`tsschecker --boardconfig j86map -e 4364ba491b0 -s ./ --latest` Works and saves the blob
`tsschecker --boardconfig j86map -e 4364ba491b0 -s ./ --latest --generator 0x1111111111111111` Results in endless 'Unhandled status code 128' when using the 330 release, and has been updated to stop trying on the first '128 error' with 336 release.

**Comment by razer86** [comment]
Build 336 is able to save the ticket the generator successfully

**Comment by airsquared** [comment]
@s0uthwest & @SwiftWinds updated tsschecker to solve this issue in [this](https://github.com/s0uthwest/tsschecker/commit/bef8186e22d22db396b8c5a2f42ed4ba43563fef) commit, so I will just need to update the bundled version of tsschecker.

**Comment by gummykage** [comment]
Also cannot save blob on iphone 7+. Thank you for your help.

**Comment by airsquared** [comment]
I've fixed the issue, and it will be released in the next update this weekend.
