### ISSUE TITLE
iPhone XS Max wrong code

### ISSUE THREAD

**Issue by ipodtouchdude** [airsquared/blobsaver#61]
In the app you have the iPhone XS Max codes labeled wrong.

e.g. in the app you have 
iPhone XS Max (iPhone11,4) = D331AP
iPhone XS Max (China) (iPhone11,6) = D331pAP

When it is 

iPhone XS Max (China) (iPhone11,4) = D331AP
iPhone XS Max (iPhone11,6) = D331pAP

**Comment by airsquared** [comment]
Thanks for the bug report, I'll have this fixed in the next version.
