### ISSUE TITLE
Can't enable background saving

### ISSUE THREAD

**Issue by SudoTheHacker** [airsquared/blobsaver#613]
Please remove the following line and the text above it before submitting this issue:

**Describe the bug**
When clicking on Start background, the app return with an error saying "Background saving i snot enabled. Try again with the debug log open to check for any errors.”

**Screenshots**
![Capture](https://github.com/airsquared/blobsaver/assets/78053418/3a79d46a-324d-41c0-9616-324c1babb485)

**Desktop:**
 - OS Version: Windows 10
 - iOS Device: iOS 16.5.1 (Does not matter in that case)

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked other open issues to see if my problem has already been reported
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
Wrote to: C:\Users\Antoine\AppData\Local\Temp\blobsaver_background_service2644177830618330546.xml
Op￯﾿ﾽration r￯﾿ﾽussie : la t￯﾿ﾽche planifi￯﾿ﾽe "\airsquared\blobsaver\BackgroundService" a ￯﾿ﾽt￯﾿ﾽ cr￯﾿ﾽ￯﾿ﾽe.
If applicable, paste any log(s) here, on the lines between the backticks.
EMPTY

**Comment by airsquared** [comment]
Could you please translate what it says in the logs? Seems to be in a different language.

**Comment by airsquared** [comment]
Try the latest [nightly build](https://nightly.link/airsquared/blobsaver/workflows/main/master) and let me know if that fixes it.

**Comment by airsquared** [comment]
Fixed in v3.5.2.

**Comment by SudoTheHacker** [comment]
It was in french it seems your log does not use UTF-8. I am not sure, but it can't show french character the message was probably "Opération réussie : la tache planifiée "\airsquared\blobsaver\BackgroundService" a ￯﾿ﾽt￯﾿ﾽ cr￯﾿ﾽ￯﾿ﾽe.
If applicable, paste any log(s) here, on the lines between the backticks."
Can't read what's written next, but it's the error message. "Opération réussie : la tache planifiée" means "Operation succesfull: the planned task", but the new update fixed it so it's fine.
