### ISSUE TITLE
Linux x64 3.5.2 does not have an archive

### ISSUE THREAD

**Issue by PassiveLemon** [airsquared/blobsaver#615]
**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

The archive for Linux x64 3.5.2 does not exist.
It does exist for older versions though.

**Screenshots**
![image](https://github.com/airsquared/blobsaver/assets/72527881/36aa44da-8f5a-42a4-b33c-118005258a36)

**Comment by airsquared** [comment]
I changed the file extension to .tgz and forgot to change the URL. Fixed now.
