### ISSUE TITLE
Freeze on startup after upgrade to 3.5.2

### ISSUE THREAD

**Issue by treyturner** [airsquared/blobsaver#616]
**Describe the bug**
App freezes on startup after upgrading from 3.5.1 to 3.5.2 on Windows 11.

Possibly worth noting this Windows installation is a VM that is administered via RDP.

**Screenshots**
<img width="342" alt="image" src="https://github.com/airsquared/blobsaver/assets/1878152/cbdf205e-5ca6-41a2-8f0b-7b06ea415a7e">

**Desktop:**
 - OS Version: Win 11 21H2 (22000.2295)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

Well I've restarted, but I haven't yet uninstall/reinstalled because I am worried my profile is going to be lost

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```
I haven't found the logs yet, but I'll post them if I do. I understand this is a bit short of information right now but I can definitely follow any additional troubleshooting or debug steps, just let me know.

**Comment by treyturner** [comment]
I just noticed that if I leave the window in this state and come back to the session much later, the app UI has loaded and everything seems to work. But if I restart it, it again hangs for some undetermined length of time during startup. Definitely several minutes or more.

**Comment by airsquared** [comment]
If you downgrade back to v3.5.1 does it work fine as normal?

**Comment by treyturner** [comment]
Great question, no it does not. Hmm. 🤔

**Comment by treyturner** [comment]
I'm going to wait for it to load again, export my profile, then will try an uninstall and reinstall.

**Comment by treyturner** [comment]
Unfortunately uninstalling and reinstalling (v3.5.2) doesn't seem to fix the problem.

I tried to open the app by pasting `"C:\Program Files\blobsaver\blobsaver.exe" | findstr x*` into cmd, but no logging is produced before the window freezes. Thanks for your time; let me know if you have any other ideas.

**Comment by airsquared** [comment]
In that case it doesn't seem like an issue with blobsaver if it just coincidentally started happening when v3.5.2 was released but worked before. I'll close this as unreproducible, but if you are able to get somehow get some logs then I can look into it further.
