### ISSUE TITLE
Unable to save beta blobs

### ISSUE THREAD

**Issue by marshmello-colin** [airsquared/blobsaver#62]
Version:  - 
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "*ECID*" to dec:3421766524338234 hex:c28141a30003a
[TSSC] opening C:\Users\---\AppData\Local\Temp\BuildManifest2078014167464015037.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[Error] [TSSR] Error: could not get id0 for installType=Update
[Error] [TSSR] faild to build tssrequest

[Error] [TSSC] checking tss status failed!

**Comment by airsquared** [comment]
You still haven't filled out the issue template. Could you please fill out the issue template? In case you can't see the template, [here](https://github.com/airsquared/blobsaver/issues/new?assignees=&labels=bug&template=bug_report.md&title=) is a link.
