### ISSUE TITLE
macOS Sonoma: 5 second delay on opening and window not focused

### ISSUE THREAD

**Issue by airsquared** [airsquared/blobsaver#627]
On macOS 14/Sonoma, the application will take about 5 extra seconds to open and may not be focused after opening. 

This is an issue with JavaFX, waiting on JavaFX 21.01 to be released on October 17.

**Comment by emranovin** [comment]
I've stuck on MacOS Sonoma on 2nd launch of blobsaver app.
Here is my hang log:
[blobsaver_2024-02-25-100035_My-MacBook-Pro.log](https://github.com/airsquared/blobsaver/files/14395510/blobsaver_2024-02-25-100035_My-MacBook-Pro.log)
