### ISSUE TITLE
Can you add iPhone 15 Pro Max support?

### ISSUE THREAD

**Issue by garyakimoto** [airsquared/blobsaver#628]
Can you add iPhone 15 Pro Max support? because there is no iPhone 15 Pro max support yet.

Thanks

**Comment by Mangaia** [comment]
I'm also looking for this!

**Comment by airsquared** [comment]
Available in latest nightly builds.

**Comment by garyakimoto** [comment]
> Available in latest nightly builds.

Thank you so much, it help a lot for me

**Comment by airsquared** [comment]
Seems the nighly builds might not have updated, please try again.

**Comment by garyakimoto** [comment]
> Seems the nighly builds might not have updated, please try downloading a new nightly build again.

Thanks , but it same... still nothing to save

**Comment by Mangaia** [comment]
> Seems the nighly builds might not have updated, please try downloading a new nightly build again.

I used the latest nightly build and can confirm that it worked fine! I was able to select the 15 Pro Max. Thank you!

**Comment by garyakimoto** [comment]
> > Seems the nighly builds might not have updated, please try downloading a new nightly build again.
> 
> I used the latest nightly build and can confirm that it worked fine! I was able to select the 15 Pro Max. Thank you!

me2, I can select 15 Pro Max too, but I can't save 15 Pro Max's blobs

**Comment by Mangaia** [comment]
> > > Seems the nighly builds might not have updated, please try downloading a new nightly build again.
> > 
> > 
> > I used the latest nightly build and can confirm that it worked fine! I was able to select the 15 Pro Max. Thank you!
> 
> me2, I can select 15 Pro Max too, but I can't save 15 Pro Max's blobs did you check your blobs saved location??? it's empty only, nothing saved there
> 
> Normally the popup will show you which version 's blobs you saved, but for 15 Pro Max... just popup "Success !" only

I just checked and yeah, they are there. Try to fully remove blobsaver and download the nighly build and try again. It worked fine for me. Also I've saved them to TSS Saver and without betas as it is bugged right now. Both ECID and APNonce were directly read from the device.

**Comment by garyakimoto** [comment]
> > > > Seems the nighly builds might not have updated, please try downloading a new nightly build again.
> > > 
> > > 
> > > I used the latest nightly build and can confirm that it worked fine! I was able to select the 15 Pro Max. Thank you!
> > 
> > 
> > me2, I can select 15 Pro Max too, but I can't save 15 Pro Max's blobs did you check your blobs saved location??? it's empty only, nothing saved there
> > Normally the popup will show you which version 's blobs you saved, but for 15 Pro Max... just popup "Success !" only
> 
> I just checked and yeah, they are there. Try to fully remove blobsaver and download the nighly build and try again. It worked fine for me. Also I've saved them to TSS Saver and without betas as it is bugged right now. Both ECID and APNonce were directly read from the device.

Thank you, I just try the solution you say remove them and reinstall, after I reinstall them, it show a error, and I find the problem with new install: blobsaver installer without tsssaver.exe inside, we need to download the new one and put it to lib folder, after that I can save my blobs now. thanks

**Comment by airsquared** [comment]
> problem with new install: blobsaver installer without tsssaver.exe inside, we need to download the new one and put it to lib folder, after that I can save my blobs now. thanks

Fixed in the latest nightly build, seems like there was a problem with copying files on installation.

**Comment by garyakimoto** [comment]
> > problem with new install: blobsaver installer without tsssaver.exe inside, we need to download the new one and put it to lib folder, after that I can save my blobs now. thanks
> 
> Fixed in the latest nightly build, seems like there was a problem with copying files on installation.

Thank you so much

**Comment by airsquared** [comment]
I'll leave this issue open until the next version is released.
