### ISSUE TITLE
Check for blobs that have been saved already on the device?

### ISSUE THREAD

**Issue by terminalN00b** [airsquared/blobsaver#629]
Hey, so I'm pretty new to the whole SHSH blobs game and I still am unable to fully understand what they are, but that doesn't matter I guess. I've seen a comment on a tutorial video for downgrading an iPhone 5 to iOS 6, that stated something about "before doing this, look for saved blobs on your phone, and you should be able to downgrade without using this custom firmware". How do I check for already saved blobs on an iPhone? Because I have bought an old 5 that still runs iOS 7, and I kinda wanna get it down to 6 again. So can I do it with this tool? I tried installing TinyUmbrella on my macbook, with no success.

Kind regards

**Comment by airsquared** [comment]
blobsaver can't help with this. Ask for help in [r/Jailbreak](https://www.reddit.com/r/jailbreak/) or in either of the Discord servers:

- [r/Jailbreak Discord](https://discord.gg/jb)
- [FDR Bureau](https://discord.gg/96wCSnwYVX)
