### ISSUE TITLE
Retry

### ISSUE THREAD

**Issue by mendel3** [airsquared/blobsaver#63]
**Describe the what you'd like**
An auto-retry, for when blobs are being signed on and off (like now)

Currently, I am doing it with a batch script but a GUI would be nicer

**Comment by airsquared** [comment]
Wouldn't that be the background mode? You can set it to try every minute using the background mode.

**Comment by mendel3** [comment]
Wait, before you close it, what is the minimum time for background mode?

**Comment by airsquared** [comment]
> You can set it to try **every minute** using the background mode.

**Comment by mendel3** [comment]
What about one try after another, so like every 5 seconds?

**Comment by airsquared** [comment]
That would get your IP address blacklisted/blocked by Apple if you repeatedly do it one after another.
