### ISSUE TITLE
Specific operating system version

### ISSUE THREAD

**Issue by haltlos** [airsquared/blobsaver#633]
In which situation would you want to obtain a blob for a specific (unsigned) version of iOS (or iPadOS)? I am referring to this field:

![Screen Shot 2023-10-17 at 22 32 11](https://github.com/airsquared/blobsaver/assets/4324234/2ab184f1-17c6-42d3-8ef4-17613d77eb9b)

From what I have read, a blob can only be obtained for a signed os version. So I'd like to understand why blobsaver even offers the option to specify a different version.

**Comment by airsquared** [comment]
It's just to check the signing status of one specific version, if there are many versions currently being signed.
