### ISSUE TITLE
Is this an error?

### ISSUE THREAD

**Issue by minhdanlc124** [airsquared/blobsaver#635]
Why is my file only 8kb?
Here is the path to my device shsh file
https://stor.tsssaver.1conan.com/tsssaver/shsh/6242177629880350/

**Comment by airsquared** [comment]
No that's normal. blobsaver doesn't control TSS Saver anyway, so if there is a problem you will have to contact 1Conan instead.

**Comment by minhdanlc124** [comment]
> Không, đó là điều bình thường. Dù sao thì blobsaver cũng không kiểm soát TSS Saver, vì vậy nếu có vấn đề, bạn sẽ phải liên hệ với 1Conan.

Do you know how I should use it?

**Comment by airsquared** [comment]
> > Không, đó là điều bình thường. Dù sao thì blobsaver cũng không kiểm soát TSS Saver, vì vậy nếu có vấn đề, bạn sẽ phải liên hệ với 1Conan.
> 
> Do you know how I should use it?

I don't use TSS Saver myself, you will have to ask elsewhere.
