### ISSUE TITLE
Release Blobs saving as 0 Bytes to TSSSaver but saving to computer as the real size.

### ISSUE THREAD

**Issue by glowberri** [airsquared/blobsaver#643]
**Describe the bug**
When saving blobs along with the ECID, APNonce, and Generator. It saves as the actual size to the computer but when saving to TSSSaver it's 0 bytes and considered invalid although I just saved valid blobs. It saved blobs up to 17.0.2 on TSSSaver before it gave me an Internal Server Error for future blobs. The screenshots below will show the Internal Server Error, the list of blobs to show that it stopped saving after 17.0.2, The inside of the directory 17.0.2 on TSSSaver, and the comparison on how 17.0.2 blobs on TSSSaver are somehow invalid and how a 17.1.1 blob on my computer cannot be checked through TSSSaver becuase of the Internal Server Error.

**Screenshots**
![image](https://github.com/airsquared/blobsaver/assets/116987350/ac656317-9d6b-48b5-b2c1-3cf5e1abcd26)
![image](https://github.com/airsquared/blobsaver/assets/116987350/532e400f-9061-4d5f-aed8-95a245886927)
![image](https://github.com/airsquared/blobsaver/assets/116987350/9929b5bd-2404-449b-b0e1-1293b42220a1)
![image](https://github.com/airsquared/blobsaver/assets/116987350/62ac9793-faab-41e2-9ce6-cb0fa944aeb4)
![image](https://github.com/airsquared/blobsaver/assets/116987350/32f654f2-6c82-48d3-86c5-ae99affd6920)

**Desktop:**
 - OS Version: Windows 10 Pro x64
 - iOS Device: iPhone SE (2nd Generation) running iOS 16.1.2

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked other open issues to see if my problem has already been reported
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s) (As I could only get the 17.1.1 saving blobs log)**
```
iosVersions = [IOSVersion[versionString=17.1.1, buildid=21B91, ipswURL=https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-96610/0343030F-BCF7-49DD-ACE2-549BC0A900CB/iPhone12,8_17.1.1_21B91_Restore.ipsw, signed=true]]
Running: [C:\Program Files\blobsaver\lib\tsschecker.exe, --nocache, --save, --device, iPhone12,8, --ecid, 1439D20286402E, --boardconfig, d79ap, --apnonce, 9d2654e5a91c9882739b657c0ded86915b58c077ed7af7167b3015db60df8fd0, --generator, 0x4442e82c910a77f1, --save-path, C:\Users\Canar\Blobs, --build-manifest, C:\Users\Canar\AppData\Local\Temp\BuildManifest9624235554233176216.plist]
tsschecker version: 0.431.0-75f5c11420946c9d2b6ce3bacb35f0b7beddc84a-RELEASE
libfragmentzip version: 0.VERSION_COMMIT_COUNT_not_set-VERSION_COMMIT_SHA_not_set Build: Oct  1 2023 13:40:45-RELEASE
[TSSC] manually specified generator "0x4442e82c910a77f1"
[TSSC] manually specified ECID to use, parsed "1439D20286402E" to dec:5693073682481198 hex:1439d20286402e
[TSSC] manually specified apnonce to use, parsed "9d2654e5a91c9882739b657c0ded86915b58c077ed7af7167b3015db60df8fd0" to hex:9d2654e5a91c9882739b657c0ded86915b58c077ed7af7167b3015db60df8fd0
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket for installType=Update
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket without a nonce
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Saved shsh blobs!

iOS 17.1.1 for device iPhone12,8 IS being signed!
{deviceIdentifier=iPhone12,8, boardConfig=d79ap, ecid=5693073682481198, generator=0x4442e82c910a77f1, apnonce=9d2654e5a91c9882739b657c0ded86915b58c077ed7af7167b3015db60df8fd0}
```

**Comment by airsquared** [comment]
blobsaver doesn't control TSS Saver, so if there is a problem you will have to contact 1Conan instead.
