### ISSUE TITLE
Unable to open from double-click on macOS

### ISSUE THREAD

**Issue by Techman749** [airsquared/blobsaver#7]
**Describe the bug**
When double-clicking on the Jar in macOS it fails to launch, however, it works when I make it run from the terminal when running "java -jar /path/to/jar"

**Screenshots**
<img width="504" alt="screen shot 2018-09-19 at 10 04 03 am" src="https://user-images.githubusercontent.com/7294113/45758410-8786b700-bbf3-11e8-873e-9f1afbd17235.png">

**Desktop:**
 - OS: macOS High Sierra 10.13.6
 - App version: 2.1

**Crash log**
I'm not sure where I'd find a crash log to be able to help with this.

**Comment by hEvaDer** [comment]
@Techman749 It's a bug in a few builds it will be fixed in the next version.

**Comment by hEvaDer** [comment]
[https://www.reddit.com/r/jailbreak/comments/9gqb2k/tip_use_blobsaver_to_save_blobs_automatically_so/e67jg69](url)

**Comment by airsquared** [comment]
@hEvaDer He can't even open the application, because there is some error with macOS.

**Comment by airsquared** [comment]
@Techman749 Does the error appear in Console.app?

**Comment by Techman749** [comment]
Let me see if I can try and figure out if this problem pertains only to BlobSaver or my entire Java installation. I recently updated to Java 10 for my college classes that require JDK. I'll report back if I figure out the issue. At this point I'm wondering if it's my fault and not the program's. I'll keep you all posted.

**Comment by airsquared** [comment]
@Techman749 Can you open this application: `/Applications/Utilities/Console.app` and see if there is an error/log there for java?

**Comment by airsquared** [comment]
Have you solved the problem? Can I close the issue?

**Comment by Techman749** [comment]
@airsquared Sorry for the radio silence these past couple of days. Been busy with college. I'll confirm this tonight and I'll get back to you for sure.

**Comment by Techman749** [comment]
@airsquared Count this bug as a false alarm/solved. I guess juggling 2 different versions of Java for my coding classes in college on my Mac made it unable to open from double clicking the Jar. I got it working now.
