### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by Lobolin** [airsquared/blobsaver#74]
**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Mojave]
 - App version [e.g. 1.1.1]
 - [x] Using .jar?(place an x between the brackets if true)

**Crash log**
If applicable, paste the crash log here.

Version:  - 
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "001C44AC0488002E" to dec:7956804948983854 hex:1c44ac0488002e
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[Error] failed to download file from=https://api.ipsw.me/v2.1/firmwares.json/condensed to=C:\Users\ADMINI~1\AppData\Local\Temp\firmware.json CURLcode=35
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] parsing firmware.json failed

**Comment by airsquared** [comment]
Please create a new issue with the issue template filled out.
