### ISSUE TITLE
Error Starting TSSCHECKER. Log mentions something like "%1 not compatible with your OS"

### ISSUE THREAD

**Issue by coupedeebaybee** [airsquared/blobsaver#75]
_**Describe the bug**
A clear and concise description of what the bug is and the expected behavior._
### ### 
**I click 'GO' after inputing my device information, two prompts pop up that say 'error starting TSSSERVER', afterwards it appears to save my blobs to the correct folder. Using the Blob Checker I can confirm that the blobs are valid, but I just want to know what is causing the errors to begin with. Java Log says something like "%1 not compatible with your OS please contact software vendor", which doesn't make any sense whatsoever.**
### ### 

_**Screenshots**
If applicable, add screenshots to help explain your problem._
### ### 
**Too lazy to prnt scrn, use ur imagination bro**
### ### 

_**Desktop (please complete the following information):**_
### ### 
 - OS: **WIN 7 32BIT**
 - App version: **2.3.0**
 - [**X**] Using .jar?(place an x between the brackets if true)
### ### 

_**Crash log**
If applicable, paste the crash log here._

### ### 
**java.io.IOException: Cannot run program "C:\Users\Coupe\.blobsaver_bin\tsschecker": CreateProcess error=216, This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher**
### ###

**Comment by airsquared** [comment]
blobsaver doesn't support 32 bit devices.(you should really upgrade your computer, 32 bit devices are very old)

**Comment by airsquared** [comment]
blobsaver doesn't support 32 bit computers (I'm surprised it even saved blobs). You should really upgrade your computer.
