### ISSUE TITLE
lockdownd error: code=-13

### ISSUE THREAD

**Issue by kid1carus** [airsquared/blobsaver#76]
**Describe the bug**
Error popup saying:  lockdownd error: code=-13

**Screenshots**
![Screen Shot 2019-04-05 at 11 32 59 AM](https://user-images.githubusercontent.com/45052773/55639266-f9d97600-5796-11e9-9306-ed15f1ccb455.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5 Beta (18F96h)
 - App version 2.3.2
 - [x] Using .jar?(place an x between the brackets if true)

**Comment by airsquared** [comment]
If you open iTunes, is it able to recognize your device and is it able to get the ECID? And when you run blobsaver, is your phone turned on and unlocked?

**Comment by airsquared** [comment]
I will close this issue due to OP not responding. Please reopen this issue if you need help.

**Comment by SwiftWinds** [comment]
I believe lockdownd error -13 is that there is no device. Maybe we should check for error -13 and say that no device was detected?

**Comment by airsquared** [comment]
It's not: https://www.libimobiledevice.org/docs/html/lockdown_8h.html

**Comment by SwiftWinds** [comment]
Oh. Nevermind then
