### ISSUE TITLE
Error:  saving blobs failed

### ISSUE THREAD

**Issue by julienkrijnen8** [airsquared/blobsaver#78]
Hi. I am getting this error when I try to save blobs for iOS 12.1.3 B4.

-----------------------------------------------------------------------------------------------------------

Version: 8ce7eaf0a731c39eb1e08ed6725303d6d6dd2eee - 340
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "5733951685592" to dec:5733951685592 hex:5370a2743d8
[TSSC] opening C:\Users\JULIEN~1\AppData\Local\Temp\BuildManifest1728527445495097441.plist
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

Build 16D5039a for device iPhone6,2 IS NOT being signed!

**Comment by airsquared** [comment]
Please fill in the information in the bug report issue template.
