### ISSUE TITLE
Support for more than 10 devices and Betas

### ISSUE THREAD

**Issue by JustAn0rmalUser** [airsquared/blobsaver#79]
I’d like to have support for 50 devices or more and support for Betas without downloading the IPSW like in TSSChecker in Terminal and better automatic Blobs saving, so that it automatically saves Blobs for any version that gets signed if you activate the setting for it.

**Comment by airsquared** [comment]
50+ devices? How do you have so many? I might be able to add support for more devices, but 50 is a lot. What do you mean without downloading the IPSW file? You don't have to download it, you just put in the URL. Doesn't blobsaver already save blobs for all signed versions?

**Comment by airsquared** [comment]
If you have 50+ devices, you're probably better off just setting up a cron job. Other features are already implemented.
