### ISSUE TITLE
Can not assign apnonce

### ISSUE THREAD

**Issue by peierh** [airsquared/blobsaver#8]
**Describe the bug**
When I assign the apnonce, it always going wrong. My iphone is 6S+ with Board number N66AP.
The apnoce number I get it from web site: https://mrmad.com.tw/tsschecke-web-save-ios10-shsh

**Screenshots**
![1](https://user-images.githubusercontent.com/22253962/45923806-7fe04e80-bf22-11e8-9af4-f0cb916ec061.png)
![2](https://user-images.githubusercontent.com/22253962/45923807-8242a880-bf22-11e8-8487-722061350f0f.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional X64
 - blobsaver-2.1.jar

**Crash log**
Version: 9ce5e00fdeaba8d7e763a028d32b11937839d2f9 - 268
[TSSC] manually specified ecid to use, parsed "50F0AAB14C8" to dec:5562161632456 hex:50f0aab14c8
[TSSC] manually specified apnonce to use, parsed "15400076bc4c35a7c8caefdcae5bda69c140a11bce870548f0862aac28c194cc" to hex:15400076bc4c35a7c8caefdcae5bda69c140a11bce870548f0862aac28c194cc
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest iOS: 12.0
[TSSC] got firmwareurl for iOS 12.0 build 16A366
[TSSC] opening Buildmanifest for iPhone8,2_12.0_16A366
[Error] [TSSR] parsed APNoncelen != requiredAPNoncelen (32 != 20)
[Error] [TSSR] failed to populate tss request
[Error] [TSSR] faild to build tssrequest

[Error] [TSSC] checking tss status failed!

**Comment by airsquared** [comment]
> [Error] [TSSR] parsed APNoncelen != requiredAPNoncelen (32 != 20)

Looking at this line, it probably means the apnonce is not the correct length. Where did you get this apnonce from?

**Comment by peierh** [comment]
I get it from web site: https://mrmad.com.tw/tsschecke-web-save-ios10-shsh

**Comment by peierh** [comment]
Thanks for remind, and Refilled done!!

**Comment by airsquared** [comment]
The website you are using(I'm using Google Translate so this may be wrong) says that the apnonce is only for iPhone X and other A11 devices. The iPhone 6s+ is not an A11 device.

**Comment by peierh** [comment]
Oh, I understand it, thanks a lot.
