### ISSUE TITLE
Unable to save blobs

### ISSUE THREAD

**Issue by kikokoko95** [airsquared/blobsaver#80]
**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Mojave]
 - App version [e.g. 1.1.1]
 - [ ] Using .jar?(place an x between the brackets if true)

**Crash log**
If applicable, paste the crash log here.

**Comment by airsquared** [comment]
Please create a new issue with the issue template filled out.
