### ISSUE TITLE
Program closes instantaneously after opening (Windows)

### ISSUE THREAD

**Issue by usern132** [airsquared/blobsaver#84]
When I open the blobsaver shortcut created in the Start Menu in Windows (which leads to _"C:\Program Files (x86)\blobsaver\blobsaver.exe"_), the GUI window opens up very briefly and closes automatically within a fraction of a second. There's no evidence of the program running in the system tray. However, the process responsible for the Java Platform SE binary (_javaw.exe_) can be found running in the Task Manager.
After the window has closed, when I click on the shortcut again, an error message appears saying _"blobsaver already running, exiting"_. This message continues to appear every time I open the program until I kill the _javaw.exe_ process. After killing it and opening the program again, the same issue described at the beginning occurs.

I have tried uninstalling and reinstalling the program several times, but things have remained the same. Also, I have checked that I'm running the latest version of Java.

I'm using **Windows 8.1 Pro (64 bits)** and running the latest version of blobsaver currently available, which is **2.3.2**.

Attached is a screen recording of the issue, recorded at 60fps for clearer slow motion if necessary. It's the only file found inside the _.zip_.

[Video demonstration.zip](https://github.com/airsquared/blobsaver/files/3188770/Video.demonstration.zip)

**Comment by airsquared** [comment]
Could you send a screenshot/video of your taskbar/tray when opening blobsaver? Because it's still running but you can't see the window, it means it's running in background mode.

**Comment by usern132** [comment]
I guess it's running in the background, but the icon never appears in the taskbar like it's supposed to.

**Comment by airsquared** [comment]
Could you please share a screenshot of your taskbar?

**Comment by usern132** [comment]
Attached is a screenshot of all the icons present in the taskbar after opening blobsaver.

![Screenshot](https://user-images.githubusercontent.com/24841687/57986752-83ec4e00-7a68-11e9-8db7-9729fe6270b6.png)

As it can be seen, despite blobsaver presumably running in background mode, its icon doesn't show up.

**Comment by airsquared** [comment]
Sorry about not replying earlier, I've been really busy recently. Try [this](https://www.top-password.com/blog/fix-onedrive-icon-missing-from-windows-10-taskbar/), except instead of enabling OneDrive, enable blobsaver (if that doesn't work try enabling "Always show all icons in the notification area").

**Comment by usern132** [comment]
blobsaver doesn't show up on the list, and enabling _Always show all icons in the notification area_ doesn't show the program's icon in the taskbar.

**Comment by airsquared** [comment]
Try removing another icon from the taskbar and see if it shows up. blobsaver might also be showing as a blank icon for some reason so see if there might be empty icons or try clicking on empty spaces to see if blobsaver actually is there.

**Comment by usern132** [comment]
![imatge](https://user-images.githubusercontent.com/24841687/64687945-f26f7480-d47a-11e9-84c8-3f5d659133ca.png)
These are all the icons in the taskbar. The blank one in the middle is from another program which is completely unrelated to blobsaver.

**Comment by airsquared** [comment]
Try this: [blobsaver-windows.exe.zip](https://github.com/airsquared/blobsaver/files/3721485/blobsaver-windows.exe.zip) (make sure to restart and uninstall the older version of blobsaver before installing this)

**Comment by airsquared** [comment]
Closing this issue due to no response from OP, please create a new issue if you have any further problems.
