### ISSUE TITLE
iOS 13 beta 1 error

### ISSUE THREAD

**Issue by cgeek-yt** [airsquared/blobsaver#88]
**Bug Description :**
Impossible to save SHSH blobs due to error on the IPSW download link recognition (the download link is valid) because the app says "Failed to load manifest"

**Error Log**
Version: 9be4a1cd83ba0a38082b0634b3a0ade8526f2733 - 330
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "C61A234810026" to dec:3485049013993510 hex:c61a234810026
[TSSC] opening /var/folders/20/lrh135f1523g2yh30_9lvrmh0000gn/T/BuildManifest5917654020072987342.plist
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!

**Desktop :**
 - OS: macOS Catalina (10.15) Beta 1 (19A471t)
 - App version : 2.2.3

**Comment by AnthoPakPak** [comment]
I'm using v2.3.2 and encounter the same issue. Here is the link used [https://developer.apple.com/services-account/download?path=/WWDC_2019/iOS_and_tvOS_IPSWs_for_Jun_3_2019_Seed/iPhone_4.7_P3_13.0_17A5492t_Restore.ipsw](https://developer.apple.com/services-account/download?path=/WWDC_2019/iOS_and_tvOS_IPSWs_for_Jun_3_2019_Seed/iPhone_4.7_P3_13.0_17A5492t_Restore.ipsw)

**Comment by airsquared** [comment]
Apple has disabled downloading the IPSW if you don't have an Apple Developer Account. You will need to wait until Apple releases the beta publicly to save blobs for it.

**Comment by AnthoPakPak** [comment]
I do have a developer account, but I think there is no way to log in? No problem if so.

**Comment by airsquared** [comment]
Oh. Unfortunately there is no way to log in from blobsaver to download developer-only IPSWs, but Apple usually releases the beta version to the public soon after.

Apple has recently released iOS 13b2, and it is no longer behind the login wall so you should be able to save blobs for iOS 13b2 now.

**Comment by AnthoPakPak** [comment]
Indeed it works without problem for iOS 13b2, thanks for sharing the info @airsquared :)
