### ISSUE TITLE
iPod Touch 7th Generation (iPod9,1) fails 

### ISSUE THREAD

**Issue by dude22072** [airsquared/blobsaver#89]
**Describe the bug**
Even when manually specifying the device identifier of "iPod9,1" blobs for the iPod Touch 7th Generation fail to save. I get the error message: 
Could not find: "Null"

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - App version [2.3.2]
 - [ ] Using .jar?(place an x between the brackets if true)

**Crash log**
N/a

**Comment by airsquared** [comment]
Could you please try [this](https://github.com/airsquared/blobsaver/files/3312979/blobsaver-windows.exe.zip)? It should have the new iPod in the device picker now. (when opening the app it'll ask you to upgrade to v2.3.2 even though it's a lower version, just ignore that)

**Comment by dude22072** [comment]
Get an error sayings to check the board configuration: http://puu.sh/DJ4VG/62b2d45980.png
Used the "Read from Device" option to fill out EDID and Identifier.

**Comment by airsquared** [comment]
Could you please try again now? Sometimes you'll just need to wait a few hours or up to a day when you get that error(I think it has something to do with Apple's servers). I just tested it myself and it should work now. If it still doesn't work, I may be able to fix it.

**Comment by dude22072** [comment]
Still same error trying it now.

**Comment by airsquared** [comment]
Try [this](https://github.com/airsquared/blobsaver/files/3318527/blobsaver-windows.exe.zip), should hopefully be fixed now. (make sure to uninstall blobsaver before installing this)

**Comment by dude22072** [comment]
All appears to be in working order now! Thank you,

**Comment by tommyim** [comment]
blobsaver v2.3.2 still not work.

**Comment by airsquared** [comment]
@tommyim Use the link from above which should work for the iPod 7th gen, I haven't added support yet to the normal releases.

**Comment by tommyim** [comment]
OK Thank you!
