### ISSUE TITLE
Cannot save blobs

### ISSUE THREAD

**Issue by Assfugil** [airsquared/blobsaver#90]
**Describe the bug**
Title
**Screenshots**
![未命名](https://user-images.githubusercontent.com/42699250/60395921-2f5ee700-9b6d-11e9-9fb0-657b3405bb14.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - App version 2.3.2

**Log(s)**
```
java.io.IOException: Cannot run program "C:\Users\nick\.blobsaver_bin\tsschecker": CreateProcess error=216, 此版的 %1 與您執行的 Windows 版本不相容。請檢查電腦的系統資訊，以查看您需要 x86 (32 位元) 或 x64 (64 位元) 版的程式，然後連絡軟體發行者。
```

**Comment by airsquared** [comment]
blobsaver currently doesn't support 32-bit devices, but I may add it at some point in the future. You should upgrade your computer, 32-bit processors are very old.
