### ISSUE TITLE
Download blobs for iOS 12.3.2

### ISSUE THREAD

**Issue by La-te** [airsquared/blobsaver#92]
Looks like blobs are not saved for iOS 12.3.2

**Comment by airsquared** [comment]
What device are you on?

**Comment by airsquared** [comment]
iOS 12.3.2 is only available for the iPhone 8 Plus, and no other device so unless you have an iPhone 8 Plus, you won't be able to get iOS 12.3.2.

**Comment by airsquared** [comment]
Closing this issue. Please open a new issue if this problem happens again.
