### ISSUE TITLE
Add ECID as default to Save file path

### ISSUE THREAD

**Issue by bensh** [airsquared/blobsaver#97]
**Describe the what you'd like**

1. I like to keep my blobs organised. Please could we have the option, maybe a check box to set the default save path to append the ECID on the end. e.g c:\myfile\blobs\ [ECID]

2. Also could we have the option to choose how many preset we want please, I could use a few more. Maybe have the default as 10, but if you want more you can adjust the value in the Options menu

3. A recent list of other save locations

**Optional screenshot**
Add any screenshots about the feature request here.

**Comment by airsquared** [comment]
Superseded by #265.
