### ISSUE TITLE
There was an error starting tsschecker.

### ISSUE THREAD

**Issue by Kakaka999** [airsquared/blobsaver#99]
java.io.IOException: Cannot run program "C:\Users\USER\.blobsaver_bin\tsschecker": CreateProcess error=216, %1의  버전이 실행 중인 Windows 버전과 호환되지 않습니다. 컴퓨터의 시스템 정보를 확인하고 소프트웨어 게시자에게 문의하십시오 (version not compatible with running version of Windows. Check the system information and contact the software publisher.)

**Comment by Kakaka999** [comment]
32 bit

**Comment by airsquared** [comment]
Sorry, but blobsaver doesn't support 32-bit computers. You should really upgrade your computer.
